/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKPIT_H
#define _MOCKPIT_H

#include "Types.h"
#include "pit.h"

void Mockpit_Init(void);
void Mockpit_Destroy(void);
void Mockpit_Verify(void);




#define pit_init_Ignore() pit_init_CMockIgnore(__LINE__)
void pit_init_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define pit_init_Expect() pit_init_CMockExpect(__LINE__)
void pit_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_pit_init_CALLBACK)(int cmock_num_calls);
void pit_init_StubWithCallback(CMOCK_pit_init_CALLBACK Callback);
#define PIT_Config_Ignore() PIT_Config_CMockIgnore(__LINE__)
void PIT_Config_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define PIT_Config_Expect(cmock_arg1, cmock_arg2) PIT_Config_CMockExpect(__LINE__, cmock_arg1, cmock_arg2)
void PIT_Config_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, uint32_t cmock_arg2);
typedef void (* CMOCK_PIT_Config_CALLBACK)(uint8_t cmock_arg1, uint32_t cmock_arg2, int cmock_num_calls);
void PIT_Config_StubWithCallback(CMOCK_PIT_Config_CALLBACK Callback);

#endif
