/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockfootpedal.h"

typedef struct _CMOCK_poll_footpedal_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_poll_footpedal_CALL_INSTANCE;

typedef struct _CMOCK_foot_pedal_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_foot_pedal_init_CALL_INSTANCE;

typedef struct _CMOCK_check_fs_stuck_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_check_fs_stuck_CALL_INSTANCE;

typedef struct _CMOCK_fs_any_button_pressed_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_fs_any_button_pressed_CALL_INSTANCE;

static struct MockfootpedalInstance
{
  int poll_footpedal_IgnoreBool;
  uint8_t poll_footpedal_FinalReturn;
  CMOCK_poll_footpedal_CALLBACK poll_footpedal_CallbackFunctionPointer;
  int poll_footpedal_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE poll_footpedal_CallInstance;
  int foot_pedal_init_IgnoreBool;
  uint8_t foot_pedal_init_FinalReturn;
  CMOCK_foot_pedal_init_CALLBACK foot_pedal_init_CallbackFunctionPointer;
  int foot_pedal_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE foot_pedal_init_CallInstance;
  int check_fs_stuck_IgnoreBool;
  uint8_t check_fs_stuck_FinalReturn;
  CMOCK_check_fs_stuck_CALLBACK check_fs_stuck_CallbackFunctionPointer;
  int check_fs_stuck_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE check_fs_stuck_CallInstance;
  int fs_any_button_pressed_IgnoreBool;
  bool fs_any_button_pressed_FinalReturn;
  CMOCK_fs_any_button_pressed_CALLBACK fs_any_button_pressed_CallbackFunctionPointer;
  int fs_any_button_pressed_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE fs_any_button_pressed_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfootpedal_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.poll_footpedal_IgnoreBool)
    Mock.poll_footpedal_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.poll_footpedal_CallInstance, cmock_line, "Function 'poll_footpedal' called less times than expected.");
  if (Mock.poll_footpedal_CallbackFunctionPointer != NULL)
    Mock.poll_footpedal_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.foot_pedal_init_IgnoreBool)
    Mock.foot_pedal_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.foot_pedal_init_CallInstance, cmock_line, "Function 'foot_pedal_init' called less times than expected.");
  if (Mock.foot_pedal_init_CallbackFunctionPointer != NULL)
    Mock.foot_pedal_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.check_fs_stuck_IgnoreBool)
    Mock.check_fs_stuck_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.check_fs_stuck_CallInstance, cmock_line, "Function 'check_fs_stuck' called less times than expected.");
  if (Mock.check_fs_stuck_CallbackFunctionPointer != NULL)
    Mock.check_fs_stuck_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.fs_any_button_pressed_IgnoreBool)
    Mock.fs_any_button_pressed_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.fs_any_button_pressed_CallInstance, cmock_line, "Function 'fs_any_button_pressed' called less times than expected.");
  if (Mock.fs_any_button_pressed_CallbackFunctionPointer != NULL)
    Mock.fs_any_button_pressed_CallInstance = CMOCK_GUTS_NONE;
}

void Mockfootpedal_Init(void)
{
  Mockfootpedal_Destroy();
}

void Mockfootpedal_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.poll_footpedal_CallbackFunctionPointer = NULL;
  Mock.poll_footpedal_CallbackCalls = 0;
  Mock.foot_pedal_init_CallbackFunctionPointer = NULL;
  Mock.foot_pedal_init_CallbackCalls = 0;
  Mock.check_fs_stuck_CallbackFunctionPointer = NULL;
  Mock.check_fs_stuck_CallbackCalls = 0;
  Mock.fs_any_button_pressed_CallbackFunctionPointer = NULL;
  Mock.fs_any_button_pressed_CallbackCalls = 0;
}

uint8_t poll_footpedal(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_poll_footpedal_CALL_INSTANCE* cmock_call_instance = (CMOCK_poll_footpedal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.poll_footpedal_CallInstance);
  Mock.poll_footpedal_CallInstance = CMock_Guts_MemNext(Mock.poll_footpedal_CallInstance);
  if (Mock.poll_footpedal_CallbackFunctionPointer != NULL)
  {
    return Mock.poll_footpedal_CallbackFunctionPointer(Mock.poll_footpedal_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'poll_footpedal' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.poll_footpedal_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.poll_footpedal_FinalReturn;
    Mock.poll_footpedal_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void poll_footpedal_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_poll_footpedal_CALL_INSTANCE));
  CMOCK_poll_footpedal_CALL_INSTANCE* cmock_call_instance = (CMOCK_poll_footpedal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.poll_footpedal_CallInstance = CMock_Guts_MemChain(Mock.poll_footpedal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.poll_footpedal_IgnoreBool = (int)1;
}

void poll_footpedal_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_poll_footpedal_CALL_INSTANCE));
  CMOCK_poll_footpedal_CALL_INSTANCE* cmock_call_instance = (CMOCK_poll_footpedal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.poll_footpedal_CallInstance = CMock_Guts_MemChain(Mock.poll_footpedal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void poll_footpedal_StubWithCallback(CMOCK_poll_footpedal_CALLBACK Callback)
{
  Mock.poll_footpedal_CallbackFunctionPointer = Callback;
}

uint8_t foot_pedal_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_foot_pedal_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_foot_pedal_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.foot_pedal_init_CallInstance);
  Mock.foot_pedal_init_CallInstance = CMock_Guts_MemNext(Mock.foot_pedal_init_CallInstance);
  if (Mock.foot_pedal_init_CallbackFunctionPointer != NULL)
  {
    return Mock.foot_pedal_init_CallbackFunctionPointer(Mock.foot_pedal_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'foot_pedal_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.foot_pedal_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.foot_pedal_init_FinalReturn;
    Mock.foot_pedal_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void foot_pedal_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_foot_pedal_init_CALL_INSTANCE));
  CMOCK_foot_pedal_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_foot_pedal_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.foot_pedal_init_CallInstance = CMock_Guts_MemChain(Mock.foot_pedal_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.foot_pedal_init_IgnoreBool = (int)1;
}

void foot_pedal_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_foot_pedal_init_CALL_INSTANCE));
  CMOCK_foot_pedal_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_foot_pedal_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.foot_pedal_init_CallInstance = CMock_Guts_MemChain(Mock.foot_pedal_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void foot_pedal_init_StubWithCallback(CMOCK_foot_pedal_init_CALLBACK Callback)
{
  Mock.foot_pedal_init_CallbackFunctionPointer = Callback;
}

uint8_t check_fs_stuck(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_check_fs_stuck_CALL_INSTANCE* cmock_call_instance = (CMOCK_check_fs_stuck_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.check_fs_stuck_CallInstance);
  Mock.check_fs_stuck_CallInstance = CMock_Guts_MemNext(Mock.check_fs_stuck_CallInstance);
  if (Mock.check_fs_stuck_CallbackFunctionPointer != NULL)
  {
    return Mock.check_fs_stuck_CallbackFunctionPointer(Mock.check_fs_stuck_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'check_fs_stuck' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.check_fs_stuck_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.check_fs_stuck_FinalReturn;
    Mock.check_fs_stuck_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void check_fs_stuck_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_check_fs_stuck_CALL_INSTANCE));
  CMOCK_check_fs_stuck_CALL_INSTANCE* cmock_call_instance = (CMOCK_check_fs_stuck_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.check_fs_stuck_CallInstance = CMock_Guts_MemChain(Mock.check_fs_stuck_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.check_fs_stuck_IgnoreBool = (int)1;
}

void check_fs_stuck_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_check_fs_stuck_CALL_INSTANCE));
  CMOCK_check_fs_stuck_CALL_INSTANCE* cmock_call_instance = (CMOCK_check_fs_stuck_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.check_fs_stuck_CallInstance = CMock_Guts_MemChain(Mock.check_fs_stuck_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void check_fs_stuck_StubWithCallback(CMOCK_check_fs_stuck_CALLBACK Callback)
{
  Mock.check_fs_stuck_CallbackFunctionPointer = Callback;
}

bool fs_any_button_pressed(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fs_any_button_pressed_CALL_INSTANCE* cmock_call_instance = (CMOCK_fs_any_button_pressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fs_any_button_pressed_CallInstance);
  Mock.fs_any_button_pressed_CallInstance = CMock_Guts_MemNext(Mock.fs_any_button_pressed_CallInstance);
  if (Mock.fs_any_button_pressed_CallbackFunctionPointer != NULL)
  {
    return Mock.fs_any_button_pressed_CallbackFunctionPointer(Mock.fs_any_button_pressed_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'fs_any_button_pressed' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.fs_any_button_pressed_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.fs_any_button_pressed_FinalReturn;
    Mock.fs_any_button_pressed_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void fs_any_button_pressed_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fs_any_button_pressed_CALL_INSTANCE));
  CMOCK_fs_any_button_pressed_CALL_INSTANCE* cmock_call_instance = (CMOCK_fs_any_button_pressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.fs_any_button_pressed_CallInstance = CMock_Guts_MemChain(Mock.fs_any_button_pressed_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.fs_any_button_pressed_IgnoreBool = (int)1;
}

void fs_any_button_pressed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fs_any_button_pressed_CALL_INSTANCE));
  CMOCK_fs_any_button_pressed_CALL_INSTANCE* cmock_call_instance = (CMOCK_fs_any_button_pressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.fs_any_button_pressed_CallInstance = CMock_Guts_MemChain(Mock.fs_any_button_pressed_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void fs_any_button_pressed_StubWithCallback(CMOCK_fs_any_button_pressed_CALLBACK Callback)
{
  Mock.fs_any_button_pressed_CallbackFunctionPointer = Callback;
}

