/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKBUCK_H
#define _MOCKBUCK_H

#include "Types.h"
#include "buck.h"

void Mockbuck_Init(void);
void Mockbuck_Destroy(void);
void Mockbuck_Verify(void);




#define buck_init_IgnoreAndReturn(cmock_retval) buck_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void buck_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define buck_init_ExpectAndReturn(cmock_retval) buck_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void buck_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_buck_init_CALLBACK)(int cmock_num_calls);
void buck_init_StubWithCallback(CMOCK_buck_init_CALLBACK Callback);
#define set_buck_voltage_IgnoreAndReturn(cmock_retval) set_buck_voltage_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void set_buck_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define set_buck_voltage_ExpectAndReturn(cmock_arg1, cmock_arg2, cmock_retval) set_buck_voltage_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_arg2, cmock_retval)
void set_buck_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_arg1, uint16_t cmock_arg2, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_set_buck_voltage_CALLBACK)(uint16_t cmock_arg1, uint16_t cmock_arg2, int cmock_num_calls);
void set_buck_voltage_StubWithCallback(CMOCK_set_buck_voltage_CALLBACK Callback);
#define ramp_down_buck_voltage_IgnoreAndReturn(cmock_retval) ramp_down_buck_voltage_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ramp_down_buck_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define ramp_down_buck_voltage_ExpectAndReturn(cmock_arg1, cmock_arg2, cmock_retval) ramp_down_buck_voltage_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_arg2, cmock_retval)
void ramp_down_buck_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_ramp_down_buck_voltage_CALLBACK)(DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2, int cmock_num_calls);
void ramp_down_buck_voltage_StubWithCallback(CMOCK_ramp_down_buck_voltage_CALLBACK Callback);
#define buck_inactive_shutdown_IgnoreAndReturn(cmock_retval) buck_inactive_shutdown_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void buck_inactive_shutdown_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define buck_inactive_shutdown_ExpectAndReturn(cmock_retval) buck_inactive_shutdown_CMockExpectAndReturn(__LINE__, cmock_retval)
void buck_inactive_shutdown_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_buck_inactive_shutdown_CALLBACK)(int cmock_num_calls);
void buck_inactive_shutdown_StubWithCallback(CMOCK_buck_inactive_shutdown_CALLBACK Callback);
#define vmod2_test_IgnoreAndReturn(cmock_retval) vmod2_test_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void vmod2_test_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define vmod2_test_ExpectAndReturn(cmock_retval) vmod2_test_CMockExpectAndReturn(__LINE__, cmock_retval)
void vmod2_test_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_vmod2_test_CALLBACK)(int cmock_num_calls);
void vmod2_test_StubWithCallback(CMOCK_vmod2_test_CALLBACK Callback);
#define set_dac_IgnoreAndReturn(cmock_retval) set_dac_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void set_dac_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define set_dac_ExpectAndReturn(cmock_arg1, cmock_retval) set_dac_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void set_dac_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_arg1, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_set_dac_CALLBACK)(uint16_t cmock_arg1, int cmock_num_calls);
void set_dac_StubWithCallback(CMOCK_set_dac_CALLBACK Callback);
#define sort_vmeas_Ignore() sort_vmeas_CMockIgnore(__LINE__)
void sort_vmeas_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define sort_vmeas_Expect(cmock_arg1) sort_vmeas_CMockExpect(__LINE__, cmock_arg1)
void sort_vmeas_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t* cmock_arg1);
typedef void (* CMOCK_sort_vmeas_CALLBACK)(uint16_t* cmock_arg1, int cmock_num_calls);
void sort_vmeas_StubWithCallback(CMOCK_sort_vmeas_CALLBACK Callback);
#define interp2_IgnoreAndReturn(cmock_retval) interp2_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void interp2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define interp2_ExpectAndReturn(cmock_arg1, cmock_retval) interp2_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void interp2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_interp2_CALLBACK)(uint8_t cmock_arg1, int cmock_num_calls);
void interp2_StubWithCallback(CMOCK_interp2_CALLBACK Callback);
#define vmod2_ramp_test_IgnoreAndReturn(cmock_retval) vmod2_ramp_test_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void vmod2_ramp_test_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, VMOD_TEST_STATUS cmock_to_return);
#define vmod2_ramp_test_ExpectAndReturn(cmock_arg1, cmock_retval) vmod2_ramp_test_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void vmod2_ramp_test_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, VMOD_TEST_STATUS cmock_to_return);
typedef VMOD_TEST_STATUS (* CMOCK_vmod2_ramp_test_CALLBACK)(uint8_t cmock_arg1, int cmock_num_calls);
void vmod2_ramp_test_StubWithCallback(CMOCK_vmod2_ramp_test_CALLBACK Callback);
#define ramp_down_buck_test_voltage_IgnoreAndReturn(cmock_retval) ramp_down_buck_test_voltage_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ramp_down_buck_test_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define ramp_down_buck_test_voltage_ExpectAndReturn(cmock_arg1, cmock_arg2, cmock_arg3, cmock_retval) ramp_down_buck_test_voltage_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_arg2, cmock_arg3, cmock_retval)
void ramp_down_buck_test_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2, uint8_t cmock_arg3, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_ramp_down_buck_test_voltage_CALLBACK)(DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2, uint8_t cmock_arg3, int cmock_num_calls);
void ramp_down_buck_test_voltage_StubWithCallback(CMOCK_ramp_down_buck_test_voltage_CALLBACK Callback);
#define legacy_set_buck_voltage_IgnoreAndReturn(cmock_retval) legacy_set_buck_voltage_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void legacy_set_buck_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define legacy_set_buck_voltage_ExpectAndReturn(cmock_arg1, cmock_arg2, cmock_retval) legacy_set_buck_voltage_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_arg2, cmock_retval)
void legacy_set_buck_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_arg1, uint16_t cmock_arg2, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_legacy_set_buck_voltage_CALLBACK)(uint16_t cmock_arg1, uint16_t cmock_arg2, int cmock_num_calls);
void legacy_set_buck_voltage_StubWithCallback(CMOCK_legacy_set_buck_voltage_CALLBACK Callback);
#define legacy_ramp_down_buck_voltage_IgnoreAndReturn(cmock_retval) legacy_ramp_down_buck_voltage_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void legacy_ramp_down_buck_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define legacy_ramp_down_buck_voltage_ExpectAndReturn(cmock_arg1, cmock_retval) legacy_ramp_down_buck_voltage_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void legacy_ramp_down_buck_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_arg1, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_legacy_ramp_down_buck_voltage_CALLBACK)(uint16_t cmock_arg1, int cmock_num_calls);
void legacy_ramp_down_buck_voltage_StubWithCallback(CMOCK_legacy_ramp_down_buck_voltage_CALLBACK Callback);
#define vmod_interp_IgnoreAndReturn(cmock_retval) vmod_interp_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void vmod_interp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define vmod_interp_ExpectAndReturn(cmock_retval) vmod_interp_CMockExpectAndReturn(__LINE__, cmock_retval)
void vmod_interp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_vmod_interp_CALLBACK)(int cmock_num_calls);
void vmod_interp_StubWithCallback(CMOCK_vmod_interp_CALLBACK Callback);
#define vmod1_ramp_test_IgnoreAndReturn(cmock_retval) vmod1_ramp_test_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void vmod1_ramp_test_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, VMOD_TEST_STATUS cmock_to_return);
#define vmod1_ramp_test_ExpectAndReturn(cmock_arg1, cmock_retval) vmod1_ramp_test_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void vmod1_ramp_test_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, VMOD_TEST_STATUS cmock_to_return);
typedef VMOD_TEST_STATUS (* CMOCK_vmod1_ramp_test_CALLBACK)(uint8_t cmock_arg1, int cmock_num_calls);
void vmod1_ramp_test_StubWithCallback(CMOCK_vmod1_ramp_test_CALLBACK Callback);
#define vmod1_test_IgnoreAndReturn(cmock_retval) vmod1_test_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void vmod1_test_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define vmod1_test_ExpectAndReturn(cmock_retval) vmod1_test_CMockExpectAndReturn(__LINE__, cmock_retval)
void vmod1_test_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_vmod1_test_CALLBACK)(int cmock_num_calls);
void vmod1_test_StubWithCallback(CMOCK_vmod1_test_CALLBACK Callback);
#define set_buck_voltage_constant_power_IgnoreAndReturn(cmock_retval) set_buck_voltage_constant_power_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void set_buck_voltage_constant_power_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define set_buck_voltage_constant_power_ExpectAndReturn(irms, current_dac, power_target, vlimit, cmock_retval) set_buck_voltage_constant_power_CMockExpectAndReturn(__LINE__, irms, current_dac, power_target, vlimit, cmock_retval)
void set_buck_voltage_constant_power_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t irms, uint16_t current_dac, float32_t power_target, uint16_t vlimit, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_set_buck_voltage_constant_power_CALLBACK)(uint16_t irms, uint16_t current_dac, float32_t power_target, uint16_t vlimit, int cmock_num_calls);
void set_buck_voltage_constant_power_StubWithCallback(CMOCK_set_buck_voltage_constant_power_CALLBACK Callback);
#define vmod1_adc_coco_IgnoreAndReturn(cmock_retval) vmod1_adc_coco_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void vmod1_adc_coco_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return);
#define vmod1_adc_coco_ExpectAndReturn(cmock_retval) vmod1_adc_coco_CMockExpectAndReturn(__LINE__, cmock_retval)
void vmod1_adc_coco_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return);
typedef unsigned char (* CMOCK_vmod1_adc_coco_CALLBACK)(int cmock_num_calls);
void vmod1_adc_coco_StubWithCallback(CMOCK_vmod1_adc_coco_CALLBACK Callback);
#define vmod2_adc_coco_IgnoreAndReturn(cmock_retval) vmod2_adc_coco_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void vmod2_adc_coco_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return);
#define vmod2_adc_coco_ExpectAndReturn(cmock_retval) vmod2_adc_coco_CMockExpectAndReturn(__LINE__, cmock_retval)
void vmod2_adc_coco_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return);
typedef unsigned char (* CMOCK_vmod2_adc_coco_CALLBACK)(int cmock_num_calls);
void vmod2_adc_coco_StubWithCallback(CMOCK_vmod2_adc_coco_CALLBACK Callback);

#endif
