/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockcan.h"

typedef struct _CMOCK_flexCAN_readMB_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_flexCAN_readMB_CALL_INSTANCE;

typedef struct _CMOCK_read_flexcan_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_read_flexcan_CALL_INSTANCE;

typedef struct _CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE;

typedef struct _CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE;

typedef struct _CMOCK_flexcan_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_flexcan_init_CALL_INSTANCE;

typedef struct _CMOCK_can_wdog_rx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_can_wdog_rx_CALL_INSTANCE;

typedef struct _CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE;

static struct MockcanInstance
{
  int flexCAN_readMB_IgnoreBool;
  CMOCK_flexCAN_readMB_CALLBACK flexCAN_readMB_CallbackFunctionPointer;
  int flexCAN_readMB_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE flexCAN_readMB_CallInstance;
  int read_flexcan_IgnoreBool;
  uint8_t read_flexcan_FinalReturn;
  CMOCK_read_flexcan_CALLBACK read_flexcan_CallbackFunctionPointer;
  int read_flexcan_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE read_flexcan_CallInstance;
  int flexCAN_write_fast_msgs_IgnoreBool;
  uint8_t flexCAN_write_fast_msgs_FinalReturn;
  CMOCK_flexCAN_write_fast_msgs_CALLBACK flexCAN_write_fast_msgs_CallbackFunctionPointer;
  int flexCAN_write_fast_msgs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE flexCAN_write_fast_msgs_CallInstance;
  int FlexCAN_Write0x82Msg_IgnoreBool;
  CMOCK_FlexCAN_Write0x82Msg_CALLBACK FlexCAN_Write0x82Msg_CallbackFunctionPointer;
  int FlexCAN_Write0x82Msg_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlexCAN_Write0x82Msg_CallInstance;
  int flexcan_init_IgnoreBool;
  uint8_t flexcan_init_FinalReturn;
  CMOCK_flexcan_init_CALLBACK flexcan_init_CallbackFunctionPointer;
  int flexcan_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE flexcan_init_CallInstance;
  int can_wdog_rx_IgnoreBool;
  uint8_t can_wdog_rx_FinalReturn;
  CMOCK_can_wdog_rx_CALLBACK can_wdog_rx_CallbackFunctionPointer;
  int can_wdog_rx_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE can_wdog_rx_CallInstance;
  int flexCAN_write_slow_msgs_IgnoreBool;
  uint8_t flexCAN_write_slow_msgs_FinalReturn;
  CMOCK_flexCAN_write_slow_msgs_CALLBACK flexCAN_write_slow_msgs_CallbackFunctionPointer;
  int flexCAN_write_slow_msgs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE flexCAN_write_slow_msgs_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockcan_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.flexCAN_readMB_IgnoreBool)
    Mock.flexCAN_readMB_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.flexCAN_readMB_CallInstance, cmock_line, "Function 'flexCAN_readMB' called less times than expected.");
  if (Mock.flexCAN_readMB_CallbackFunctionPointer != NULL)
    Mock.flexCAN_readMB_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.read_flexcan_IgnoreBool)
    Mock.read_flexcan_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.read_flexcan_CallInstance, cmock_line, "Function 'read_flexcan' called less times than expected.");
  if (Mock.read_flexcan_CallbackFunctionPointer != NULL)
    Mock.read_flexcan_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.flexCAN_write_fast_msgs_IgnoreBool)
    Mock.flexCAN_write_fast_msgs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.flexCAN_write_fast_msgs_CallInstance, cmock_line, "Function 'flexCAN_write_fast_msgs' called less times than expected.");
  if (Mock.flexCAN_write_fast_msgs_CallbackFunctionPointer != NULL)
    Mock.flexCAN_write_fast_msgs_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.FlexCAN_Write0x82Msg_IgnoreBool)
    Mock.FlexCAN_Write0x82Msg_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.FlexCAN_Write0x82Msg_CallInstance, cmock_line, "Function 'FlexCAN_Write0x82Msg' called less times than expected.");
  if (Mock.FlexCAN_Write0x82Msg_CallbackFunctionPointer != NULL)
    Mock.FlexCAN_Write0x82Msg_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.flexcan_init_IgnoreBool)
    Mock.flexcan_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.flexcan_init_CallInstance, cmock_line, "Function 'flexcan_init' called less times than expected.");
  if (Mock.flexcan_init_CallbackFunctionPointer != NULL)
    Mock.flexcan_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.can_wdog_rx_IgnoreBool)
    Mock.can_wdog_rx_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.can_wdog_rx_CallInstance, cmock_line, "Function 'can_wdog_rx' called less times than expected.");
  if (Mock.can_wdog_rx_CallbackFunctionPointer != NULL)
    Mock.can_wdog_rx_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.flexCAN_write_slow_msgs_IgnoreBool)
    Mock.flexCAN_write_slow_msgs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.flexCAN_write_slow_msgs_CallInstance, cmock_line, "Function 'flexCAN_write_slow_msgs' called less times than expected.");
  if (Mock.flexCAN_write_slow_msgs_CallbackFunctionPointer != NULL)
    Mock.flexCAN_write_slow_msgs_CallInstance = CMOCK_GUTS_NONE;
}

void Mockcan_Init(void)
{
  Mockcan_Destroy();
}

void Mockcan_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.flexCAN_readMB_CallbackFunctionPointer = NULL;
  Mock.flexCAN_readMB_CallbackCalls = 0;
  Mock.read_flexcan_CallbackFunctionPointer = NULL;
  Mock.read_flexcan_CallbackCalls = 0;
  Mock.flexCAN_write_fast_msgs_CallbackFunctionPointer = NULL;
  Mock.flexCAN_write_fast_msgs_CallbackCalls = 0;
  Mock.FlexCAN_Write0x82Msg_CallbackFunctionPointer = NULL;
  Mock.FlexCAN_Write0x82Msg_CallbackCalls = 0;
  Mock.flexcan_init_CallbackFunctionPointer = NULL;
  Mock.flexcan_init_CallbackCalls = 0;
  Mock.can_wdog_rx_CallbackFunctionPointer = NULL;
  Mock.can_wdog_rx_CallbackCalls = 0;
  Mock.flexCAN_write_slow_msgs_CallbackFunctionPointer = NULL;
  Mock.flexCAN_write_slow_msgs_CallbackCalls = 0;
}

void flexCAN_readMB(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_flexCAN_readMB_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_readMB_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.flexCAN_readMB_CallInstance);
  Mock.flexCAN_readMB_CallInstance = CMock_Guts_MemNext(Mock.flexCAN_readMB_CallInstance);
  if (Mock.flexCAN_readMB_CallbackFunctionPointer != NULL)
  {
    Mock.flexCAN_readMB_CallbackFunctionPointer(Mock.flexCAN_readMB_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'flexCAN_readMB' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.flexCAN_readMB_IgnoreBool)
  {
    return;
  }
}

void flexCAN_readMB_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_readMB_CALL_INSTANCE));
  CMOCK_flexCAN_readMB_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_readMB_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_readMB_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_readMB_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.flexCAN_readMB_IgnoreBool = (int)1;
}

void flexCAN_readMB_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_readMB_CALL_INSTANCE));
  CMOCK_flexCAN_readMB_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_readMB_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_readMB_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_readMB_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void flexCAN_readMB_StubWithCallback(CMOCK_flexCAN_readMB_CALLBACK Callback)
{
  Mock.flexCAN_readMB_CallbackFunctionPointer = Callback;
}

uint8_t read_flexcan(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_read_flexcan_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_flexcan_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.read_flexcan_CallInstance);
  Mock.read_flexcan_CallInstance = CMock_Guts_MemNext(Mock.read_flexcan_CallInstance);
  if (Mock.read_flexcan_CallbackFunctionPointer != NULL)
  {
    return Mock.read_flexcan_CallbackFunctionPointer(Mock.read_flexcan_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'read_flexcan' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.read_flexcan_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.read_flexcan_FinalReturn;
    Mock.read_flexcan_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void read_flexcan_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_flexcan_CALL_INSTANCE));
  CMOCK_read_flexcan_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_flexcan_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.read_flexcan_CallInstance = CMock_Guts_MemChain(Mock.read_flexcan_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.read_flexcan_IgnoreBool = (int)1;
}

void read_flexcan_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_flexcan_CALL_INSTANCE));
  CMOCK_read_flexcan_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_flexcan_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.read_flexcan_CallInstance = CMock_Guts_MemChain(Mock.read_flexcan_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void read_flexcan_StubWithCallback(CMOCK_read_flexcan_CALLBACK Callback)
{
  Mock.read_flexcan_CallbackFunctionPointer = Callback;
}

uint8_t flexCAN_write_fast_msgs(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.flexCAN_write_fast_msgs_CallInstance);
  Mock.flexCAN_write_fast_msgs_CallInstance = CMock_Guts_MemNext(Mock.flexCAN_write_fast_msgs_CallInstance);
  if (Mock.flexCAN_write_fast_msgs_CallbackFunctionPointer != NULL)
  {
    return Mock.flexCAN_write_fast_msgs_CallbackFunctionPointer(Mock.flexCAN_write_fast_msgs_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'flexCAN_write_fast_msgs' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.flexCAN_write_fast_msgs_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.flexCAN_write_fast_msgs_FinalReturn;
    Mock.flexCAN_write_fast_msgs_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void flexCAN_write_fast_msgs_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE));
  CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_fast_msgs_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_fast_msgs_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.flexCAN_write_fast_msgs_IgnoreBool = (int)1;
}

void flexCAN_write_fast_msgs_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE));
  CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_fast_msgs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_fast_msgs_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_fast_msgs_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void flexCAN_write_fast_msgs_StubWithCallback(CMOCK_flexCAN_write_fast_msgs_CALLBACK Callback)
{
  Mock.flexCAN_write_fast_msgs_CallbackFunctionPointer = Callback;
}

void FlexCAN_Write0x82Msg(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlexCAN_Write0x82Msg_CallInstance);
  Mock.FlexCAN_Write0x82Msg_CallInstance = CMock_Guts_MemNext(Mock.FlexCAN_Write0x82Msg_CallInstance);
  if (Mock.FlexCAN_Write0x82Msg_CallbackFunctionPointer != NULL)
  {
    Mock.FlexCAN_Write0x82Msg_CallbackFunctionPointer(Mock.FlexCAN_Write0x82Msg_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'FlexCAN_Write0x82Msg' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.FlexCAN_Write0x82Msg_IgnoreBool)
  {
    return;
  }
}

void FlexCAN_Write0x82Msg_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE));
  CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.FlexCAN_Write0x82Msg_CallInstance = CMock_Guts_MemChain(Mock.FlexCAN_Write0x82Msg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.FlexCAN_Write0x82Msg_IgnoreBool = (int)1;
}

void FlexCAN_Write0x82Msg_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE));
  CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlexCAN_Write0x82Msg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.FlexCAN_Write0x82Msg_CallInstance = CMock_Guts_MemChain(Mock.FlexCAN_Write0x82Msg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void FlexCAN_Write0x82Msg_StubWithCallback(CMOCK_FlexCAN_Write0x82Msg_CALLBACK Callback)
{
  Mock.FlexCAN_Write0x82Msg_CallbackFunctionPointer = Callback;
}

uint8_t flexcan_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_flexcan_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexcan_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.flexcan_init_CallInstance);
  Mock.flexcan_init_CallInstance = CMock_Guts_MemNext(Mock.flexcan_init_CallInstance);
  if (Mock.flexcan_init_CallbackFunctionPointer != NULL)
  {
    return Mock.flexcan_init_CallbackFunctionPointer(Mock.flexcan_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'flexcan_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.flexcan_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.flexcan_init_FinalReturn;
    Mock.flexcan_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void flexcan_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexcan_init_CALL_INSTANCE));
  CMOCK_flexcan_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexcan_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexcan_init_CallInstance = CMock_Guts_MemChain(Mock.flexcan_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.flexcan_init_IgnoreBool = (int)1;
}

void flexcan_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexcan_init_CALL_INSTANCE));
  CMOCK_flexcan_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexcan_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexcan_init_CallInstance = CMock_Guts_MemChain(Mock.flexcan_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void flexcan_init_StubWithCallback(CMOCK_flexcan_init_CALLBACK Callback)
{
  Mock.flexcan_init_CallbackFunctionPointer = Callback;
}

uint8_t can_wdog_rx(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_can_wdog_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_wdog_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.can_wdog_rx_CallInstance);
  Mock.can_wdog_rx_CallInstance = CMock_Guts_MemNext(Mock.can_wdog_rx_CallInstance);
  if (Mock.can_wdog_rx_CallbackFunctionPointer != NULL)
  {
    return Mock.can_wdog_rx_CallbackFunctionPointer(Mock.can_wdog_rx_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'can_wdog_rx' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.can_wdog_rx_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.can_wdog_rx_FinalReturn;
    Mock.can_wdog_rx_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void can_wdog_rx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_wdog_rx_CALL_INSTANCE));
  CMOCK_can_wdog_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_wdog_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.can_wdog_rx_CallInstance = CMock_Guts_MemChain(Mock.can_wdog_rx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.can_wdog_rx_IgnoreBool = (int)1;
}

void can_wdog_rx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_wdog_rx_CALL_INSTANCE));
  CMOCK_can_wdog_rx_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_wdog_rx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.can_wdog_rx_CallInstance = CMock_Guts_MemChain(Mock.can_wdog_rx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void can_wdog_rx_StubWithCallback(CMOCK_can_wdog_rx_CALLBACK Callback)
{
  Mock.can_wdog_rx_CallbackFunctionPointer = Callback;
}

uint8_t flexCAN_write_slow_msgs(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.flexCAN_write_slow_msgs_CallInstance);
  Mock.flexCAN_write_slow_msgs_CallInstance = CMock_Guts_MemNext(Mock.flexCAN_write_slow_msgs_CallInstance);
  if (Mock.flexCAN_write_slow_msgs_CallbackFunctionPointer != NULL)
  {
    return Mock.flexCAN_write_slow_msgs_CallbackFunctionPointer(Mock.flexCAN_write_slow_msgs_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'flexCAN_write_slow_msgs' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.flexCAN_write_slow_msgs_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.flexCAN_write_slow_msgs_FinalReturn;
    Mock.flexCAN_write_slow_msgs_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void flexCAN_write_slow_msgs_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE));
  CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_slow_msgs_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_slow_msgs_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.flexCAN_write_slow_msgs_IgnoreBool = (int)1;
}

void flexCAN_write_slow_msgs_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE));
  CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_slow_msgs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_slow_msgs_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_slow_msgs_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void flexCAN_write_slow_msgs_StubWithCallback(CMOCK_flexCAN_write_slow_msgs_CALLBACK Callback)
{
  Mock.flexCAN_write_slow_msgs_CallbackFunctionPointer = Callback;
}

