/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockcpu.h"

typedef struct _CMOCK_Write_Vtor_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int Expected_cmock_arg1;

} CMOCK_Write_Vtor_CALL_INSTANCE;

typedef struct _CMOCK_enable_irq_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_cmock_arg1;

} CMOCK_enable_irq_CALL_INSTANCE;

typedef struct _CMOCK_disable_irq_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_cmock_arg1;

} CMOCK_disable_irq_CALL_INSTANCE;

typedef struct _CMOCK_system_reset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_system_reset_CALL_INSTANCE;

static struct MockcpuInstance
{
  int Write_Vtor_IgnoreBool;
  CMOCK_Write_Vtor_CALLBACK Write_Vtor_CallbackFunctionPointer;
  int Write_Vtor_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Write_Vtor_CallInstance;
  int enable_irq_IgnoreBool;
  CMOCK_enable_irq_CALLBACK enable_irq_CallbackFunctionPointer;
  int enable_irq_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE enable_irq_CallInstance;
  int disable_irq_IgnoreBool;
  CMOCK_disable_irq_CALLBACK disable_irq_CallbackFunctionPointer;
  int disable_irq_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE disable_irq_CallInstance;
  int system_reset_IgnoreBool;
  uint8_t system_reset_FinalReturn;
  CMOCK_system_reset_CALLBACK system_reset_CallbackFunctionPointer;
  int system_reset_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE system_reset_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockcpu_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.Write_Vtor_IgnoreBool)
    Mock.Write_Vtor_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Write_Vtor_CallInstance, cmock_line, "Function 'Write_Vtor' called less times than expected.");
  if (Mock.Write_Vtor_CallbackFunctionPointer != NULL)
    Mock.Write_Vtor_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.enable_irq_IgnoreBool)
    Mock.enable_irq_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.enable_irq_CallInstance, cmock_line, "Function 'enable_irq' called less times than expected.");
  if (Mock.enable_irq_CallbackFunctionPointer != NULL)
    Mock.enable_irq_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.disable_irq_IgnoreBool)
    Mock.disable_irq_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.disable_irq_CallInstance, cmock_line, "Function 'disable_irq' called less times than expected.");
  if (Mock.disable_irq_CallbackFunctionPointer != NULL)
    Mock.disable_irq_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.system_reset_IgnoreBool)
    Mock.system_reset_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.system_reset_CallInstance, cmock_line, "Function 'system_reset' called less times than expected.");
  if (Mock.system_reset_CallbackFunctionPointer != NULL)
    Mock.system_reset_CallInstance = CMOCK_GUTS_NONE;
}

void Mockcpu_Init(void)
{
  Mockcpu_Destroy();
}

void Mockcpu_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.Write_Vtor_CallbackFunctionPointer = NULL;
  Mock.Write_Vtor_CallbackCalls = 0;
  Mock.enable_irq_CallbackFunctionPointer = NULL;
  Mock.enable_irq_CallbackCalls = 0;
  Mock.disable_irq_CallbackFunctionPointer = NULL;
  Mock.disable_irq_CallbackCalls = 0;
  Mock.system_reset_CallbackFunctionPointer = NULL;
  Mock.system_reset_CallbackCalls = 0;
}

void Write_Vtor(int cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Write_Vtor_CALL_INSTANCE* cmock_call_instance = (CMOCK_Write_Vtor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Write_Vtor_CallInstance);
  Mock.Write_Vtor_CallInstance = CMock_Guts_MemNext(Mock.Write_Vtor_CallInstance);
  if (Mock.Write_Vtor_CallbackFunctionPointer != NULL)
  {
    Mock.Write_Vtor_CallbackFunctionPointer(cmock_arg1, Mock.Write_Vtor_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Write_Vtor' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.Write_Vtor_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'Write_Vtor' called with unexpected value for argument 'cmock_arg1'.");
}

void CMockExpectParameters_Write_Vtor(CMOCK_Write_Vtor_CALL_INSTANCE* cmock_call_instance, int cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void Write_Vtor_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Write_Vtor_CALL_INSTANCE));
  CMOCK_Write_Vtor_CALL_INSTANCE* cmock_call_instance = (CMOCK_Write_Vtor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Write_Vtor_CallInstance = CMock_Guts_MemChain(Mock.Write_Vtor_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.Write_Vtor_IgnoreBool = (int)1;
}

void Write_Vtor_CMockExpect(UNITY_LINE_TYPE cmock_line, int cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Write_Vtor_CALL_INSTANCE));
  CMOCK_Write_Vtor_CALL_INSTANCE* cmock_call_instance = (CMOCK_Write_Vtor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Write_Vtor_CallInstance = CMock_Guts_MemChain(Mock.Write_Vtor_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Write_Vtor(cmock_call_instance, cmock_arg1);
}

void Write_Vtor_StubWithCallback(CMOCK_Write_Vtor_CALLBACK Callback)
{
  Mock.Write_Vtor_CallbackFunctionPointer = Callback;
}

void enable_irq(uint8_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_enable_irq_CALL_INSTANCE* cmock_call_instance = (CMOCK_enable_irq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.enable_irq_CallInstance);
  Mock.enable_irq_CallInstance = CMock_Guts_MemNext(Mock.enable_irq_CallInstance);
  if (Mock.enable_irq_CallbackFunctionPointer != NULL)
  {
    Mock.enable_irq_CallbackFunctionPointer(cmock_arg1, Mock.enable_irq_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'enable_irq' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.enable_irq_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'enable_irq' called with unexpected value for argument 'cmock_arg1'.");
}

void CMockExpectParameters_enable_irq(CMOCK_enable_irq_CALL_INSTANCE* cmock_call_instance, uint8_t cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void enable_irq_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_enable_irq_CALL_INSTANCE));
  CMOCK_enable_irq_CALL_INSTANCE* cmock_call_instance = (CMOCK_enable_irq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.enable_irq_CallInstance = CMock_Guts_MemChain(Mock.enable_irq_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.enable_irq_IgnoreBool = (int)1;
}

void enable_irq_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_enable_irq_CALL_INSTANCE));
  CMOCK_enable_irq_CALL_INSTANCE* cmock_call_instance = (CMOCK_enable_irq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.enable_irq_CallInstance = CMock_Guts_MemChain(Mock.enable_irq_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_enable_irq(cmock_call_instance, cmock_arg1);
}

void enable_irq_StubWithCallback(CMOCK_enable_irq_CALLBACK Callback)
{
  Mock.enable_irq_CallbackFunctionPointer = Callback;
}

void disable_irq(uint8_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_disable_irq_CALL_INSTANCE* cmock_call_instance = (CMOCK_disable_irq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.disable_irq_CallInstance);
  Mock.disable_irq_CallInstance = CMock_Guts_MemNext(Mock.disable_irq_CallInstance);
  if (Mock.disable_irq_CallbackFunctionPointer != NULL)
  {
    Mock.disable_irq_CallbackFunctionPointer(cmock_arg1, Mock.disable_irq_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'disable_irq' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.disable_irq_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'disable_irq' called with unexpected value for argument 'cmock_arg1'.");
}

void CMockExpectParameters_disable_irq(CMOCK_disable_irq_CALL_INSTANCE* cmock_call_instance, uint8_t cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void disable_irq_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_disable_irq_CALL_INSTANCE));
  CMOCK_disable_irq_CALL_INSTANCE* cmock_call_instance = (CMOCK_disable_irq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.disable_irq_CallInstance = CMock_Guts_MemChain(Mock.disable_irq_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.disable_irq_IgnoreBool = (int)1;
}

void disable_irq_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_disable_irq_CALL_INSTANCE));
  CMOCK_disable_irq_CALL_INSTANCE* cmock_call_instance = (CMOCK_disable_irq_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.disable_irq_CallInstance = CMock_Guts_MemChain(Mock.disable_irq_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_disable_irq(cmock_call_instance, cmock_arg1);
}

void disable_irq_StubWithCallback(CMOCK_disable_irq_CALLBACK Callback)
{
  Mock.disable_irq_CallbackFunctionPointer = Callback;
}

uint8_t system_reset(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_system_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_system_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.system_reset_CallInstance);
  Mock.system_reset_CallInstance = CMock_Guts_MemNext(Mock.system_reset_CallInstance);
  if (Mock.system_reset_CallbackFunctionPointer != NULL)
  {
    return Mock.system_reset_CallbackFunctionPointer(Mock.system_reset_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'system_reset' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.system_reset_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.system_reset_FinalReturn;
    Mock.system_reset_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void system_reset_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_system_reset_CALL_INSTANCE));
  CMOCK_system_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_system_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.system_reset_CallInstance = CMock_Guts_MemChain(Mock.system_reset_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.system_reset_IgnoreBool = (int)1;
}

void system_reset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_system_reset_CALL_INSTANCE));
  CMOCK_system_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_system_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.system_reset_CallInstance = CMock_Guts_MemChain(Mock.system_reset_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void system_reset_StubWithCallback(CMOCK_system_reset_CALLBACK Callback)
{
  Mock.system_reset_CallbackFunctionPointer = Callback;
}

