/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKRCM_H
#define _MOCKRCM_H

#include "Types.h"
#include "rcm.h"

void Mockrcm_Init(void);
void Mockrcm_Destroy(void);
void Mockrcm_Verify(void);




#define reset_monitor_IgnoreAndReturn(cmock_retval) reset_monitor_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void reset_monitor_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define reset_monitor_ExpectAndReturn(cmock_retval) reset_monitor_CMockExpectAndReturn(__LINE__, cmock_retval)
void reset_monitor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_reset_monitor_CALLBACK)(int cmock_num_calls);
void reset_monitor_StubWithCallback(CMOCK_reset_monitor_CALLBACK Callback);
#define software_reset_Ignore() software_reset_CMockIgnore(__LINE__)
void software_reset_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define software_reset_Expect() software_reset_CMockExpect(__LINE__)
void software_reset_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_software_reset_CALLBACK)(int cmock_num_calls);
void software_reset_StubWithCallback(CMOCK_software_reset_CALLBACK Callback);

#endif
