/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockpost.h"

typedef struct _CMOCK_post_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_post_CALL_INSTANCE;

typedef struct _CMOCK_post_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_post_init_CALL_INSTANCE;

typedef struct _CMOCK_post_exit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_post_exit_CALL_INSTANCE;

typedef struct _CMOCK_get_mfg_date_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_get_mfg_date_CALL_INSTANCE;

typedef struct _CMOCK_get_serial_num_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_get_serial_num_CALL_INSTANCE;

typedef struct _CMOCK_sn_acii2bcd_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t* Expected_cmock_arg1;
  uint8_t* Expected_cmock_arg2;

} CMOCK_sn_acii2bcd_CALL_INSTANCE;

static struct MockpostInstance
{
  int post_IgnoreBool;
  uint8_t post_FinalReturn;
  CMOCK_post_CALLBACK post_CallbackFunctionPointer;
  int post_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE post_CallInstance;
  int post_init_IgnoreBool;
  uint8_t post_init_FinalReturn;
  CMOCK_post_init_CALLBACK post_init_CallbackFunctionPointer;
  int post_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE post_init_CallInstance;
  int post_exit_IgnoreBool;
  uint8_t post_exit_FinalReturn;
  CMOCK_post_exit_CALLBACK post_exit_CallbackFunctionPointer;
  int post_exit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE post_exit_CallInstance;
  int get_mfg_date_IgnoreBool;
  uint8_t get_mfg_date_FinalReturn;
  CMOCK_get_mfg_date_CALLBACK get_mfg_date_CallbackFunctionPointer;
  int get_mfg_date_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_mfg_date_CallInstance;
  int get_serial_num_IgnoreBool;
  uint8_t get_serial_num_FinalReturn;
  CMOCK_get_serial_num_CALLBACK get_serial_num_CallbackFunctionPointer;
  int get_serial_num_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_serial_num_CallInstance;
  int sn_acii2bcd_IgnoreBool;
  CMOCK_sn_acii2bcd_CALLBACK sn_acii2bcd_CallbackFunctionPointer;
  int sn_acii2bcd_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sn_acii2bcd_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockpost_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.post_IgnoreBool)
    Mock.post_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.post_CallInstance, cmock_line, "Function 'post' called less times than expected.");
  if (Mock.post_CallbackFunctionPointer != NULL)
    Mock.post_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.post_init_IgnoreBool)
    Mock.post_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.post_init_CallInstance, cmock_line, "Function 'post_init' called less times than expected.");
  if (Mock.post_init_CallbackFunctionPointer != NULL)
    Mock.post_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.post_exit_IgnoreBool)
    Mock.post_exit_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.post_exit_CallInstance, cmock_line, "Function 'post_exit' called less times than expected.");
  if (Mock.post_exit_CallbackFunctionPointer != NULL)
    Mock.post_exit_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.get_mfg_date_IgnoreBool)
    Mock.get_mfg_date_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.get_mfg_date_CallInstance, cmock_line, "Function 'get_mfg_date' called less times than expected.");
  if (Mock.get_mfg_date_CallbackFunctionPointer != NULL)
    Mock.get_mfg_date_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.get_serial_num_IgnoreBool)
    Mock.get_serial_num_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.get_serial_num_CallInstance, cmock_line, "Function 'get_serial_num' called less times than expected.");
  if (Mock.get_serial_num_CallbackFunctionPointer != NULL)
    Mock.get_serial_num_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sn_acii2bcd_IgnoreBool)
    Mock.sn_acii2bcd_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sn_acii2bcd_CallInstance, cmock_line, "Function 'sn_acii2bcd' called less times than expected.");
  if (Mock.sn_acii2bcd_CallbackFunctionPointer != NULL)
    Mock.sn_acii2bcd_CallInstance = CMOCK_GUTS_NONE;
}

void Mockpost_Init(void)
{
  Mockpost_Destroy();
}

void Mockpost_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.post_CallbackFunctionPointer = NULL;
  Mock.post_CallbackCalls = 0;
  Mock.post_init_CallbackFunctionPointer = NULL;
  Mock.post_init_CallbackCalls = 0;
  Mock.post_exit_CallbackFunctionPointer = NULL;
  Mock.post_exit_CallbackCalls = 0;
  Mock.get_mfg_date_CallbackFunctionPointer = NULL;
  Mock.get_mfg_date_CallbackCalls = 0;
  Mock.get_serial_num_CallbackFunctionPointer = NULL;
  Mock.get_serial_num_CallbackCalls = 0;
  Mock.sn_acii2bcd_CallbackFunctionPointer = NULL;
  Mock.sn_acii2bcd_CallbackCalls = 0;
}

uint8_t post(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_post_CALL_INSTANCE* cmock_call_instance = (CMOCK_post_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.post_CallInstance);
  Mock.post_CallInstance = CMock_Guts_MemNext(Mock.post_CallInstance);
  if (Mock.post_CallbackFunctionPointer != NULL)
  {
    return Mock.post_CallbackFunctionPointer(Mock.post_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'post' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.post_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.post_FinalReturn;
    Mock.post_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void post_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_post_CALL_INSTANCE));
  CMOCK_post_CALL_INSTANCE* cmock_call_instance = (CMOCK_post_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.post_CallInstance = CMock_Guts_MemChain(Mock.post_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.post_IgnoreBool = (int)1;
}

void post_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_post_CALL_INSTANCE));
  CMOCK_post_CALL_INSTANCE* cmock_call_instance = (CMOCK_post_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.post_CallInstance = CMock_Guts_MemChain(Mock.post_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void post_StubWithCallback(CMOCK_post_CALLBACK Callback)
{
  Mock.post_CallbackFunctionPointer = Callback;
}

uint8_t post_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_post_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_post_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.post_init_CallInstance);
  Mock.post_init_CallInstance = CMock_Guts_MemNext(Mock.post_init_CallInstance);
  if (Mock.post_init_CallbackFunctionPointer != NULL)
  {
    return Mock.post_init_CallbackFunctionPointer(Mock.post_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'post_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.post_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.post_init_FinalReturn;
    Mock.post_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void post_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_post_init_CALL_INSTANCE));
  CMOCK_post_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_post_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.post_init_CallInstance = CMock_Guts_MemChain(Mock.post_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.post_init_IgnoreBool = (int)1;
}

void post_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_post_init_CALL_INSTANCE));
  CMOCK_post_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_post_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.post_init_CallInstance = CMock_Guts_MemChain(Mock.post_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void post_init_StubWithCallback(CMOCK_post_init_CALLBACK Callback)
{
  Mock.post_init_CallbackFunctionPointer = Callback;
}

uint8_t post_exit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_post_exit_CALL_INSTANCE* cmock_call_instance = (CMOCK_post_exit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.post_exit_CallInstance);
  Mock.post_exit_CallInstance = CMock_Guts_MemNext(Mock.post_exit_CallInstance);
  if (Mock.post_exit_CallbackFunctionPointer != NULL)
  {
    return Mock.post_exit_CallbackFunctionPointer(Mock.post_exit_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'post_exit' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.post_exit_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.post_exit_FinalReturn;
    Mock.post_exit_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void post_exit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_post_exit_CALL_INSTANCE));
  CMOCK_post_exit_CALL_INSTANCE* cmock_call_instance = (CMOCK_post_exit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.post_exit_CallInstance = CMock_Guts_MemChain(Mock.post_exit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.post_exit_IgnoreBool = (int)1;
}

void post_exit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_post_exit_CALL_INSTANCE));
  CMOCK_post_exit_CALL_INSTANCE* cmock_call_instance = (CMOCK_post_exit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.post_exit_CallInstance = CMock_Guts_MemChain(Mock.post_exit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void post_exit_StubWithCallback(CMOCK_post_exit_CALLBACK Callback)
{
  Mock.post_exit_CallbackFunctionPointer = Callback;
}

uint8_t get_mfg_date(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_mfg_date_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_mfg_date_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_mfg_date_CallInstance);
  Mock.get_mfg_date_CallInstance = CMock_Guts_MemNext(Mock.get_mfg_date_CallInstance);
  if (Mock.get_mfg_date_CallbackFunctionPointer != NULL)
  {
    return Mock.get_mfg_date_CallbackFunctionPointer(Mock.get_mfg_date_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'get_mfg_date' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.get_mfg_date_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.get_mfg_date_FinalReturn;
    Mock.get_mfg_date_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void get_mfg_date_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_mfg_date_CALL_INSTANCE));
  CMOCK_get_mfg_date_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_mfg_date_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.get_mfg_date_CallInstance = CMock_Guts_MemChain(Mock.get_mfg_date_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_mfg_date_IgnoreBool = (int)1;
}

void get_mfg_date_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_mfg_date_CALL_INSTANCE));
  CMOCK_get_mfg_date_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_mfg_date_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.get_mfg_date_CallInstance = CMock_Guts_MemChain(Mock.get_mfg_date_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_mfg_date_StubWithCallback(CMOCK_get_mfg_date_CALLBACK Callback)
{
  Mock.get_mfg_date_CallbackFunctionPointer = Callback;
}

uint8_t get_serial_num(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_serial_num_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_serial_num_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_serial_num_CallInstance);
  Mock.get_serial_num_CallInstance = CMock_Guts_MemNext(Mock.get_serial_num_CallInstance);
  if (Mock.get_serial_num_CallbackFunctionPointer != NULL)
  {
    return Mock.get_serial_num_CallbackFunctionPointer(Mock.get_serial_num_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'get_serial_num' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.get_serial_num_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.get_serial_num_FinalReturn;
    Mock.get_serial_num_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void get_serial_num_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_serial_num_CALL_INSTANCE));
  CMOCK_get_serial_num_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_serial_num_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.get_serial_num_CallInstance = CMock_Guts_MemChain(Mock.get_serial_num_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_serial_num_IgnoreBool = (int)1;
}

void get_serial_num_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_serial_num_CALL_INSTANCE));
  CMOCK_get_serial_num_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_serial_num_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.get_serial_num_CallInstance = CMock_Guts_MemChain(Mock.get_serial_num_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_serial_num_StubWithCallback(CMOCK_get_serial_num_CALLBACK Callback)
{
  Mock.get_serial_num_CallbackFunctionPointer = Callback;
}

void sn_acii2bcd(uint8_t* cmock_arg1, uint8_t* cmock_arg2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sn_acii2bcd_CALL_INSTANCE* cmock_call_instance = (CMOCK_sn_acii2bcd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sn_acii2bcd_CallInstance);
  Mock.sn_acii2bcd_CallInstance = CMock_Guts_MemNext(Mock.sn_acii2bcd_CallInstance);
  if (Mock.sn_acii2bcd_CallbackFunctionPointer != NULL)
  {
    Mock.sn_acii2bcd_CallbackFunctionPointer(cmock_arg1, cmock_arg2, Mock.sn_acii2bcd_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sn_acii2bcd' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.sn_acii2bcd_IgnoreBool)
  {
    return;
  }
  if (cmock_call_instance->Expected_cmock_arg1 == NULL)
    { UNITY_TEST_ASSERT_NULL(cmock_arg1, cmock_line, "Expected NULL. Function 'sn_acii2bcd' called with unexpected value for argument 'cmock_arg1'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, 1, cmock_line, "Function 'sn_acii2bcd' called with unexpected value for argument 'cmock_arg1'."); }
  if (cmock_call_instance->Expected_cmock_arg2 == NULL)
    { UNITY_TEST_ASSERT_NULL(cmock_arg2, cmock_line, "Expected NULL. Function 'sn_acii2bcd' called with unexpected value for argument 'cmock_arg2'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, 1, cmock_line, "Function 'sn_acii2bcd' called with unexpected value for argument 'cmock_arg2'."); }
}

void CMockExpectParameters_sn_acii2bcd(CMOCK_sn_acii2bcd_CALL_INSTANCE* cmock_call_instance, uint8_t* cmock_arg1, uint8_t* cmock_arg2)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
}

void sn_acii2bcd_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sn_acii2bcd_CALL_INSTANCE));
  CMOCK_sn_acii2bcd_CALL_INSTANCE* cmock_call_instance = (CMOCK_sn_acii2bcd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sn_acii2bcd_CallInstance = CMock_Guts_MemChain(Mock.sn_acii2bcd_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.sn_acii2bcd_IgnoreBool = (int)1;
}

void sn_acii2bcd_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* cmock_arg1, uint8_t* cmock_arg2)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sn_acii2bcd_CALL_INSTANCE));
  CMOCK_sn_acii2bcd_CALL_INSTANCE* cmock_call_instance = (CMOCK_sn_acii2bcd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sn_acii2bcd_CallInstance = CMock_Guts_MemChain(Mock.sn_acii2bcd_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sn_acii2bcd(cmock_call_instance, cmock_arg1, cmock_arg2);
}

void sn_acii2bcd_StubWithCallback(CMOCK_sn_acii2bcd_CALLBACK Callback)
{
  Mock.sn_acii2bcd_CallbackFunctionPointer = Callback;
}

