/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTATE_MACHINE_H
#define _MOCKSTATE_MACHINE_H

#include "Types.h"
#include "state_machine.h"

void Mockstate_machine_Init(void);
void Mockstate_machine_Destroy(void);
void Mockstate_machine_Verify(void);




#define do_nothing_IgnoreAndReturn(cmock_retval) do_nothing_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void do_nothing_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define do_nothing_ExpectAndReturn(cmock_retval) do_nothing_CMockExpectAndReturn(__LINE__, cmock_retval)
void do_nothing_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_do_nothing_CALLBACK)(int cmock_num_calls);
void do_nothing_StubWithCallback(CMOCK_do_nothing_CALLBACK Callback);
#define init_shutdown_IgnoreAndReturn(cmock_retval) init_shutdown_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void init_shutdown_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define init_shutdown_ExpectAndReturn(cmock_retval) init_shutdown_CMockExpectAndReturn(__LINE__, cmock_retval)
void init_shutdown_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_init_shutdown_CALLBACK)(int cmock_num_calls);
void init_shutdown_StubWithCallback(CMOCK_init_shutdown_CALLBACK Callback);
#define state_switch_IgnoreAndReturn(cmock_retval) state_switch_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void state_switch_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define state_switch_ExpectAndReturn(cmock_retval) state_switch_CMockExpectAndReturn(__LINE__, cmock_retval)
void state_switch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_state_switch_CALLBACK)(int cmock_num_calls);
void state_switch_StubWithCallback(CMOCK_state_switch_CALLBACK Callback);

#endif
