/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockcan_debug.h"

typedef struct _CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE;

typedef struct _CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE;

typedef struct _CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE;

typedef struct _CMOCK_flexCAN_write_wireless_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_flexCAN_write_wireless_CALL_INSTANCE;

typedef struct _CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE;

static struct Mockcan_debugInstance
{
  int flexCAN_write_pumpdebug_IgnoreBool;
  uint8_t flexCAN_write_pumpdebug_FinalReturn;
  CMOCK_flexCAN_write_pumpdebug_CALLBACK flexCAN_write_pumpdebug_CallbackFunctionPointer;
  int flexCAN_write_pumpdebug_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE flexCAN_write_pumpdebug_CallInstance;
  int FlexCAN_Write_PWMDebug_IgnoreBool;
  CMOCK_FlexCAN_Write_PWMDebug_CALLBACK FlexCAN_Write_PWMDebug_CallbackFunctionPointer;
  int FlexCAN_Write_PWMDebug_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlexCAN_Write_PWMDebug_CallInstance;
  int flexCAN_write_wanddebug_IgnoreBool;
  uint8_t flexCAN_write_wanddebug_FinalReturn;
  CMOCK_flexCAN_write_wanddebug_CALLBACK flexCAN_write_wanddebug_CallbackFunctionPointer;
  int flexCAN_write_wanddebug_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE flexCAN_write_wanddebug_CallInstance;
  int flexCAN_write_wireless_IgnoreBool;
  uint8_t flexCAN_write_wireless_FinalReturn;
  CMOCK_flexCAN_write_wireless_CALLBACK flexCAN_write_wireless_CallbackFunctionPointer;
  int flexCAN_write_wireless_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE flexCAN_write_wireless_CallInstance;
  int flexCAN_write_wand_wear_debug_IgnoreBool;
  uint8_t flexCAN_write_wand_wear_debug_FinalReturn;
  CMOCK_flexCAN_write_wand_wear_debug_CALLBACK flexCAN_write_wand_wear_debug_CallbackFunctionPointer;
  int flexCAN_write_wand_wear_debug_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE flexCAN_write_wand_wear_debug_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockcan_debug_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.flexCAN_write_pumpdebug_IgnoreBool)
    Mock.flexCAN_write_pumpdebug_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.flexCAN_write_pumpdebug_CallInstance, cmock_line, "Function 'flexCAN_write_pumpdebug' called less times than expected.");
  if (Mock.flexCAN_write_pumpdebug_CallbackFunctionPointer != NULL)
    Mock.flexCAN_write_pumpdebug_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.FlexCAN_Write_PWMDebug_IgnoreBool)
    Mock.FlexCAN_Write_PWMDebug_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.FlexCAN_Write_PWMDebug_CallInstance, cmock_line, "Function 'FlexCAN_Write_PWMDebug' called less times than expected.");
  if (Mock.FlexCAN_Write_PWMDebug_CallbackFunctionPointer != NULL)
    Mock.FlexCAN_Write_PWMDebug_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.flexCAN_write_wanddebug_IgnoreBool)
    Mock.flexCAN_write_wanddebug_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.flexCAN_write_wanddebug_CallInstance, cmock_line, "Function 'flexCAN_write_wanddebug' called less times than expected.");
  if (Mock.flexCAN_write_wanddebug_CallbackFunctionPointer != NULL)
    Mock.flexCAN_write_wanddebug_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.flexCAN_write_wireless_IgnoreBool)
    Mock.flexCAN_write_wireless_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.flexCAN_write_wireless_CallInstance, cmock_line, "Function 'flexCAN_write_wireless' called less times than expected.");
  if (Mock.flexCAN_write_wireless_CallbackFunctionPointer != NULL)
    Mock.flexCAN_write_wireless_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.flexCAN_write_wand_wear_debug_IgnoreBool)
    Mock.flexCAN_write_wand_wear_debug_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.flexCAN_write_wand_wear_debug_CallInstance, cmock_line, "Function 'flexCAN_write_wand_wear_debug' called less times than expected.");
  if (Mock.flexCAN_write_wand_wear_debug_CallbackFunctionPointer != NULL)
    Mock.flexCAN_write_wand_wear_debug_CallInstance = CMOCK_GUTS_NONE;
}

void Mockcan_debug_Init(void)
{
  Mockcan_debug_Destroy();
}

void Mockcan_debug_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.flexCAN_write_pumpdebug_CallbackFunctionPointer = NULL;
  Mock.flexCAN_write_pumpdebug_CallbackCalls = 0;
  Mock.FlexCAN_Write_PWMDebug_CallbackFunctionPointer = NULL;
  Mock.FlexCAN_Write_PWMDebug_CallbackCalls = 0;
  Mock.flexCAN_write_wanddebug_CallbackFunctionPointer = NULL;
  Mock.flexCAN_write_wanddebug_CallbackCalls = 0;
  Mock.flexCAN_write_wireless_CallbackFunctionPointer = NULL;
  Mock.flexCAN_write_wireless_CallbackCalls = 0;
  Mock.flexCAN_write_wand_wear_debug_CallbackFunctionPointer = NULL;
  Mock.flexCAN_write_wand_wear_debug_CallbackCalls = 0;
}

uint8_t flexCAN_write_pumpdebug(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.flexCAN_write_pumpdebug_CallInstance);
  Mock.flexCAN_write_pumpdebug_CallInstance = CMock_Guts_MemNext(Mock.flexCAN_write_pumpdebug_CallInstance);
  if (Mock.flexCAN_write_pumpdebug_CallbackFunctionPointer != NULL)
  {
    return Mock.flexCAN_write_pumpdebug_CallbackFunctionPointer(Mock.flexCAN_write_pumpdebug_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'flexCAN_write_pumpdebug' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.flexCAN_write_pumpdebug_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.flexCAN_write_pumpdebug_FinalReturn;
    Mock.flexCAN_write_pumpdebug_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void flexCAN_write_pumpdebug_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE));
  CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_pumpdebug_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_pumpdebug_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.flexCAN_write_pumpdebug_IgnoreBool = (int)1;
}

void flexCAN_write_pumpdebug_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE));
  CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_pumpdebug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_pumpdebug_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_pumpdebug_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void flexCAN_write_pumpdebug_StubWithCallback(CMOCK_flexCAN_write_pumpdebug_CALLBACK Callback)
{
  Mock.flexCAN_write_pumpdebug_CallbackFunctionPointer = Callback;
}

void FlexCAN_Write_PWMDebug(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlexCAN_Write_PWMDebug_CallInstance);
  Mock.FlexCAN_Write_PWMDebug_CallInstance = CMock_Guts_MemNext(Mock.FlexCAN_Write_PWMDebug_CallInstance);
  if (Mock.FlexCAN_Write_PWMDebug_CallbackFunctionPointer != NULL)
  {
    Mock.FlexCAN_Write_PWMDebug_CallbackFunctionPointer(Mock.FlexCAN_Write_PWMDebug_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'FlexCAN_Write_PWMDebug' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.FlexCAN_Write_PWMDebug_IgnoreBool)
  {
    return;
  }
}

void FlexCAN_Write_PWMDebug_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE));
  CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.FlexCAN_Write_PWMDebug_CallInstance = CMock_Guts_MemChain(Mock.FlexCAN_Write_PWMDebug_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.FlexCAN_Write_PWMDebug_IgnoreBool = (int)1;
}

void FlexCAN_Write_PWMDebug_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE));
  CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlexCAN_Write_PWMDebug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.FlexCAN_Write_PWMDebug_CallInstance = CMock_Guts_MemChain(Mock.FlexCAN_Write_PWMDebug_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void FlexCAN_Write_PWMDebug_StubWithCallback(CMOCK_FlexCAN_Write_PWMDebug_CALLBACK Callback)
{
  Mock.FlexCAN_Write_PWMDebug_CallbackFunctionPointer = Callback;
}

uint8_t flexCAN_write_wanddebug(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.flexCAN_write_wanddebug_CallInstance);
  Mock.flexCAN_write_wanddebug_CallInstance = CMock_Guts_MemNext(Mock.flexCAN_write_wanddebug_CallInstance);
  if (Mock.flexCAN_write_wanddebug_CallbackFunctionPointer != NULL)
  {
    return Mock.flexCAN_write_wanddebug_CallbackFunctionPointer(Mock.flexCAN_write_wanddebug_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'flexCAN_write_wanddebug' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.flexCAN_write_wanddebug_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.flexCAN_write_wanddebug_FinalReturn;
    Mock.flexCAN_write_wanddebug_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void flexCAN_write_wanddebug_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE));
  CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_wanddebug_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_wanddebug_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.flexCAN_write_wanddebug_IgnoreBool = (int)1;
}

void flexCAN_write_wanddebug_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE));
  CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_wanddebug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_wanddebug_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_wanddebug_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void flexCAN_write_wanddebug_StubWithCallback(CMOCK_flexCAN_write_wanddebug_CALLBACK Callback)
{
  Mock.flexCAN_write_wanddebug_CallbackFunctionPointer = Callback;
}

uint8_t flexCAN_write_wireless(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_flexCAN_write_wireless_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_wireless_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.flexCAN_write_wireless_CallInstance);
  Mock.flexCAN_write_wireless_CallInstance = CMock_Guts_MemNext(Mock.flexCAN_write_wireless_CallInstance);
  if (Mock.flexCAN_write_wireless_CallbackFunctionPointer != NULL)
  {
    return Mock.flexCAN_write_wireless_CallbackFunctionPointer(Mock.flexCAN_write_wireless_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'flexCAN_write_wireless' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.flexCAN_write_wireless_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.flexCAN_write_wireless_FinalReturn;
    Mock.flexCAN_write_wireless_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void flexCAN_write_wireless_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_wireless_CALL_INSTANCE));
  CMOCK_flexCAN_write_wireless_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_wireless_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_wireless_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_wireless_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.flexCAN_write_wireless_IgnoreBool = (int)1;
}

void flexCAN_write_wireless_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_wireless_CALL_INSTANCE));
  CMOCK_flexCAN_write_wireless_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_wireless_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_wireless_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_wireless_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void flexCAN_write_wireless_StubWithCallback(CMOCK_flexCAN_write_wireless_CALLBACK Callback)
{
  Mock.flexCAN_write_wireless_CallbackFunctionPointer = Callback;
}

uint8_t flexCAN_write_wand_wear_debug(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.flexCAN_write_wand_wear_debug_CallInstance);
  Mock.flexCAN_write_wand_wear_debug_CallInstance = CMock_Guts_MemNext(Mock.flexCAN_write_wand_wear_debug_CallInstance);
  if (Mock.flexCAN_write_wand_wear_debug_CallbackFunctionPointer != NULL)
  {
    return Mock.flexCAN_write_wand_wear_debug_CallbackFunctionPointer(Mock.flexCAN_write_wand_wear_debug_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'flexCAN_write_wand_wear_debug' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.flexCAN_write_wand_wear_debug_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.flexCAN_write_wand_wear_debug_FinalReturn;
    Mock.flexCAN_write_wand_wear_debug_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void flexCAN_write_wand_wear_debug_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE));
  CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_wand_wear_debug_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_wand_wear_debug_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.flexCAN_write_wand_wear_debug_IgnoreBool = (int)1;
}

void flexCAN_write_wand_wear_debug_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE));
  CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE* cmock_call_instance = (CMOCK_flexCAN_write_wand_wear_debug_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flexCAN_write_wand_wear_debug_CallInstance = CMock_Guts_MemChain(Mock.flexCAN_write_wand_wear_debug_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void flexCAN_write_wand_wear_debug_StubWithCallback(CMOCK_flexCAN_write_wand_wear_debug_CALLBACK Callback)
{
  Mock.flexCAN_write_wand_wear_debug_CallbackFunctionPointer = Callback;
}

