/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKADC_H
#define _MOCKADC_H

#include "Types.h"
#include "adc.h"

void Mockadc_Init(void);
void Mockadc_Destroy(void);
void Mockadc_Verify(void);




#define adc_init_IgnoreAndReturn(cmock_retval) adc_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void adc_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define adc_init_ExpectAndReturn(cmock_retval) adc_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void adc_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_adc_init_CALLBACK)(int cmock_num_calls);
void adc_init_StubWithCallback(CMOCK_adc_init_CALLBACK Callback);
#define ADC_DMA_Init_Ignore() ADC_DMA_Init_CMockIgnore(__LINE__)
void ADC_DMA_Init_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define ADC_DMA_Init_Expect() ADC_DMA_Init_CMockExpect(__LINE__)
void ADC_DMA_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_ADC_DMA_Init_CALLBACK)(int cmock_num_calls);
void ADC_DMA_Init_StubWithCallback(CMOCK_ADC_DMA_Init_CALLBACK Callback);
#define irms_overcurrent_IgnoreAndReturn(cmock_retval) irms_overcurrent_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void irms_overcurrent_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define irms_overcurrent_ExpectAndReturn(cmock_retval) irms_overcurrent_CMockExpectAndReturn(__LINE__, cmock_retval)
void irms_overcurrent_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_irms_overcurrent_CALLBACK)(int cmock_num_calls);
void irms_overcurrent_StubWithCallback(CMOCK_irms_overcurrent_CALLBACK Callback);
#define ADC_Cal_IgnoreAndReturn(cmock_retval) ADC_Cal_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ADC_Cal_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define ADC_Cal_ExpectAndReturn(cmock_arg1, cmock_retval) ADC_Cal_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void ADC_Cal_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_MemMapPtr cmock_arg1, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_ADC_Cal_CALLBACK)(ADC_MemMapPtr cmock_arg1, int cmock_num_calls);
void ADC_Cal_StubWithCallback(CMOCK_ADC_Cal_CALLBACK Callback);
#define poll_adc_data_IgnoreAndReturn(cmock_retval) poll_adc_data_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void poll_adc_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define poll_adc_data_ExpectAndReturn(cmock_retval) poll_adc_data_CMockExpectAndReturn(__LINE__, cmock_retval)
void poll_adc_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_poll_adc_data_CALLBACK)(int cmock_num_calls);
void poll_adc_data_StubWithCallback(CMOCK_poll_adc_data_CALLBACK Callback);
#define get_temp_IgnoreAndReturn(cmock_retval) get_temp_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_temp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float32_t cmock_to_return);
#define get_temp_ExpectAndReturn(cmock_arg1, cmock_retval) get_temp_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void get_temp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_arg1, float32_t cmock_to_return);
typedef float32_t (* CMOCK_get_temp_CALLBACK)(uint16_t cmock_arg1, int cmock_num_calls);
void get_temp_StubWithCallback(CMOCK_get_temp_CALLBACK Callback);
#define adc3_coco_IgnoreAndReturn(cmock_retval) adc3_coco_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void adc3_coco_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define adc3_coco_ExpectAndReturn(cmock_retval) adc3_coco_CMockExpectAndReturn(__LINE__, cmock_retval)
void adc3_coco_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_adc3_coco_CALLBACK)(int cmock_num_calls);
void adc3_coco_StubWithCallback(CMOCK_adc3_coco_CALLBACK Callback);
#define irms2_adc_result_IgnoreAndReturn(cmock_retval) irms2_adc_result_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void irms2_adc_result_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define irms2_adc_result_ExpectAndReturn(cmock_retval) irms2_adc_result_CMockExpectAndReturn(__LINE__, cmock_retval)
void irms2_adc_result_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_irms2_adc_result_CALLBACK)(int cmock_num_calls);
void irms2_adc_result_StubWithCallback(CMOCK_irms2_adc_result_CALLBACK Callback);
#define legacy_irms_adc_result_IgnoreAndReturn(cmock_retval) legacy_irms_adc_result_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void legacy_irms_adc_result_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define legacy_irms_adc_result_ExpectAndReturn(cmock_retval) legacy_irms_adc_result_CMockExpectAndReturn(__LINE__, cmock_retval)
void legacy_irms_adc_result_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_legacy_irms_adc_result_CALLBACK)(int cmock_num_calls);
void legacy_irms_adc_result_StubWithCallback(CMOCK_legacy_irms_adc_result_CALLBACK Callback);
#define legacy_irms_over_energy_IgnoreAndReturn(cmock_retval) legacy_irms_over_energy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void legacy_irms_over_energy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define legacy_irms_over_energy_ExpectAndReturn(cmock_retval) legacy_irms_over_energy_CMockExpectAndReturn(__LINE__, cmock_retval)
void legacy_irms_over_energy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_legacy_irms_over_energy_CALLBACK)(int cmock_num_calls);
void legacy_irms_over_energy_StubWithCallback(CMOCK_legacy_irms_over_energy_CALLBACK Callback);
#define legacy_timer_wands_Ignore() legacy_timer_wands_CMockIgnore(__LINE__)
void legacy_timer_wands_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define legacy_timer_wands_Expect() legacy_timer_wands_CMockExpect(__LINE__)
void legacy_timer_wands_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_legacy_timer_wands_CALLBACK)(int cmock_num_calls);
void legacy_timer_wands_StubWithCallback(CMOCK_legacy_timer_wands_CALLBACK Callback);
#define adc_init_2_IgnoreAndReturn(cmock_retval) adc_init_2_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void adc_init_2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define adc_init_2_ExpectAndReturn(cmock_retval) adc_init_2_CMockExpectAndReturn(__LINE__, cmock_retval)
void adc_init_2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_adc_init_2_CALLBACK)(int cmock_num_calls);
void adc_init_2_StubWithCallback(CMOCK_adc_init_2_CALLBACK Callback);
#define adc0_coco_stator_IgnoreAndReturn(cmock_retval) adc0_coco_stator_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void adc0_coco_stator_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define adc0_coco_stator_ExpectAndReturn(cmock_retval) adc0_coco_stator_CMockExpectAndReturn(__LINE__, cmock_retval)
void adc0_coco_stator_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_adc0_coco_stator_CALLBACK)(int cmock_num_calls);
void adc0_coco_stator_StubWithCallback(CMOCK_adc0_coco_stator_CALLBACK Callback);
#define print_debug_IgnoreAndReturn(cmock_retval) print_debug_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void print_debug_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define print_debug_ExpectAndReturn(cmock_retval) print_debug_CMockExpectAndReturn(__LINE__, cmock_retval)
void print_debug_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_print_debug_CALLBACK)(int cmock_num_calls);
void print_debug_StubWithCallback(CMOCK_print_debug_CALLBACK Callback);

#endif
