/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mocksw_manager.h"

typedef struct _CMOCK_commence_uis_sw_update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_commence_uis_sw_update_CALL_INSTANCE;

typedef struct _CMOCK_commence_gs_sw_update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_commence_gs_sw_update_CALL_INSTANCE;

typedef struct _CMOCK_ui_update_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_ui_update_status_CALL_INSTANCE;

typedef struct _CMOCK_check4gsfw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  uint8_t Expected_cmock_arg1;
  uint8_t Expected_cmock_arg2;

} CMOCK_check4gsfw_CALL_INSTANCE;

typedef struct _CMOCK_check4uifw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  uint8_t Expected_cmock_arg1;
  uint8_t Expected_cmock_arg2;

} CMOCK_check4uifw_CALL_INSTANCE;

typedef struct _CMOCK_cancel_sw_update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_cancel_sw_update_CALL_INSTANCE;

typedef struct _CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE;

static struct Mocksw_managerInstance
{
  int commence_uis_sw_update_IgnoreBool;
  uint8_t commence_uis_sw_update_FinalReturn;
  CMOCK_commence_uis_sw_update_CALLBACK commence_uis_sw_update_CallbackFunctionPointer;
  int commence_uis_sw_update_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE commence_uis_sw_update_CallInstance;
  int commence_gs_sw_update_IgnoreBool;
  uint8_t commence_gs_sw_update_FinalReturn;
  CMOCK_commence_gs_sw_update_CALLBACK commence_gs_sw_update_CallbackFunctionPointer;
  int commence_gs_sw_update_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE commence_gs_sw_update_CallInstance;
  int ui_update_status_IgnoreBool;
  uint8_t ui_update_status_FinalReturn;
  CMOCK_ui_update_status_CALLBACK ui_update_status_CallbackFunctionPointer;
  int ui_update_status_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ui_update_status_CallInstance;
  int check4gsfw_IgnoreBool;
  uint8_t check4gsfw_FinalReturn;
  CMOCK_check4gsfw_CALLBACK check4gsfw_CallbackFunctionPointer;
  int check4gsfw_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE check4gsfw_CallInstance;
  int check4uifw_IgnoreBool;
  uint8_t check4uifw_FinalReturn;
  CMOCK_check4uifw_CALLBACK check4uifw_CallbackFunctionPointer;
  int check4uifw_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE check4uifw_CallInstance;
  int cancel_sw_update_IgnoreBool;
  uint8_t cancel_sw_update_FinalReturn;
  CMOCK_cancel_sw_update_CALLBACK cancel_sw_update_CallbackFunctionPointer;
  int cancel_sw_update_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cancel_sw_update_CallInstance;
  int ui_gs_firmware_update_pause_IgnoreBool;
  uint8_t ui_gs_firmware_update_pause_FinalReturn;
  CMOCK_ui_gs_firmware_update_pause_CALLBACK ui_gs_firmware_update_pause_CallbackFunctionPointer;
  int ui_gs_firmware_update_pause_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ui_gs_firmware_update_pause_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocksw_manager_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.commence_uis_sw_update_IgnoreBool)
    Mock.commence_uis_sw_update_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.commence_uis_sw_update_CallInstance, cmock_line, "Function 'commence_uis_sw_update' called less times than expected.");
  if (Mock.commence_uis_sw_update_CallbackFunctionPointer != NULL)
    Mock.commence_uis_sw_update_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.commence_gs_sw_update_IgnoreBool)
    Mock.commence_gs_sw_update_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.commence_gs_sw_update_CallInstance, cmock_line, "Function 'commence_gs_sw_update' called less times than expected.");
  if (Mock.commence_gs_sw_update_CallbackFunctionPointer != NULL)
    Mock.commence_gs_sw_update_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ui_update_status_IgnoreBool)
    Mock.ui_update_status_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ui_update_status_CallInstance, cmock_line, "Function 'ui_update_status' called less times than expected.");
  if (Mock.ui_update_status_CallbackFunctionPointer != NULL)
    Mock.ui_update_status_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.check4gsfw_IgnoreBool)
    Mock.check4gsfw_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.check4gsfw_CallInstance, cmock_line, "Function 'check4gsfw' called less times than expected.");
  if (Mock.check4gsfw_CallbackFunctionPointer != NULL)
    Mock.check4gsfw_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.check4uifw_IgnoreBool)
    Mock.check4uifw_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.check4uifw_CallInstance, cmock_line, "Function 'check4uifw' called less times than expected.");
  if (Mock.check4uifw_CallbackFunctionPointer != NULL)
    Mock.check4uifw_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cancel_sw_update_IgnoreBool)
    Mock.cancel_sw_update_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cancel_sw_update_CallInstance, cmock_line, "Function 'cancel_sw_update' called less times than expected.");
  if (Mock.cancel_sw_update_CallbackFunctionPointer != NULL)
    Mock.cancel_sw_update_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ui_gs_firmware_update_pause_IgnoreBool)
    Mock.ui_gs_firmware_update_pause_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ui_gs_firmware_update_pause_CallInstance, cmock_line, "Function 'ui_gs_firmware_update_pause' called less times than expected.");
  if (Mock.ui_gs_firmware_update_pause_CallbackFunctionPointer != NULL)
    Mock.ui_gs_firmware_update_pause_CallInstance = CMOCK_GUTS_NONE;
}

void Mocksw_manager_Init(void)
{
  Mocksw_manager_Destroy();
}

void Mocksw_manager_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.commence_uis_sw_update_CallbackFunctionPointer = NULL;
  Mock.commence_uis_sw_update_CallbackCalls = 0;
  Mock.commence_gs_sw_update_CallbackFunctionPointer = NULL;
  Mock.commence_gs_sw_update_CallbackCalls = 0;
  Mock.ui_update_status_CallbackFunctionPointer = NULL;
  Mock.ui_update_status_CallbackCalls = 0;
  Mock.check4gsfw_CallbackFunctionPointer = NULL;
  Mock.check4gsfw_CallbackCalls = 0;
  Mock.check4uifw_CallbackFunctionPointer = NULL;
  Mock.check4uifw_CallbackCalls = 0;
  Mock.cancel_sw_update_CallbackFunctionPointer = NULL;
  Mock.cancel_sw_update_CallbackCalls = 0;
  Mock.ui_gs_firmware_update_pause_CallbackFunctionPointer = NULL;
  Mock.ui_gs_firmware_update_pause_CallbackCalls = 0;
}

uint8_t commence_uis_sw_update(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_commence_uis_sw_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_commence_uis_sw_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.commence_uis_sw_update_CallInstance);
  Mock.commence_uis_sw_update_CallInstance = CMock_Guts_MemNext(Mock.commence_uis_sw_update_CallInstance);
  if (Mock.commence_uis_sw_update_CallbackFunctionPointer != NULL)
  {
    return Mock.commence_uis_sw_update_CallbackFunctionPointer(Mock.commence_uis_sw_update_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'commence_uis_sw_update' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.commence_uis_sw_update_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.commence_uis_sw_update_FinalReturn;
    Mock.commence_uis_sw_update_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void commence_uis_sw_update_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_commence_uis_sw_update_CALL_INSTANCE));
  CMOCK_commence_uis_sw_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_commence_uis_sw_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.commence_uis_sw_update_CallInstance = CMock_Guts_MemChain(Mock.commence_uis_sw_update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.commence_uis_sw_update_IgnoreBool = (int)1;
}

void commence_uis_sw_update_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_commence_uis_sw_update_CALL_INSTANCE));
  CMOCK_commence_uis_sw_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_commence_uis_sw_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.commence_uis_sw_update_CallInstance = CMock_Guts_MemChain(Mock.commence_uis_sw_update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void commence_uis_sw_update_StubWithCallback(CMOCK_commence_uis_sw_update_CALLBACK Callback)
{
  Mock.commence_uis_sw_update_CallbackFunctionPointer = Callback;
}

uint8_t commence_gs_sw_update(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_commence_gs_sw_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_commence_gs_sw_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.commence_gs_sw_update_CallInstance);
  Mock.commence_gs_sw_update_CallInstance = CMock_Guts_MemNext(Mock.commence_gs_sw_update_CallInstance);
  if (Mock.commence_gs_sw_update_CallbackFunctionPointer != NULL)
  {
    return Mock.commence_gs_sw_update_CallbackFunctionPointer(Mock.commence_gs_sw_update_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'commence_gs_sw_update' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.commence_gs_sw_update_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.commence_gs_sw_update_FinalReturn;
    Mock.commence_gs_sw_update_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void commence_gs_sw_update_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_commence_gs_sw_update_CALL_INSTANCE));
  CMOCK_commence_gs_sw_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_commence_gs_sw_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.commence_gs_sw_update_CallInstance = CMock_Guts_MemChain(Mock.commence_gs_sw_update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.commence_gs_sw_update_IgnoreBool = (int)1;
}

void commence_gs_sw_update_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_commence_gs_sw_update_CALL_INSTANCE));
  CMOCK_commence_gs_sw_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_commence_gs_sw_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.commence_gs_sw_update_CallInstance = CMock_Guts_MemChain(Mock.commence_gs_sw_update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void commence_gs_sw_update_StubWithCallback(CMOCK_commence_gs_sw_update_CALLBACK Callback)
{
  Mock.commence_gs_sw_update_CallbackFunctionPointer = Callback;
}

uint8_t ui_update_status(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ui_update_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_ui_update_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ui_update_status_CallInstance);
  Mock.ui_update_status_CallInstance = CMock_Guts_MemNext(Mock.ui_update_status_CallInstance);
  if (Mock.ui_update_status_CallbackFunctionPointer != NULL)
  {
    return Mock.ui_update_status_CallbackFunctionPointer(Mock.ui_update_status_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'ui_update_status' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.ui_update_status_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.ui_update_status_FinalReturn;
    Mock.ui_update_status_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void ui_update_status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ui_update_status_CALL_INSTANCE));
  CMOCK_ui_update_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_ui_update_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.ui_update_status_CallInstance = CMock_Guts_MemChain(Mock.ui_update_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ui_update_status_IgnoreBool = (int)1;
}

void ui_update_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ui_update_status_CALL_INSTANCE));
  CMOCK_ui_update_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_ui_update_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.ui_update_status_CallInstance = CMock_Guts_MemChain(Mock.ui_update_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ui_update_status_StubWithCallback(CMOCK_ui_update_status_CALLBACK Callback)
{
  Mock.ui_update_status_CallbackFunctionPointer = Callback;
}

uint8_t check4gsfw(uint8_t cmock_arg1, uint8_t cmock_arg2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_check4gsfw_CALL_INSTANCE* cmock_call_instance = (CMOCK_check4gsfw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.check4gsfw_CallInstance);
  Mock.check4gsfw_CallInstance = CMock_Guts_MemNext(Mock.check4gsfw_CallInstance);
  if (Mock.check4gsfw_CallbackFunctionPointer != NULL)
  {
    return Mock.check4gsfw_CallbackFunctionPointer(cmock_arg1, cmock_arg2, Mock.check4gsfw_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'check4gsfw' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.check4gsfw_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.check4gsfw_FinalReturn;
    Mock.check4gsfw_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'check4gsfw' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, cmock_line, "Function 'check4gsfw' called with unexpected value for argument 'cmock_arg2'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_check4gsfw(CMOCK_check4gsfw_CALL_INSTANCE* cmock_call_instance, uint8_t cmock_arg1, uint8_t cmock_arg2)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
}

void check4gsfw_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_check4gsfw_CALL_INSTANCE));
  CMOCK_check4gsfw_CALL_INSTANCE* cmock_call_instance = (CMOCK_check4gsfw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.check4gsfw_CallInstance = CMock_Guts_MemChain(Mock.check4gsfw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.check4gsfw_IgnoreBool = (int)1;
}

void check4gsfw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, uint8_t cmock_arg2, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_check4gsfw_CALL_INSTANCE));
  CMOCK_check4gsfw_CALL_INSTANCE* cmock_call_instance = (CMOCK_check4gsfw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.check4gsfw_CallInstance = CMock_Guts_MemChain(Mock.check4gsfw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_check4gsfw(cmock_call_instance, cmock_arg1, cmock_arg2);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void check4gsfw_StubWithCallback(CMOCK_check4gsfw_CALLBACK Callback)
{
  Mock.check4gsfw_CallbackFunctionPointer = Callback;
}

uint8_t check4uifw(uint8_t cmock_arg1, uint8_t cmock_arg2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_check4uifw_CALL_INSTANCE* cmock_call_instance = (CMOCK_check4uifw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.check4uifw_CallInstance);
  Mock.check4uifw_CallInstance = CMock_Guts_MemNext(Mock.check4uifw_CallInstance);
  if (Mock.check4uifw_CallbackFunctionPointer != NULL)
  {
    return Mock.check4uifw_CallbackFunctionPointer(cmock_arg1, cmock_arg2, Mock.check4uifw_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'check4uifw' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.check4uifw_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.check4uifw_FinalReturn;
    Mock.check4uifw_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'check4uifw' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, cmock_line, "Function 'check4uifw' called with unexpected value for argument 'cmock_arg2'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_check4uifw(CMOCK_check4uifw_CALL_INSTANCE* cmock_call_instance, uint8_t cmock_arg1, uint8_t cmock_arg2)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
}

void check4uifw_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_check4uifw_CALL_INSTANCE));
  CMOCK_check4uifw_CALL_INSTANCE* cmock_call_instance = (CMOCK_check4uifw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.check4uifw_CallInstance = CMock_Guts_MemChain(Mock.check4uifw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.check4uifw_IgnoreBool = (int)1;
}

void check4uifw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, uint8_t cmock_arg2, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_check4uifw_CALL_INSTANCE));
  CMOCK_check4uifw_CALL_INSTANCE* cmock_call_instance = (CMOCK_check4uifw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.check4uifw_CallInstance = CMock_Guts_MemChain(Mock.check4uifw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_check4uifw(cmock_call_instance, cmock_arg1, cmock_arg2);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void check4uifw_StubWithCallback(CMOCK_check4uifw_CALLBACK Callback)
{
  Mock.check4uifw_CallbackFunctionPointer = Callback;
}

uint8_t cancel_sw_update(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cancel_sw_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_cancel_sw_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cancel_sw_update_CallInstance);
  Mock.cancel_sw_update_CallInstance = CMock_Guts_MemNext(Mock.cancel_sw_update_CallInstance);
  if (Mock.cancel_sw_update_CallbackFunctionPointer != NULL)
  {
    return Mock.cancel_sw_update_CallbackFunctionPointer(Mock.cancel_sw_update_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cancel_sw_update' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.cancel_sw_update_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cancel_sw_update_FinalReturn;
    Mock.cancel_sw_update_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void cancel_sw_update_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cancel_sw_update_CALL_INSTANCE));
  CMOCK_cancel_sw_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_cancel_sw_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.cancel_sw_update_CallInstance = CMock_Guts_MemChain(Mock.cancel_sw_update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cancel_sw_update_IgnoreBool = (int)1;
}

void cancel_sw_update_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cancel_sw_update_CALL_INSTANCE));
  CMOCK_cancel_sw_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_cancel_sw_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.cancel_sw_update_CallInstance = CMock_Guts_MemChain(Mock.cancel_sw_update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void cancel_sw_update_StubWithCallback(CMOCK_cancel_sw_update_CALLBACK Callback)
{
  Mock.cancel_sw_update_CallbackFunctionPointer = Callback;
}

uint8_t ui_gs_firmware_update_pause(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE* cmock_call_instance = (CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ui_gs_firmware_update_pause_CallInstance);
  Mock.ui_gs_firmware_update_pause_CallInstance = CMock_Guts_MemNext(Mock.ui_gs_firmware_update_pause_CallInstance);
  if (Mock.ui_gs_firmware_update_pause_CallbackFunctionPointer != NULL)
  {
    return Mock.ui_gs_firmware_update_pause_CallbackFunctionPointer(Mock.ui_gs_firmware_update_pause_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'ui_gs_firmware_update_pause' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.ui_gs_firmware_update_pause_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.ui_gs_firmware_update_pause_FinalReturn;
    Mock.ui_gs_firmware_update_pause_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void ui_gs_firmware_update_pause_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE));
  CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE* cmock_call_instance = (CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.ui_gs_firmware_update_pause_CallInstance = CMock_Guts_MemChain(Mock.ui_gs_firmware_update_pause_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ui_gs_firmware_update_pause_IgnoreBool = (int)1;
}

void ui_gs_firmware_update_pause_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE));
  CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE* cmock_call_instance = (CMOCK_ui_gs_firmware_update_pause_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.ui_gs_firmware_update_pause_CallInstance = CMock_Guts_MemChain(Mock.ui_gs_firmware_update_pause_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ui_gs_firmware_update_pause_StubWithCallback(CMOCK_ui_gs_firmware_update_pause_CALLBACK Callback)
{
  Mock.ui_gs_firmware_update_pause_CallbackFunctionPointer = Callback;
}

