/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockbuck.h"

typedef struct _CMOCK_buck_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_buck_init_CALL_INSTANCE;

typedef struct _CMOCK_set_buck_voltage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uint16_t Expected_cmock_arg1;
  uint16_t Expected_cmock_arg2;

} CMOCK_set_buck_voltage_CALL_INSTANCE;

typedef struct _CMOCK_ramp_down_buck_voltage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  DAC_MemMapPtr Expected_cmock_arg1;
  uint16_t Expected_cmock_arg2;

} CMOCK_ramp_down_buck_voltage_CALL_INSTANCE;

typedef struct _CMOCK_buck_inactive_shutdown_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_buck_inactive_shutdown_CALL_INSTANCE;

typedef struct _CMOCK_vmod2_test_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_vmod2_test_CALL_INSTANCE;

typedef struct _CMOCK_set_dac_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uint16_t Expected_cmock_arg1;

} CMOCK_set_dac_CALL_INSTANCE;

typedef struct _CMOCK_sort_vmeas_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t* Expected_cmock_arg1;

} CMOCK_sort_vmeas_CALL_INSTANCE;

typedef struct _CMOCK_interp2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  uint8_t Expected_cmock_arg1;

} CMOCK_interp2_CALL_INSTANCE;

typedef struct _CMOCK_vmod2_ramp_test_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  VMOD_TEST_STATUS ReturnVal;
  uint8_t Expected_cmock_arg1;

} CMOCK_vmod2_ramp_test_CALL_INSTANCE;

typedef struct _CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  DAC_MemMapPtr Expected_cmock_arg1;
  uint16_t Expected_cmock_arg2;
  uint8_t Expected_cmock_arg3;

} CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE;

typedef struct _CMOCK_legacy_set_buck_voltage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uint16_t Expected_cmock_arg1;
  uint16_t Expected_cmock_arg2;

} CMOCK_legacy_set_buck_voltage_CALL_INSTANCE;

typedef struct _CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uint16_t Expected_cmock_arg1;

} CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE;

typedef struct _CMOCK_vmod_interp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_vmod_interp_CALL_INSTANCE;

typedef struct _CMOCK_vmod1_ramp_test_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  VMOD_TEST_STATUS ReturnVal;
  uint8_t Expected_cmock_arg1;

} CMOCK_vmod1_ramp_test_CALL_INSTANCE;

typedef struct _CMOCK_vmod1_test_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_vmod1_test_CALL_INSTANCE;

typedef struct _CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uint16_t Expected_irms;
  uint16_t Expected_current_dac;
  float32_t Expected_power_target;
  uint16_t Expected_vlimit;

} CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE;

typedef struct _CMOCK_vmod1_adc_coco_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char ReturnVal;

} CMOCK_vmod1_adc_coco_CALL_INSTANCE;

typedef struct _CMOCK_vmod2_adc_coco_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char ReturnVal;

} CMOCK_vmod2_adc_coco_CALL_INSTANCE;

static struct MockbuckInstance
{
  int buck_init_IgnoreBool;
  uint8_t buck_init_FinalReturn;
  CMOCK_buck_init_CALLBACK buck_init_CallbackFunctionPointer;
  int buck_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE buck_init_CallInstance;
  int set_buck_voltage_IgnoreBool;
  uint16_t set_buck_voltage_FinalReturn;
  CMOCK_set_buck_voltage_CALLBACK set_buck_voltage_CallbackFunctionPointer;
  int set_buck_voltage_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE set_buck_voltage_CallInstance;
  int ramp_down_buck_voltage_IgnoreBool;
  uint16_t ramp_down_buck_voltage_FinalReturn;
  CMOCK_ramp_down_buck_voltage_CALLBACK ramp_down_buck_voltage_CallbackFunctionPointer;
  int ramp_down_buck_voltage_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ramp_down_buck_voltage_CallInstance;
  int buck_inactive_shutdown_IgnoreBool;
  uint8_t buck_inactive_shutdown_FinalReturn;
  CMOCK_buck_inactive_shutdown_CALLBACK buck_inactive_shutdown_CallbackFunctionPointer;
  int buck_inactive_shutdown_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE buck_inactive_shutdown_CallInstance;
  int vmod2_test_IgnoreBool;
  uint8_t vmod2_test_FinalReturn;
  CMOCK_vmod2_test_CALLBACK vmod2_test_CallbackFunctionPointer;
  int vmod2_test_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE vmod2_test_CallInstance;
  int set_dac_IgnoreBool;
  uint16_t set_dac_FinalReturn;
  CMOCK_set_dac_CALLBACK set_dac_CallbackFunctionPointer;
  int set_dac_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE set_dac_CallInstance;
  int sort_vmeas_IgnoreBool;
  CMOCK_sort_vmeas_CALLBACK sort_vmeas_CallbackFunctionPointer;
  int sort_vmeas_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sort_vmeas_CallInstance;
  int interp2_IgnoreBool;
  uint8_t interp2_FinalReturn;
  CMOCK_interp2_CALLBACK interp2_CallbackFunctionPointer;
  int interp2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE interp2_CallInstance;
  int vmod2_ramp_test_IgnoreBool;
  VMOD_TEST_STATUS vmod2_ramp_test_FinalReturn;
  CMOCK_vmod2_ramp_test_CALLBACK vmod2_ramp_test_CallbackFunctionPointer;
  int vmod2_ramp_test_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE vmod2_ramp_test_CallInstance;
  int ramp_down_buck_test_voltage_IgnoreBool;
  uint16_t ramp_down_buck_test_voltage_FinalReturn;
  CMOCK_ramp_down_buck_test_voltage_CALLBACK ramp_down_buck_test_voltage_CallbackFunctionPointer;
  int ramp_down_buck_test_voltage_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ramp_down_buck_test_voltage_CallInstance;
  int legacy_set_buck_voltage_IgnoreBool;
  uint16_t legacy_set_buck_voltage_FinalReturn;
  CMOCK_legacy_set_buck_voltage_CALLBACK legacy_set_buck_voltage_CallbackFunctionPointer;
  int legacy_set_buck_voltage_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE legacy_set_buck_voltage_CallInstance;
  int legacy_ramp_down_buck_voltage_IgnoreBool;
  uint16_t legacy_ramp_down_buck_voltage_FinalReturn;
  CMOCK_legacy_ramp_down_buck_voltage_CALLBACK legacy_ramp_down_buck_voltage_CallbackFunctionPointer;
  int legacy_ramp_down_buck_voltage_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE legacy_ramp_down_buck_voltage_CallInstance;
  int vmod_interp_IgnoreBool;
  uint8_t vmod_interp_FinalReturn;
  CMOCK_vmod_interp_CALLBACK vmod_interp_CallbackFunctionPointer;
  int vmod_interp_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE vmod_interp_CallInstance;
  int vmod1_ramp_test_IgnoreBool;
  VMOD_TEST_STATUS vmod1_ramp_test_FinalReturn;
  CMOCK_vmod1_ramp_test_CALLBACK vmod1_ramp_test_CallbackFunctionPointer;
  int vmod1_ramp_test_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE vmod1_ramp_test_CallInstance;
  int vmod1_test_IgnoreBool;
  uint8_t vmod1_test_FinalReturn;
  CMOCK_vmod1_test_CALLBACK vmod1_test_CallbackFunctionPointer;
  int vmod1_test_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE vmod1_test_CallInstance;
  int set_buck_voltage_constant_power_IgnoreBool;
  uint16_t set_buck_voltage_constant_power_FinalReturn;
  CMOCK_set_buck_voltage_constant_power_CALLBACK set_buck_voltage_constant_power_CallbackFunctionPointer;
  int set_buck_voltage_constant_power_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE set_buck_voltage_constant_power_CallInstance;
  int vmod1_adc_coco_IgnoreBool;
  unsigned char vmod1_adc_coco_FinalReturn;
  CMOCK_vmod1_adc_coco_CALLBACK vmod1_adc_coco_CallbackFunctionPointer;
  int vmod1_adc_coco_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE vmod1_adc_coco_CallInstance;
  int vmod2_adc_coco_IgnoreBool;
  unsigned char vmod2_adc_coco_FinalReturn;
  CMOCK_vmod2_adc_coco_CALLBACK vmod2_adc_coco_CallbackFunctionPointer;
  int vmod2_adc_coco_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE vmod2_adc_coco_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockbuck_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.buck_init_IgnoreBool)
    Mock.buck_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.buck_init_CallInstance, cmock_line, "Function 'buck_init' called less times than expected.");
  if (Mock.buck_init_CallbackFunctionPointer != NULL)
    Mock.buck_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.set_buck_voltage_IgnoreBool)
    Mock.set_buck_voltage_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.set_buck_voltage_CallInstance, cmock_line, "Function 'set_buck_voltage' called less times than expected.");
  if (Mock.set_buck_voltage_CallbackFunctionPointer != NULL)
    Mock.set_buck_voltage_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ramp_down_buck_voltage_IgnoreBool)
    Mock.ramp_down_buck_voltage_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ramp_down_buck_voltage_CallInstance, cmock_line, "Function 'ramp_down_buck_voltage' called less times than expected.");
  if (Mock.ramp_down_buck_voltage_CallbackFunctionPointer != NULL)
    Mock.ramp_down_buck_voltage_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.buck_inactive_shutdown_IgnoreBool)
    Mock.buck_inactive_shutdown_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.buck_inactive_shutdown_CallInstance, cmock_line, "Function 'buck_inactive_shutdown' called less times than expected.");
  if (Mock.buck_inactive_shutdown_CallbackFunctionPointer != NULL)
    Mock.buck_inactive_shutdown_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.vmod2_test_IgnoreBool)
    Mock.vmod2_test_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.vmod2_test_CallInstance, cmock_line, "Function 'vmod2_test' called less times than expected.");
  if (Mock.vmod2_test_CallbackFunctionPointer != NULL)
    Mock.vmod2_test_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.set_dac_IgnoreBool)
    Mock.set_dac_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.set_dac_CallInstance, cmock_line, "Function 'set_dac' called less times than expected.");
  if (Mock.set_dac_CallbackFunctionPointer != NULL)
    Mock.set_dac_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sort_vmeas_IgnoreBool)
    Mock.sort_vmeas_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sort_vmeas_CallInstance, cmock_line, "Function 'sort_vmeas' called less times than expected.");
  if (Mock.sort_vmeas_CallbackFunctionPointer != NULL)
    Mock.sort_vmeas_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.interp2_IgnoreBool)
    Mock.interp2_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.interp2_CallInstance, cmock_line, "Function 'interp2' called less times than expected.");
  if (Mock.interp2_CallbackFunctionPointer != NULL)
    Mock.interp2_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.vmod2_ramp_test_IgnoreBool)
    Mock.vmod2_ramp_test_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.vmod2_ramp_test_CallInstance, cmock_line, "Function 'vmod2_ramp_test' called less times than expected.");
  if (Mock.vmod2_ramp_test_CallbackFunctionPointer != NULL)
    Mock.vmod2_ramp_test_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ramp_down_buck_test_voltage_IgnoreBool)
    Mock.ramp_down_buck_test_voltage_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ramp_down_buck_test_voltage_CallInstance, cmock_line, "Function 'ramp_down_buck_test_voltage' called less times than expected.");
  if (Mock.ramp_down_buck_test_voltage_CallbackFunctionPointer != NULL)
    Mock.ramp_down_buck_test_voltage_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.legacy_set_buck_voltage_IgnoreBool)
    Mock.legacy_set_buck_voltage_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.legacy_set_buck_voltage_CallInstance, cmock_line, "Function 'legacy_set_buck_voltage' called less times than expected.");
  if (Mock.legacy_set_buck_voltage_CallbackFunctionPointer != NULL)
    Mock.legacy_set_buck_voltage_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.legacy_ramp_down_buck_voltage_IgnoreBool)
    Mock.legacy_ramp_down_buck_voltage_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.legacy_ramp_down_buck_voltage_CallInstance, cmock_line, "Function 'legacy_ramp_down_buck_voltage' called less times than expected.");
  if (Mock.legacy_ramp_down_buck_voltage_CallbackFunctionPointer != NULL)
    Mock.legacy_ramp_down_buck_voltage_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.vmod_interp_IgnoreBool)
    Mock.vmod_interp_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.vmod_interp_CallInstance, cmock_line, "Function 'vmod_interp' called less times than expected.");
  if (Mock.vmod_interp_CallbackFunctionPointer != NULL)
    Mock.vmod_interp_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.vmod1_ramp_test_IgnoreBool)
    Mock.vmod1_ramp_test_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.vmod1_ramp_test_CallInstance, cmock_line, "Function 'vmod1_ramp_test' called less times than expected.");
  if (Mock.vmod1_ramp_test_CallbackFunctionPointer != NULL)
    Mock.vmod1_ramp_test_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.vmod1_test_IgnoreBool)
    Mock.vmod1_test_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.vmod1_test_CallInstance, cmock_line, "Function 'vmod1_test' called less times than expected.");
  if (Mock.vmod1_test_CallbackFunctionPointer != NULL)
    Mock.vmod1_test_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.set_buck_voltage_constant_power_IgnoreBool)
    Mock.set_buck_voltage_constant_power_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.set_buck_voltage_constant_power_CallInstance, cmock_line, "Function 'set_buck_voltage_constant_power' called less times than expected.");
  if (Mock.set_buck_voltage_constant_power_CallbackFunctionPointer != NULL)
    Mock.set_buck_voltage_constant_power_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.vmod1_adc_coco_IgnoreBool)
    Mock.vmod1_adc_coco_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.vmod1_adc_coco_CallInstance, cmock_line, "Function 'vmod1_adc_coco' called less times than expected.");
  if (Mock.vmod1_adc_coco_CallbackFunctionPointer != NULL)
    Mock.vmod1_adc_coco_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.vmod2_adc_coco_IgnoreBool)
    Mock.vmod2_adc_coco_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.vmod2_adc_coco_CallInstance, cmock_line, "Function 'vmod2_adc_coco' called less times than expected.");
  if (Mock.vmod2_adc_coco_CallbackFunctionPointer != NULL)
    Mock.vmod2_adc_coco_CallInstance = CMOCK_GUTS_NONE;
}

void Mockbuck_Init(void)
{
  Mockbuck_Destroy();
}

void Mockbuck_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.buck_init_CallbackFunctionPointer = NULL;
  Mock.buck_init_CallbackCalls = 0;
  Mock.set_buck_voltage_CallbackFunctionPointer = NULL;
  Mock.set_buck_voltage_CallbackCalls = 0;
  Mock.ramp_down_buck_voltage_CallbackFunctionPointer = NULL;
  Mock.ramp_down_buck_voltage_CallbackCalls = 0;
  Mock.buck_inactive_shutdown_CallbackFunctionPointer = NULL;
  Mock.buck_inactive_shutdown_CallbackCalls = 0;
  Mock.vmod2_test_CallbackFunctionPointer = NULL;
  Mock.vmod2_test_CallbackCalls = 0;
  Mock.set_dac_CallbackFunctionPointer = NULL;
  Mock.set_dac_CallbackCalls = 0;
  Mock.sort_vmeas_CallbackFunctionPointer = NULL;
  Mock.sort_vmeas_CallbackCalls = 0;
  Mock.interp2_CallbackFunctionPointer = NULL;
  Mock.interp2_CallbackCalls = 0;
  Mock.vmod2_ramp_test_CallbackFunctionPointer = NULL;
  Mock.vmod2_ramp_test_CallbackCalls = 0;
  Mock.ramp_down_buck_test_voltage_CallbackFunctionPointer = NULL;
  Mock.ramp_down_buck_test_voltage_CallbackCalls = 0;
  Mock.legacy_set_buck_voltage_CallbackFunctionPointer = NULL;
  Mock.legacy_set_buck_voltage_CallbackCalls = 0;
  Mock.legacy_ramp_down_buck_voltage_CallbackFunctionPointer = NULL;
  Mock.legacy_ramp_down_buck_voltage_CallbackCalls = 0;
  Mock.vmod_interp_CallbackFunctionPointer = NULL;
  Mock.vmod_interp_CallbackCalls = 0;
  Mock.vmod1_ramp_test_CallbackFunctionPointer = NULL;
  Mock.vmod1_ramp_test_CallbackCalls = 0;
  Mock.vmod1_test_CallbackFunctionPointer = NULL;
  Mock.vmod1_test_CallbackCalls = 0;
  Mock.set_buck_voltage_constant_power_CallbackFunctionPointer = NULL;
  Mock.set_buck_voltage_constant_power_CallbackCalls = 0;
  Mock.vmod1_adc_coco_CallbackFunctionPointer = NULL;
  Mock.vmod1_adc_coco_CallbackCalls = 0;
  Mock.vmod2_adc_coco_CallbackFunctionPointer = NULL;
  Mock.vmod2_adc_coco_CallbackCalls = 0;
}

uint8_t buck_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_buck_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_buck_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.buck_init_CallInstance);
  Mock.buck_init_CallInstance = CMock_Guts_MemNext(Mock.buck_init_CallInstance);
  if (Mock.buck_init_CallbackFunctionPointer != NULL)
  {
    return Mock.buck_init_CallbackFunctionPointer(Mock.buck_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'buck_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.buck_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.buck_init_FinalReturn;
    Mock.buck_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void buck_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_buck_init_CALL_INSTANCE));
  CMOCK_buck_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_buck_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.buck_init_CallInstance = CMock_Guts_MemChain(Mock.buck_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.buck_init_IgnoreBool = (int)1;
}

void buck_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_buck_init_CALL_INSTANCE));
  CMOCK_buck_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_buck_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.buck_init_CallInstance = CMock_Guts_MemChain(Mock.buck_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void buck_init_StubWithCallback(CMOCK_buck_init_CALLBACK Callback)
{
  Mock.buck_init_CallbackFunctionPointer = Callback;
}

uint16_t set_buck_voltage(uint16_t cmock_arg1, uint16_t cmock_arg2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_buck_voltage_CallInstance);
  Mock.set_buck_voltage_CallInstance = CMock_Guts_MemNext(Mock.set_buck_voltage_CallInstance);
  if (Mock.set_buck_voltage_CallbackFunctionPointer != NULL)
  {
    return Mock.set_buck_voltage_CallbackFunctionPointer(cmock_arg1, cmock_arg2, Mock.set_buck_voltage_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'set_buck_voltage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.set_buck_voltage_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.set_buck_voltage_FinalReturn;
    Mock.set_buck_voltage_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'set_buck_voltage' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, cmock_line, "Function 'set_buck_voltage' called with unexpected value for argument 'cmock_arg2'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_set_buck_voltage(CMOCK_set_buck_voltage_CALL_INSTANCE* cmock_call_instance, uint16_t cmock_arg1, uint16_t cmock_arg2)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
}

void set_buck_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_buck_voltage_CALL_INSTANCE));
  CMOCK_set_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.set_buck_voltage_CallInstance = CMock_Guts_MemChain(Mock.set_buck_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.set_buck_voltage_IgnoreBool = (int)1;
}

void set_buck_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_arg1, uint16_t cmock_arg2, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_buck_voltage_CALL_INSTANCE));
  CMOCK_set_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.set_buck_voltage_CallInstance = CMock_Guts_MemChain(Mock.set_buck_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_set_buck_voltage(cmock_call_instance, cmock_arg1, cmock_arg2);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_buck_voltage_StubWithCallback(CMOCK_set_buck_voltage_CALLBACK Callback)
{
  Mock.set_buck_voltage_CallbackFunctionPointer = Callback;
}

uint16_t ramp_down_buck_voltage(DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ramp_down_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_ramp_down_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ramp_down_buck_voltage_CallInstance);
  Mock.ramp_down_buck_voltage_CallInstance = CMock_Guts_MemNext(Mock.ramp_down_buck_voltage_CallInstance);
  if (Mock.ramp_down_buck_voltage_CallbackFunctionPointer != NULL)
  {
    return Mock.ramp_down_buck_voltage_CallbackFunctionPointer(cmock_arg1, cmock_arg2, Mock.ramp_down_buck_voltage_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'ramp_down_buck_voltage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.ramp_down_buck_voltage_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.ramp_down_buck_voltage_FinalReturn;
    Mock.ramp_down_buck_voltage_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1), sizeof(DAC_MemMapPtr), cmock_line, "Function 'ramp_down_buck_voltage' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, cmock_line, "Function 'ramp_down_buck_voltage' called with unexpected value for argument 'cmock_arg2'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ramp_down_buck_voltage(CMOCK_ramp_down_buck_voltage_CALL_INSTANCE* cmock_call_instance, DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2)
{
  memcpy(&cmock_call_instance->Expected_cmock_arg1, &cmock_arg1, sizeof(DAC_MemMapPtr));
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
}

void ramp_down_buck_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ramp_down_buck_voltage_CALL_INSTANCE));
  CMOCK_ramp_down_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_ramp_down_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.ramp_down_buck_voltage_CallInstance = CMock_Guts_MemChain(Mock.ramp_down_buck_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ramp_down_buck_voltage_IgnoreBool = (int)1;
}

void ramp_down_buck_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ramp_down_buck_voltage_CALL_INSTANCE));
  CMOCK_ramp_down_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_ramp_down_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.ramp_down_buck_voltage_CallInstance = CMock_Guts_MemChain(Mock.ramp_down_buck_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_ramp_down_buck_voltage(cmock_call_instance, cmock_arg1, cmock_arg2);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ramp_down_buck_voltage_StubWithCallback(CMOCK_ramp_down_buck_voltage_CALLBACK Callback)
{
  Mock.ramp_down_buck_voltage_CallbackFunctionPointer = Callback;
}

uint8_t buck_inactive_shutdown(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_buck_inactive_shutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_buck_inactive_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.buck_inactive_shutdown_CallInstance);
  Mock.buck_inactive_shutdown_CallInstance = CMock_Guts_MemNext(Mock.buck_inactive_shutdown_CallInstance);
  if (Mock.buck_inactive_shutdown_CallbackFunctionPointer != NULL)
  {
    return Mock.buck_inactive_shutdown_CallbackFunctionPointer(Mock.buck_inactive_shutdown_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'buck_inactive_shutdown' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.buck_inactive_shutdown_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.buck_inactive_shutdown_FinalReturn;
    Mock.buck_inactive_shutdown_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void buck_inactive_shutdown_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_buck_inactive_shutdown_CALL_INSTANCE));
  CMOCK_buck_inactive_shutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_buck_inactive_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.buck_inactive_shutdown_CallInstance = CMock_Guts_MemChain(Mock.buck_inactive_shutdown_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.buck_inactive_shutdown_IgnoreBool = (int)1;
}

void buck_inactive_shutdown_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_buck_inactive_shutdown_CALL_INSTANCE));
  CMOCK_buck_inactive_shutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_buck_inactive_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.buck_inactive_shutdown_CallInstance = CMock_Guts_MemChain(Mock.buck_inactive_shutdown_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void buck_inactive_shutdown_StubWithCallback(CMOCK_buck_inactive_shutdown_CALLBACK Callback)
{
  Mock.buck_inactive_shutdown_CallbackFunctionPointer = Callback;
}

uint8_t vmod2_test(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vmod2_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod2_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vmod2_test_CallInstance);
  Mock.vmod2_test_CallInstance = CMock_Guts_MemNext(Mock.vmod2_test_CallInstance);
  if (Mock.vmod2_test_CallbackFunctionPointer != NULL)
  {
    return Mock.vmod2_test_CallbackFunctionPointer(Mock.vmod2_test_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'vmod2_test' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.vmod2_test_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.vmod2_test_FinalReturn;
    Mock.vmod2_test_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void vmod2_test_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod2_test_CALL_INSTANCE));
  CMOCK_vmod2_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod2_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod2_test_CallInstance = CMock_Guts_MemChain(Mock.vmod2_test_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.vmod2_test_IgnoreBool = (int)1;
}

void vmod2_test_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod2_test_CALL_INSTANCE));
  CMOCK_vmod2_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod2_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod2_test_CallInstance = CMock_Guts_MemChain(Mock.vmod2_test_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void vmod2_test_StubWithCallback(CMOCK_vmod2_test_CALLBACK Callback)
{
  Mock.vmod2_test_CallbackFunctionPointer = Callback;
}

uint16_t set_dac(uint16_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_dac_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_dac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_dac_CallInstance);
  Mock.set_dac_CallInstance = CMock_Guts_MemNext(Mock.set_dac_CallInstance);
  if (Mock.set_dac_CallbackFunctionPointer != NULL)
  {
    return Mock.set_dac_CallbackFunctionPointer(cmock_arg1, Mock.set_dac_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'set_dac' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.set_dac_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.set_dac_FinalReturn;
    Mock.set_dac_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'set_dac' called with unexpected value for argument 'cmock_arg1'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_set_dac(CMOCK_set_dac_CALL_INSTANCE* cmock_call_instance, uint16_t cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void set_dac_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_dac_CALL_INSTANCE));
  CMOCK_set_dac_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_dac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.set_dac_CallInstance = CMock_Guts_MemChain(Mock.set_dac_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.set_dac_IgnoreBool = (int)1;
}

void set_dac_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_arg1, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_dac_CALL_INSTANCE));
  CMOCK_set_dac_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_dac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.set_dac_CallInstance = CMock_Guts_MemChain(Mock.set_dac_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_set_dac(cmock_call_instance, cmock_arg1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_dac_StubWithCallback(CMOCK_set_dac_CALLBACK Callback)
{
  Mock.set_dac_CallbackFunctionPointer = Callback;
}

void sort_vmeas(uint16_t* cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sort_vmeas_CALL_INSTANCE* cmock_call_instance = (CMOCK_sort_vmeas_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sort_vmeas_CallInstance);
  Mock.sort_vmeas_CallInstance = CMock_Guts_MemNext(Mock.sort_vmeas_CallInstance);
  if (Mock.sort_vmeas_CallbackFunctionPointer != NULL)
  {
    Mock.sort_vmeas_CallbackFunctionPointer(cmock_arg1, Mock.sort_vmeas_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sort_vmeas' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.sort_vmeas_IgnoreBool)
  {
    return;
  }
  if (cmock_call_instance->Expected_cmock_arg1 == NULL)
    { UNITY_TEST_ASSERT_NULL(cmock_arg1, cmock_line, "Expected NULL. Function 'sort_vmeas' called with unexpected value for argument 'cmock_arg1'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, 1, cmock_line, "Function 'sort_vmeas' called with unexpected value for argument 'cmock_arg1'."); }
}

void CMockExpectParameters_sort_vmeas(CMOCK_sort_vmeas_CALL_INSTANCE* cmock_call_instance, uint16_t* cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void sort_vmeas_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sort_vmeas_CALL_INSTANCE));
  CMOCK_sort_vmeas_CALL_INSTANCE* cmock_call_instance = (CMOCK_sort_vmeas_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sort_vmeas_CallInstance = CMock_Guts_MemChain(Mock.sort_vmeas_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.sort_vmeas_IgnoreBool = (int)1;
}

void sort_vmeas_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t* cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sort_vmeas_CALL_INSTANCE));
  CMOCK_sort_vmeas_CALL_INSTANCE* cmock_call_instance = (CMOCK_sort_vmeas_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sort_vmeas_CallInstance = CMock_Guts_MemChain(Mock.sort_vmeas_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sort_vmeas(cmock_call_instance, cmock_arg1);
}

void sort_vmeas_StubWithCallback(CMOCK_sort_vmeas_CALLBACK Callback)
{
  Mock.sort_vmeas_CallbackFunctionPointer = Callback;
}

uint8_t interp2(uint8_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_interp2_CALL_INSTANCE* cmock_call_instance = (CMOCK_interp2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.interp2_CallInstance);
  Mock.interp2_CallInstance = CMock_Guts_MemNext(Mock.interp2_CallInstance);
  if (Mock.interp2_CallbackFunctionPointer != NULL)
  {
    return Mock.interp2_CallbackFunctionPointer(cmock_arg1, Mock.interp2_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'interp2' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.interp2_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.interp2_FinalReturn;
    Mock.interp2_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'interp2' called with unexpected value for argument 'cmock_arg1'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_interp2(CMOCK_interp2_CALL_INSTANCE* cmock_call_instance, uint8_t cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void interp2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_interp2_CALL_INSTANCE));
  CMOCK_interp2_CALL_INSTANCE* cmock_call_instance = (CMOCK_interp2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.interp2_CallInstance = CMock_Guts_MemChain(Mock.interp2_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.interp2_IgnoreBool = (int)1;
}

void interp2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_interp2_CALL_INSTANCE));
  CMOCK_interp2_CALL_INSTANCE* cmock_call_instance = (CMOCK_interp2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.interp2_CallInstance = CMock_Guts_MemChain(Mock.interp2_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_interp2(cmock_call_instance, cmock_arg1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void interp2_StubWithCallback(CMOCK_interp2_CALLBACK Callback)
{
  Mock.interp2_CallbackFunctionPointer = Callback;
}

VMOD_TEST_STATUS vmod2_ramp_test(uint8_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vmod2_ramp_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod2_ramp_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vmod2_ramp_test_CallInstance);
  Mock.vmod2_ramp_test_CallInstance = CMock_Guts_MemNext(Mock.vmod2_ramp_test_CallInstance);
  if (Mock.vmod2_ramp_test_CallbackFunctionPointer != NULL)
  {
    return Mock.vmod2_ramp_test_CallbackFunctionPointer(cmock_arg1, Mock.vmod2_ramp_test_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'vmod2_ramp_test' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.vmod2_ramp_test_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.vmod2_ramp_test_FinalReturn;
    memcpy(&Mock.vmod2_ramp_test_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(VMOD_TEST_STATUS));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'vmod2_ramp_test' called with unexpected value for argument 'cmock_arg1'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_vmod2_ramp_test(CMOCK_vmod2_ramp_test_CALL_INSTANCE* cmock_call_instance, uint8_t cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void vmod2_ramp_test_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, VMOD_TEST_STATUS cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod2_ramp_test_CALL_INSTANCE));
  CMOCK_vmod2_ramp_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod2_ramp_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod2_ramp_test_CallInstance = CMock_Guts_MemChain(Mock.vmod2_ramp_test_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.vmod2_ramp_test_IgnoreBool = (int)1;
}

void vmod2_ramp_test_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, VMOD_TEST_STATUS cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod2_ramp_test_CALL_INSTANCE));
  CMOCK_vmod2_ramp_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod2_ramp_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod2_ramp_test_CallInstance = CMock_Guts_MemChain(Mock.vmod2_ramp_test_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_vmod2_ramp_test(cmock_call_instance, cmock_arg1);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(VMOD_TEST_STATUS));
}

void vmod2_ramp_test_StubWithCallback(CMOCK_vmod2_ramp_test_CALLBACK Callback)
{
  Mock.vmod2_ramp_test_CallbackFunctionPointer = Callback;
}

uint16_t ramp_down_buck_test_voltage(DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2, uint8_t cmock_arg3)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ramp_down_buck_test_voltage_CallInstance);
  Mock.ramp_down_buck_test_voltage_CallInstance = CMock_Guts_MemNext(Mock.ramp_down_buck_test_voltage_CallInstance);
  if (Mock.ramp_down_buck_test_voltage_CallbackFunctionPointer != NULL)
  {
    return Mock.ramp_down_buck_test_voltage_CallbackFunctionPointer(cmock_arg1, cmock_arg2, cmock_arg3, Mock.ramp_down_buck_test_voltage_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'ramp_down_buck_test_voltage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.ramp_down_buck_test_voltage_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.ramp_down_buck_test_voltage_FinalReturn;
    Mock.ramp_down_buck_test_voltage_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1), sizeof(DAC_MemMapPtr), cmock_line, "Function 'ramp_down_buck_test_voltage' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, cmock_line, "Function 'ramp_down_buck_test_voltage' called with unexpected value for argument 'cmock_arg2'.");
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg3, cmock_arg3, cmock_line, "Function 'ramp_down_buck_test_voltage' called with unexpected value for argument 'cmock_arg3'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ramp_down_buck_test_voltage(CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE* cmock_call_instance, DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2, uint8_t cmock_arg3)
{
  memcpy(&cmock_call_instance->Expected_cmock_arg1, &cmock_arg1, sizeof(DAC_MemMapPtr));
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
  cmock_call_instance->Expected_cmock_arg3 = cmock_arg3;
}

void ramp_down_buck_test_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE));
  CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.ramp_down_buck_test_voltage_CallInstance = CMock_Guts_MemChain(Mock.ramp_down_buck_test_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ramp_down_buck_test_voltage_IgnoreBool = (int)1;
}

void ramp_down_buck_test_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DAC_MemMapPtr cmock_arg1, uint16_t cmock_arg2, uint8_t cmock_arg3, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE));
  CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_ramp_down_buck_test_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.ramp_down_buck_test_voltage_CallInstance = CMock_Guts_MemChain(Mock.ramp_down_buck_test_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_ramp_down_buck_test_voltage(cmock_call_instance, cmock_arg1, cmock_arg2, cmock_arg3);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void ramp_down_buck_test_voltage_StubWithCallback(CMOCK_ramp_down_buck_test_voltage_CALLBACK Callback)
{
  Mock.ramp_down_buck_test_voltage_CallbackFunctionPointer = Callback;
}

uint16_t legacy_set_buck_voltage(uint16_t cmock_arg1, uint16_t cmock_arg2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_legacy_set_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_legacy_set_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.legacy_set_buck_voltage_CallInstance);
  Mock.legacy_set_buck_voltage_CallInstance = CMock_Guts_MemNext(Mock.legacy_set_buck_voltage_CallInstance);
  if (Mock.legacy_set_buck_voltage_CallbackFunctionPointer != NULL)
  {
    return Mock.legacy_set_buck_voltage_CallbackFunctionPointer(cmock_arg1, cmock_arg2, Mock.legacy_set_buck_voltage_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'legacy_set_buck_voltage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.legacy_set_buck_voltage_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.legacy_set_buck_voltage_FinalReturn;
    Mock.legacy_set_buck_voltage_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'legacy_set_buck_voltage' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, cmock_line, "Function 'legacy_set_buck_voltage' called with unexpected value for argument 'cmock_arg2'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_legacy_set_buck_voltage(CMOCK_legacy_set_buck_voltage_CALL_INSTANCE* cmock_call_instance, uint16_t cmock_arg1, uint16_t cmock_arg2)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
}

void legacy_set_buck_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_legacy_set_buck_voltage_CALL_INSTANCE));
  CMOCK_legacy_set_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_legacy_set_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.legacy_set_buck_voltage_CallInstance = CMock_Guts_MemChain(Mock.legacy_set_buck_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.legacy_set_buck_voltage_IgnoreBool = (int)1;
}

void legacy_set_buck_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_arg1, uint16_t cmock_arg2, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_legacy_set_buck_voltage_CALL_INSTANCE));
  CMOCK_legacy_set_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_legacy_set_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.legacy_set_buck_voltage_CallInstance = CMock_Guts_MemChain(Mock.legacy_set_buck_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_legacy_set_buck_voltage(cmock_call_instance, cmock_arg1, cmock_arg2);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void legacy_set_buck_voltage_StubWithCallback(CMOCK_legacy_set_buck_voltage_CALLBACK Callback)
{
  Mock.legacy_set_buck_voltage_CallbackFunctionPointer = Callback;
}

uint16_t legacy_ramp_down_buck_voltage(uint16_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.legacy_ramp_down_buck_voltage_CallInstance);
  Mock.legacy_ramp_down_buck_voltage_CallInstance = CMock_Guts_MemNext(Mock.legacy_ramp_down_buck_voltage_CallInstance);
  if (Mock.legacy_ramp_down_buck_voltage_CallbackFunctionPointer != NULL)
  {
    return Mock.legacy_ramp_down_buck_voltage_CallbackFunctionPointer(cmock_arg1, Mock.legacy_ramp_down_buck_voltage_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'legacy_ramp_down_buck_voltage' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.legacy_ramp_down_buck_voltage_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.legacy_ramp_down_buck_voltage_FinalReturn;
    Mock.legacy_ramp_down_buck_voltage_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'legacy_ramp_down_buck_voltage' called with unexpected value for argument 'cmock_arg1'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_legacy_ramp_down_buck_voltage(CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE* cmock_call_instance, uint16_t cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void legacy_ramp_down_buck_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE));
  CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.legacy_ramp_down_buck_voltage_CallInstance = CMock_Guts_MemChain(Mock.legacy_ramp_down_buck_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.legacy_ramp_down_buck_voltage_IgnoreBool = (int)1;
}

void legacy_ramp_down_buck_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_arg1, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE));
  CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_legacy_ramp_down_buck_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.legacy_ramp_down_buck_voltage_CallInstance = CMock_Guts_MemChain(Mock.legacy_ramp_down_buck_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_legacy_ramp_down_buck_voltage(cmock_call_instance, cmock_arg1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void legacy_ramp_down_buck_voltage_StubWithCallback(CMOCK_legacy_ramp_down_buck_voltage_CALLBACK Callback)
{
  Mock.legacy_ramp_down_buck_voltage_CallbackFunctionPointer = Callback;
}

uint8_t vmod_interp(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vmod_interp_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod_interp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vmod_interp_CallInstance);
  Mock.vmod_interp_CallInstance = CMock_Guts_MemNext(Mock.vmod_interp_CallInstance);
  if (Mock.vmod_interp_CallbackFunctionPointer != NULL)
  {
    return Mock.vmod_interp_CallbackFunctionPointer(Mock.vmod_interp_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'vmod_interp' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.vmod_interp_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.vmod_interp_FinalReturn;
    Mock.vmod_interp_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void vmod_interp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod_interp_CALL_INSTANCE));
  CMOCK_vmod_interp_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod_interp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod_interp_CallInstance = CMock_Guts_MemChain(Mock.vmod_interp_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.vmod_interp_IgnoreBool = (int)1;
}

void vmod_interp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod_interp_CALL_INSTANCE));
  CMOCK_vmod_interp_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod_interp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod_interp_CallInstance = CMock_Guts_MemChain(Mock.vmod_interp_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void vmod_interp_StubWithCallback(CMOCK_vmod_interp_CALLBACK Callback)
{
  Mock.vmod_interp_CallbackFunctionPointer = Callback;
}

VMOD_TEST_STATUS vmod1_ramp_test(uint8_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vmod1_ramp_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod1_ramp_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vmod1_ramp_test_CallInstance);
  Mock.vmod1_ramp_test_CallInstance = CMock_Guts_MemNext(Mock.vmod1_ramp_test_CallInstance);
  if (Mock.vmod1_ramp_test_CallbackFunctionPointer != NULL)
  {
    return Mock.vmod1_ramp_test_CallbackFunctionPointer(cmock_arg1, Mock.vmod1_ramp_test_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'vmod1_ramp_test' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.vmod1_ramp_test_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.vmod1_ramp_test_FinalReturn;
    memcpy(&Mock.vmod1_ramp_test_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(VMOD_TEST_STATUS));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'vmod1_ramp_test' called with unexpected value for argument 'cmock_arg1'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_vmod1_ramp_test(CMOCK_vmod1_ramp_test_CALL_INSTANCE* cmock_call_instance, uint8_t cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void vmod1_ramp_test_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, VMOD_TEST_STATUS cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod1_ramp_test_CALL_INSTANCE));
  CMOCK_vmod1_ramp_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod1_ramp_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod1_ramp_test_CallInstance = CMock_Guts_MemChain(Mock.vmod1_ramp_test_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.vmod1_ramp_test_IgnoreBool = (int)1;
}

void vmod1_ramp_test_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, VMOD_TEST_STATUS cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod1_ramp_test_CALL_INSTANCE));
  CMOCK_vmod1_ramp_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod1_ramp_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod1_ramp_test_CallInstance = CMock_Guts_MemChain(Mock.vmod1_ramp_test_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_vmod1_ramp_test(cmock_call_instance, cmock_arg1);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(VMOD_TEST_STATUS));
}

void vmod1_ramp_test_StubWithCallback(CMOCK_vmod1_ramp_test_CALLBACK Callback)
{
  Mock.vmod1_ramp_test_CallbackFunctionPointer = Callback;
}

uint8_t vmod1_test(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vmod1_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod1_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vmod1_test_CallInstance);
  Mock.vmod1_test_CallInstance = CMock_Guts_MemNext(Mock.vmod1_test_CallInstance);
  if (Mock.vmod1_test_CallbackFunctionPointer != NULL)
  {
    return Mock.vmod1_test_CallbackFunctionPointer(Mock.vmod1_test_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'vmod1_test' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.vmod1_test_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.vmod1_test_FinalReturn;
    Mock.vmod1_test_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void vmod1_test_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod1_test_CALL_INSTANCE));
  CMOCK_vmod1_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod1_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod1_test_CallInstance = CMock_Guts_MemChain(Mock.vmod1_test_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.vmod1_test_IgnoreBool = (int)1;
}

void vmod1_test_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod1_test_CALL_INSTANCE));
  CMOCK_vmod1_test_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod1_test_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod1_test_CallInstance = CMock_Guts_MemChain(Mock.vmod1_test_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void vmod1_test_StubWithCallback(CMOCK_vmod1_test_CALLBACK Callback)
{
  Mock.vmod1_test_CallbackFunctionPointer = Callback;
}

uint16_t set_buck_voltage_constant_power(uint16_t irms, uint16_t current_dac, float32_t power_target, uint16_t vlimit)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_buck_voltage_constant_power_CallInstance);
  Mock.set_buck_voltage_constant_power_CallInstance = CMock_Guts_MemNext(Mock.set_buck_voltage_constant_power_CallInstance);
  if (Mock.set_buck_voltage_constant_power_CallbackFunctionPointer != NULL)
  {
    return Mock.set_buck_voltage_constant_power_CallbackFunctionPointer(irms, current_dac, power_target, vlimit, Mock.set_buck_voltage_constant_power_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'set_buck_voltage_constant_power' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.set_buck_voltage_constant_power_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.set_buck_voltage_constant_power_FinalReturn;
    Mock.set_buck_voltage_constant_power_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_irms, irms, cmock_line, "Function 'set_buck_voltage_constant_power' called with unexpected value for argument 'irms'.");
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_current_dac, current_dac, cmock_line, "Function 'set_buck_voltage_constant_power' called with unexpected value for argument 'current_dac'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_power_target), (void*)(&power_target), sizeof(float32_t), cmock_line, "Function 'set_buck_voltage_constant_power' called with unexpected value for argument 'power_target'.");
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_vlimit, vlimit, cmock_line, "Function 'set_buck_voltage_constant_power' called with unexpected value for argument 'vlimit'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_set_buck_voltage_constant_power(CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE* cmock_call_instance, uint16_t irms, uint16_t current_dac, float32_t power_target, uint16_t vlimit)
{
  cmock_call_instance->Expected_irms = irms;
  cmock_call_instance->Expected_current_dac = current_dac;
  memcpy(&cmock_call_instance->Expected_power_target, &power_target, sizeof(float32_t));
  cmock_call_instance->Expected_vlimit = vlimit;
}

void set_buck_voltage_constant_power_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE));
  CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.set_buck_voltage_constant_power_CallInstance = CMock_Guts_MemChain(Mock.set_buck_voltage_constant_power_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.set_buck_voltage_constant_power_IgnoreBool = (int)1;
}

void set_buck_voltage_constant_power_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t irms, uint16_t current_dac, float32_t power_target, uint16_t vlimit, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE));
  CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_buck_voltage_constant_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.set_buck_voltage_constant_power_CallInstance = CMock_Guts_MemChain(Mock.set_buck_voltage_constant_power_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_set_buck_voltage_constant_power(cmock_call_instance, irms, current_dac, power_target, vlimit);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_buck_voltage_constant_power_StubWithCallback(CMOCK_set_buck_voltage_constant_power_CALLBACK Callback)
{
  Mock.set_buck_voltage_constant_power_CallbackFunctionPointer = Callback;
}

unsigned char vmod1_adc_coco(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vmod1_adc_coco_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod1_adc_coco_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vmod1_adc_coco_CallInstance);
  Mock.vmod1_adc_coco_CallInstance = CMock_Guts_MemNext(Mock.vmod1_adc_coco_CallInstance);
  if (Mock.vmod1_adc_coco_CallbackFunctionPointer != NULL)
  {
    return Mock.vmod1_adc_coco_CallbackFunctionPointer(Mock.vmod1_adc_coco_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'vmod1_adc_coco' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.vmod1_adc_coco_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.vmod1_adc_coco_FinalReturn;
    Mock.vmod1_adc_coco_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void vmod1_adc_coco_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod1_adc_coco_CALL_INSTANCE));
  CMOCK_vmod1_adc_coco_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod1_adc_coco_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod1_adc_coco_CallInstance = CMock_Guts_MemChain(Mock.vmod1_adc_coco_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.vmod1_adc_coco_IgnoreBool = (int)1;
}

void vmod1_adc_coco_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod1_adc_coco_CALL_INSTANCE));
  CMOCK_vmod1_adc_coco_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod1_adc_coco_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod1_adc_coco_CallInstance = CMock_Guts_MemChain(Mock.vmod1_adc_coco_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void vmod1_adc_coco_StubWithCallback(CMOCK_vmod1_adc_coco_CALLBACK Callback)
{
  Mock.vmod1_adc_coco_CallbackFunctionPointer = Callback;
}

unsigned char vmod2_adc_coco(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vmod2_adc_coco_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod2_adc_coco_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vmod2_adc_coco_CallInstance);
  Mock.vmod2_adc_coco_CallInstance = CMock_Guts_MemNext(Mock.vmod2_adc_coco_CallInstance);
  if (Mock.vmod2_adc_coco_CallbackFunctionPointer != NULL)
  {
    return Mock.vmod2_adc_coco_CallbackFunctionPointer(Mock.vmod2_adc_coco_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'vmod2_adc_coco' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.vmod2_adc_coco_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.vmod2_adc_coco_FinalReturn;
    Mock.vmod2_adc_coco_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void vmod2_adc_coco_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod2_adc_coco_CALL_INSTANCE));
  CMOCK_vmod2_adc_coco_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod2_adc_coco_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod2_adc_coco_CallInstance = CMock_Guts_MemChain(Mock.vmod2_adc_coco_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.vmod2_adc_coco_IgnoreBool = (int)1;
}

void vmod2_adc_coco_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vmod2_adc_coco_CALL_INSTANCE));
  CMOCK_vmod2_adc_coco_CALL_INSTANCE* cmock_call_instance = (CMOCK_vmod2_adc_coco_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.vmod2_adc_coco_CallInstance = CMock_Guts_MemChain(Mock.vmod2_adc_coco_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void vmod2_adc_coco_StubWithCallback(CMOCK_vmod2_adc_coco_CALLBACK Callback)
{
  Mock.vmod2_adc_coco_CallbackFunctionPointer = Callback;
}

