/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockesdhc.h"

typedef struct _CMOCK_download_sdhc_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_download_sdhc_data_CALL_INSTANCE;

typedef struct _CMOCK_esdhc_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_esdhc_init_CALL_INSTANCE;

typedef struct _CMOCK_sd_card_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  uint8_t Expected_cmock_arg1;

} CMOCK_sd_card_init_CALL_INSTANCE;

typedef struct _CMOCK_sd_card_init_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_sd_card_init_callback_CALL_INSTANCE;

typedef struct _CMOCK_sd_card_rw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_sd_card_rw_CALL_INSTANCE;

typedef struct _CMOCK_sd_card_log_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  uint8_t Expected_cmock_arg1;
  SDHC_LOGGING_CMDS Expected_cmock_arg2;
  uint8_t* Expected_cmock_arg3;

} CMOCK_sd_card_log_CALL_INSTANCE;

typedef struct _CMOCK_log2sdhc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_log2sdhc_CALL_INSTANCE;

static struct MockesdhcInstance
{
  int download_sdhc_data_IgnoreBool;
  uint8_t download_sdhc_data_FinalReturn;
  CMOCK_download_sdhc_data_CALLBACK download_sdhc_data_CallbackFunctionPointer;
  int download_sdhc_data_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE download_sdhc_data_CallInstance;
  int esdhc_init_IgnoreBool;
  uint8_t esdhc_init_FinalReturn;
  CMOCK_esdhc_init_CALLBACK esdhc_init_CallbackFunctionPointer;
  int esdhc_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esdhc_init_CallInstance;
  int sd_card_init_IgnoreBool;
  uint8_t sd_card_init_FinalReturn;
  CMOCK_sd_card_init_CALLBACK sd_card_init_CallbackFunctionPointer;
  int sd_card_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sd_card_init_CallInstance;
  int sd_card_init_callback_IgnoreBool;
  uint8_t sd_card_init_callback_FinalReturn;
  CMOCK_sd_card_init_callback_CALLBACK sd_card_init_callback_CallbackFunctionPointer;
  int sd_card_init_callback_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sd_card_init_callback_CallInstance;
  int sd_card_rw_IgnoreBool;
  uint8_t sd_card_rw_FinalReturn;
  CMOCK_sd_card_rw_CALLBACK sd_card_rw_CallbackFunctionPointer;
  int sd_card_rw_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sd_card_rw_CallInstance;
  int sd_card_log_IgnoreBool;
  uint8_t sd_card_log_FinalReturn;
  CMOCK_sd_card_log_CALLBACK sd_card_log_CallbackFunctionPointer;
  int sd_card_log_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE sd_card_log_CallInstance;
  int log2sdhc_IgnoreBool;
  uint8_t log2sdhc_FinalReturn;
  CMOCK_log2sdhc_CALLBACK log2sdhc_CallbackFunctionPointer;
  int log2sdhc_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE log2sdhc_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockesdhc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.download_sdhc_data_IgnoreBool)
    Mock.download_sdhc_data_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.download_sdhc_data_CallInstance, cmock_line, "Function 'download_sdhc_data' called less times than expected.");
  if (Mock.download_sdhc_data_CallbackFunctionPointer != NULL)
    Mock.download_sdhc_data_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.esdhc_init_IgnoreBool)
    Mock.esdhc_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.esdhc_init_CallInstance, cmock_line, "Function 'esdhc_init' called less times than expected.");
  if (Mock.esdhc_init_CallbackFunctionPointer != NULL)
    Mock.esdhc_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sd_card_init_IgnoreBool)
    Mock.sd_card_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sd_card_init_CallInstance, cmock_line, "Function 'sd_card_init' called less times than expected.");
  if (Mock.sd_card_init_CallbackFunctionPointer != NULL)
    Mock.sd_card_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sd_card_init_callback_IgnoreBool)
    Mock.sd_card_init_callback_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sd_card_init_callback_CallInstance, cmock_line, "Function 'sd_card_init_callback' called less times than expected.");
  if (Mock.sd_card_init_callback_CallbackFunctionPointer != NULL)
    Mock.sd_card_init_callback_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sd_card_rw_IgnoreBool)
    Mock.sd_card_rw_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sd_card_rw_CallInstance, cmock_line, "Function 'sd_card_rw' called less times than expected.");
  if (Mock.sd_card_rw_CallbackFunctionPointer != NULL)
    Mock.sd_card_rw_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.sd_card_log_IgnoreBool)
    Mock.sd_card_log_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sd_card_log_CallInstance, cmock_line, "Function 'sd_card_log' called less times than expected.");
  if (Mock.sd_card_log_CallbackFunctionPointer != NULL)
    Mock.sd_card_log_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.log2sdhc_IgnoreBool)
    Mock.log2sdhc_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.log2sdhc_CallInstance, cmock_line, "Function 'log2sdhc' called less times than expected.");
  if (Mock.log2sdhc_CallbackFunctionPointer != NULL)
    Mock.log2sdhc_CallInstance = CMOCK_GUTS_NONE;
}

void Mockesdhc_Init(void)
{
  Mockesdhc_Destroy();
}

void Mockesdhc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.download_sdhc_data_CallbackFunctionPointer = NULL;
  Mock.download_sdhc_data_CallbackCalls = 0;
  Mock.esdhc_init_CallbackFunctionPointer = NULL;
  Mock.esdhc_init_CallbackCalls = 0;
  Mock.sd_card_init_CallbackFunctionPointer = NULL;
  Mock.sd_card_init_CallbackCalls = 0;
  Mock.sd_card_init_callback_CallbackFunctionPointer = NULL;
  Mock.sd_card_init_callback_CallbackCalls = 0;
  Mock.sd_card_rw_CallbackFunctionPointer = NULL;
  Mock.sd_card_rw_CallbackCalls = 0;
  Mock.sd_card_log_CallbackFunctionPointer = NULL;
  Mock.sd_card_log_CallbackCalls = 0;
  Mock.log2sdhc_CallbackFunctionPointer = NULL;
  Mock.log2sdhc_CallbackCalls = 0;
}

uint8_t download_sdhc_data(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_download_sdhc_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_download_sdhc_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.download_sdhc_data_CallInstance);
  Mock.download_sdhc_data_CallInstance = CMock_Guts_MemNext(Mock.download_sdhc_data_CallInstance);
  if (Mock.download_sdhc_data_CallbackFunctionPointer != NULL)
  {
    return Mock.download_sdhc_data_CallbackFunctionPointer(Mock.download_sdhc_data_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'download_sdhc_data' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.download_sdhc_data_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.download_sdhc_data_FinalReturn;
    Mock.download_sdhc_data_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void download_sdhc_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_download_sdhc_data_CALL_INSTANCE));
  CMOCK_download_sdhc_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_download_sdhc_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.download_sdhc_data_CallInstance = CMock_Guts_MemChain(Mock.download_sdhc_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.download_sdhc_data_IgnoreBool = (int)1;
}

void download_sdhc_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_download_sdhc_data_CALL_INSTANCE));
  CMOCK_download_sdhc_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_download_sdhc_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.download_sdhc_data_CallInstance = CMock_Guts_MemChain(Mock.download_sdhc_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void download_sdhc_data_StubWithCallback(CMOCK_download_sdhc_data_CALLBACK Callback)
{
  Mock.download_sdhc_data_CallbackFunctionPointer = Callback;
}

uint8_t esdhc_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esdhc_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_esdhc_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esdhc_init_CallInstance);
  Mock.esdhc_init_CallInstance = CMock_Guts_MemNext(Mock.esdhc_init_CallInstance);
  if (Mock.esdhc_init_CallbackFunctionPointer != NULL)
  {
    return Mock.esdhc_init_CallbackFunctionPointer(Mock.esdhc_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'esdhc_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.esdhc_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.esdhc_init_FinalReturn;
    Mock.esdhc_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void esdhc_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esdhc_init_CALL_INSTANCE));
  CMOCK_esdhc_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_esdhc_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.esdhc_init_CallInstance = CMock_Guts_MemChain(Mock.esdhc_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esdhc_init_IgnoreBool = (int)1;
}

void esdhc_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esdhc_init_CALL_INSTANCE));
  CMOCK_esdhc_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_esdhc_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.esdhc_init_CallInstance = CMock_Guts_MemChain(Mock.esdhc_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esdhc_init_StubWithCallback(CMOCK_esdhc_init_CALLBACK Callback)
{
  Mock.esdhc_init_CallbackFunctionPointer = Callback;
}

uint8_t sd_card_init(uint8_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sd_card_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sd_card_init_CallInstance);
  Mock.sd_card_init_CallInstance = CMock_Guts_MemNext(Mock.sd_card_init_CallInstance);
  if (Mock.sd_card_init_CallbackFunctionPointer != NULL)
  {
    return Mock.sd_card_init_CallbackFunctionPointer(cmock_arg1, Mock.sd_card_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sd_card_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.sd_card_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.sd_card_init_FinalReturn;
    Mock.sd_card_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'sd_card_init' called with unexpected value for argument 'cmock_arg1'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sd_card_init(CMOCK_sd_card_init_CALL_INSTANCE* cmock_call_instance, uint8_t cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void sd_card_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sd_card_init_CALL_INSTANCE));
  CMOCK_sd_card_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sd_card_init_CallInstance = CMock_Guts_MemChain(Mock.sd_card_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sd_card_init_IgnoreBool = (int)1;
}

void sd_card_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sd_card_init_CALL_INSTANCE));
  CMOCK_sd_card_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sd_card_init_CallInstance = CMock_Guts_MemChain(Mock.sd_card_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sd_card_init(cmock_call_instance, cmock_arg1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void sd_card_init_StubWithCallback(CMOCK_sd_card_init_CALLBACK Callback)
{
  Mock.sd_card_init_CallbackFunctionPointer = Callback;
}

uint8_t sd_card_init_callback(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sd_card_init_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_init_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sd_card_init_callback_CallInstance);
  Mock.sd_card_init_callback_CallInstance = CMock_Guts_MemNext(Mock.sd_card_init_callback_CallInstance);
  if (Mock.sd_card_init_callback_CallbackFunctionPointer != NULL)
  {
    return Mock.sd_card_init_callback_CallbackFunctionPointer(Mock.sd_card_init_callback_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sd_card_init_callback' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.sd_card_init_callback_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.sd_card_init_callback_FinalReturn;
    Mock.sd_card_init_callback_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void sd_card_init_callback_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sd_card_init_callback_CALL_INSTANCE));
  CMOCK_sd_card_init_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_init_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sd_card_init_callback_CallInstance = CMock_Guts_MemChain(Mock.sd_card_init_callback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sd_card_init_callback_IgnoreBool = (int)1;
}

void sd_card_init_callback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sd_card_init_callback_CALL_INSTANCE));
  CMOCK_sd_card_init_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_init_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sd_card_init_callback_CallInstance = CMock_Guts_MemChain(Mock.sd_card_init_callback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void sd_card_init_callback_StubWithCallback(CMOCK_sd_card_init_callback_CALLBACK Callback)
{
  Mock.sd_card_init_callback_CallbackFunctionPointer = Callback;
}

uint8_t sd_card_rw(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sd_card_rw_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_rw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sd_card_rw_CallInstance);
  Mock.sd_card_rw_CallInstance = CMock_Guts_MemNext(Mock.sd_card_rw_CallInstance);
  if (Mock.sd_card_rw_CallbackFunctionPointer != NULL)
  {
    return Mock.sd_card_rw_CallbackFunctionPointer(Mock.sd_card_rw_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sd_card_rw' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.sd_card_rw_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.sd_card_rw_FinalReturn;
    Mock.sd_card_rw_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void sd_card_rw_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sd_card_rw_CALL_INSTANCE));
  CMOCK_sd_card_rw_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_rw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sd_card_rw_CallInstance = CMock_Guts_MemChain(Mock.sd_card_rw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sd_card_rw_IgnoreBool = (int)1;
}

void sd_card_rw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sd_card_rw_CALL_INSTANCE));
  CMOCK_sd_card_rw_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_rw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sd_card_rw_CallInstance = CMock_Guts_MemChain(Mock.sd_card_rw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void sd_card_rw_StubWithCallback(CMOCK_sd_card_rw_CALLBACK Callback)
{
  Mock.sd_card_rw_CallbackFunctionPointer = Callback;
}

uint8_t sd_card_log(uint8_t cmock_arg1, SDHC_LOGGING_CMDS cmock_arg2, uint8_t* cmock_arg3)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sd_card_log_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_log_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sd_card_log_CallInstance);
  Mock.sd_card_log_CallInstance = CMock_Guts_MemNext(Mock.sd_card_log_CallInstance);
  if (Mock.sd_card_log_CallbackFunctionPointer != NULL)
  {
    return Mock.sd_card_log_CallbackFunctionPointer(cmock_arg1, cmock_arg2, cmock_arg3, Mock.sd_card_log_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'sd_card_log' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.sd_card_log_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.sd_card_log_FinalReturn;
    Mock.sd_card_log_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, "Function 'sd_card_log' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg2), (void*)(&cmock_arg2), sizeof(SDHC_LOGGING_CMDS), cmock_line, "Function 'sd_card_log' called with unexpected value for argument 'cmock_arg2'.");
  if (cmock_call_instance->Expected_cmock_arg3 == NULL)
    { UNITY_TEST_ASSERT_NULL(cmock_arg3, cmock_line, "Expected NULL. Function 'sd_card_log' called with unexpected value for argument 'cmock_arg3'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_cmock_arg3, cmock_arg3, 1, cmock_line, "Function 'sd_card_log' called with unexpected value for argument 'cmock_arg3'."); }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_sd_card_log(CMOCK_sd_card_log_CALL_INSTANCE* cmock_call_instance, uint8_t cmock_arg1, SDHC_LOGGING_CMDS cmock_arg2, uint8_t* cmock_arg3)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  memcpy(&cmock_call_instance->Expected_cmock_arg2, &cmock_arg2, sizeof(SDHC_LOGGING_CMDS));
  cmock_call_instance->Expected_cmock_arg3 = cmock_arg3;
}

void sd_card_log_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sd_card_log_CALL_INSTANCE));
  CMOCK_sd_card_log_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_log_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sd_card_log_CallInstance = CMock_Guts_MemChain(Mock.sd_card_log_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.sd_card_log_IgnoreBool = (int)1;
}

void sd_card_log_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1, SDHC_LOGGING_CMDS cmock_arg2, uint8_t* cmock_arg3, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sd_card_log_CALL_INSTANCE));
  CMOCK_sd_card_log_CALL_INSTANCE* cmock_call_instance = (CMOCK_sd_card_log_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.sd_card_log_CallInstance = CMock_Guts_MemChain(Mock.sd_card_log_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_sd_card_log(cmock_call_instance, cmock_arg1, cmock_arg2, cmock_arg3);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void sd_card_log_StubWithCallback(CMOCK_sd_card_log_CALLBACK Callback)
{
  Mock.sd_card_log_CallbackFunctionPointer = Callback;
}

uint8_t log2sdhc(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_log2sdhc_CALL_INSTANCE* cmock_call_instance = (CMOCK_log2sdhc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.log2sdhc_CallInstance);
  Mock.log2sdhc_CallInstance = CMock_Guts_MemNext(Mock.log2sdhc_CallInstance);
  if (Mock.log2sdhc_CallbackFunctionPointer != NULL)
  {
    return Mock.log2sdhc_CallbackFunctionPointer(Mock.log2sdhc_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'log2sdhc' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.log2sdhc_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.log2sdhc_FinalReturn;
    Mock.log2sdhc_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void log2sdhc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_log2sdhc_CALL_INSTANCE));
  CMOCK_log2sdhc_CALL_INSTANCE* cmock_call_instance = (CMOCK_log2sdhc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.log2sdhc_CallInstance = CMock_Guts_MemChain(Mock.log2sdhc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.log2sdhc_IgnoreBool = (int)1;
}

void log2sdhc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_log2sdhc_CALL_INSTANCE));
  CMOCK_log2sdhc_CALL_INSTANCE* cmock_call_instance = (CMOCK_log2sdhc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.log2sdhc_CallInstance = CMock_Guts_MemChain(Mock.log2sdhc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void log2sdhc_StubWithCallback(CMOCK_log2sdhc_CALLBACK Callback)
{
  Mock.log2sdhc_CallbackFunctionPointer = Callback;
}

