/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFOOTPEDAL_H
#define _MOCKFOOTPEDAL_H

#include "Types.h"
#include "footpedal.h"

void Mockfootpedal_Init(void);
void Mockfootpedal_Destroy(void);
void Mockfootpedal_Verify(void);




#define poll_footpedal_IgnoreAndReturn(cmock_retval) poll_footpedal_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void poll_footpedal_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define poll_footpedal_ExpectAndReturn(cmock_retval) poll_footpedal_CMockExpectAndReturn(__LINE__, cmock_retval)
void poll_footpedal_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_poll_footpedal_CALLBACK)(int cmock_num_calls);
void poll_footpedal_StubWithCallback(CMOCK_poll_footpedal_CALLBACK Callback);
#define foot_pedal_init_IgnoreAndReturn(cmock_retval) foot_pedal_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void foot_pedal_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define foot_pedal_init_ExpectAndReturn(cmock_retval) foot_pedal_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void foot_pedal_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_foot_pedal_init_CALLBACK)(int cmock_num_calls);
void foot_pedal_init_StubWithCallback(CMOCK_foot_pedal_init_CALLBACK Callback);
#define check_fs_stuck_IgnoreAndReturn(cmock_retval) check_fs_stuck_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void check_fs_stuck_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define check_fs_stuck_ExpectAndReturn(cmock_retval) check_fs_stuck_CMockExpectAndReturn(__LINE__, cmock_retval)
void check_fs_stuck_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_check_fs_stuck_CALLBACK)(int cmock_num_calls);
void check_fs_stuck_StubWithCallback(CMOCK_check_fs_stuck_CALLBACK Callback);
#define fs_any_button_pressed_IgnoreAndReturn(cmock_retval) fs_any_button_pressed_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void fs_any_button_pressed_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define fs_any_button_pressed_ExpectAndReturn(cmock_retval) fs_any_button_pressed_CMockExpectAndReturn(__LINE__, cmock_retval)
void fs_any_button_pressed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
typedef bool (* CMOCK_fs_any_button_pressed_CALLBACK)(int cmock_num_calls);
void fs_any_button_pressed_StubWithCallback(CMOCK_fs_any_button_pressed_CALLBACK Callback);

#endif
