/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKGUI_H
#define _MOCKGUI_H

#include "Types.h"
#include "gui.h"

void Mockgui_Init(void);
void Mockgui_Destroy(void);
void Mockgui_Verify(void);




#define update_gui_IgnoreAndReturn(cmock_retval) update_gui_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void update_gui_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define update_gui_ExpectAndReturn(cmock_retval) update_gui_CMockExpectAndReturn(__LINE__, cmock_retval)
void update_gui_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_update_gui_CALLBACK)(int cmock_num_calls);
void update_gui_StubWithCallback(CMOCK_update_gui_CALLBACK Callback);
#define update_screen_IgnoreAndReturn(cmock_retval) update_screen_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void update_screen_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define update_screen_ExpectAndReturn(cmock_retval) update_screen_CMockExpectAndReturn(__LINE__, cmock_retval)
void update_screen_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_update_screen_CALLBACK)(int cmock_num_calls);
void update_screen_StubWithCallback(CMOCK_update_screen_CALLBACK Callback);
#define load_screen01_IgnoreAndReturn(cmock_retval) load_screen01_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void load_screen01_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define load_screen01_ExpectAndReturn(cmock_retval) load_screen01_CMockExpectAndReturn(__LINE__, cmock_retval)
void load_screen01_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_load_screen01_CALLBACK)(int cmock_num_calls);
void load_screen01_StubWithCallback(CMOCK_load_screen01_CALLBACK Callback);
#define get_priming_status_IgnoreAndReturn(cmock_retval) get_priming_status_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_priming_status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, prime_mode_t cmock_to_return);
#define get_priming_status_ExpectAndReturn(cmock_retval) get_priming_status_CMockExpectAndReturn(__LINE__, cmock_retval)
void get_priming_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, prime_mode_t cmock_to_return);
typedef prime_mode_t (* CMOCK_get_priming_status_CALLBACK)(int cmock_num_calls);
void get_priming_status_StubWithCallback(CMOCK_get_priming_status_CALLBACK Callback);
#define gui_stop_manual_prime_Ignore() gui_stop_manual_prime_CMockIgnore(__LINE__)
void gui_stop_manual_prime_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define gui_stop_manual_prime_Expect() gui_stop_manual_prime_CMockExpect(__LINE__)
void gui_stop_manual_prime_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_gui_stop_manual_prime_CALLBACK)(int cmock_num_calls);
void gui_stop_manual_prime_StubWithCallback(CMOCK_gui_stop_manual_prime_CALLBACK Callback);
#define change_flow_manta_IgnoreAndReturn(cmock_retval) change_flow_manta_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void change_flow_manta_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define change_flow_manta_ExpectAndReturn(coag_level, new_flow, cmock_retval) change_flow_manta_CMockExpectAndReturn(__LINE__, coag_level, new_flow, cmock_retval)
void change_flow_manta_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t coag_level, uint8_t new_flow, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_change_flow_manta_CALLBACK)(uint8_t coag_level, uint8_t new_flow, int cmock_num_calls);
void change_flow_manta_StubWithCallback(CMOCK_change_flow_manta_CALLBACK Callback);
#define gui_stop_auto_prime_Ignore() gui_stop_auto_prime_CMockIgnore(__LINE__)
void gui_stop_auto_prime_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define gui_stop_auto_prime_Expect() gui_stop_auto_prime_CMockExpect(__LINE__)
void gui_stop_auto_prime_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_gui_stop_auto_prime_CALLBACK)(int cmock_num_calls);
void gui_stop_auto_prime_StubWithCallback(CMOCK_gui_stop_auto_prime_CALLBACK Callback);
#define gui_clear_auto_prime_event_Ignore() gui_clear_auto_prime_event_CMockIgnore(__LINE__)
void gui_clear_auto_prime_event_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define gui_clear_auto_prime_event_Expect() gui_clear_auto_prime_event_CMockExpect(__LINE__)
void gui_clear_auto_prime_event_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_gui_clear_auto_prime_event_CALLBACK)(int cmock_num_calls);
void gui_clear_auto_prime_event_StubWithCallback(CMOCK_gui_clear_auto_prime_event_CALLBACK Callback);

#endif
