/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockevent_buffer.h"

typedef struct _CMOCK_put_event_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  event_table* Expected_cmock_arg1;
  event Expected_cmock_arg2;

} CMOCK_put_event_CALL_INSTANCE;

typedef struct _CMOCK_get_event_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  event ReturnVal;
  event_table* Expected_cmock_arg1;

} CMOCK_get_event_CALL_INSTANCE;

typedef struct _CMOCK_flush_buffer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  event_table* Expected_cmock_arg1;

} CMOCK_flush_buffer_CALL_INSTANCE;

static struct Mockevent_bufferInstance
{
  int put_event_IgnoreBool;
  uint8_t put_event_FinalReturn;
  CMOCK_put_event_CALLBACK put_event_CallbackFunctionPointer;
  int put_event_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE put_event_CallInstance;
  int get_event_IgnoreBool;
  event get_event_FinalReturn;
  CMOCK_get_event_CALLBACK get_event_CallbackFunctionPointer;
  int get_event_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_event_CallInstance;
  int flush_buffer_IgnoreBool;
  CMOCK_flush_buffer_CALLBACK flush_buffer_CallbackFunctionPointer;
  int flush_buffer_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE flush_buffer_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockevent_buffer_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.put_event_IgnoreBool)
    Mock.put_event_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.put_event_CallInstance, cmock_line, "Function 'put_event' called less times than expected.");
  if (Mock.put_event_CallbackFunctionPointer != NULL)
    Mock.put_event_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.get_event_IgnoreBool)
    Mock.get_event_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.get_event_CallInstance, cmock_line, "Function 'get_event' called less times than expected.");
  if (Mock.get_event_CallbackFunctionPointer != NULL)
    Mock.get_event_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.flush_buffer_IgnoreBool)
    Mock.flush_buffer_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.flush_buffer_CallInstance, cmock_line, "Function 'flush_buffer' called less times than expected.");
  if (Mock.flush_buffer_CallbackFunctionPointer != NULL)
    Mock.flush_buffer_CallInstance = CMOCK_GUTS_NONE;
}

void Mockevent_buffer_Init(void)
{
  Mockevent_buffer_Destroy();
}

void Mockevent_buffer_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.put_event_CallbackFunctionPointer = NULL;
  Mock.put_event_CallbackCalls = 0;
  Mock.get_event_CallbackFunctionPointer = NULL;
  Mock.get_event_CallbackCalls = 0;
  Mock.flush_buffer_CallbackFunctionPointer = NULL;
  Mock.flush_buffer_CallbackCalls = 0;
}

uint8_t put_event(event_table* cmock_arg1, event cmock_arg2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_put_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_put_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.put_event_CallInstance);
  Mock.put_event_CallInstance = CMock_Guts_MemNext(Mock.put_event_CallInstance);
  if (Mock.put_event_CallbackFunctionPointer != NULL)
  {
    return Mock.put_event_CallbackFunctionPointer(cmock_arg1, cmock_arg2, Mock.put_event_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'put_event' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.put_event_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.put_event_FinalReturn;
    Mock.put_event_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(event_table), cmock_line, "Function 'put_event' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg2), (void*)(&cmock_arg2), sizeof(event), cmock_line, "Function 'put_event' called with unexpected value for argument 'cmock_arg2'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_put_event(CMOCK_put_event_CALL_INSTANCE* cmock_call_instance, event_table* cmock_arg1, event cmock_arg2)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  memcpy(&cmock_call_instance->Expected_cmock_arg2, &cmock_arg2, sizeof(event));
}

void put_event_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_put_event_CALL_INSTANCE));
  CMOCK_put_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_put_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.put_event_CallInstance = CMock_Guts_MemChain(Mock.put_event_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.put_event_IgnoreBool = (int)1;
}

void put_event_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, event_table* cmock_arg1, event cmock_arg2, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_put_event_CALL_INSTANCE));
  CMOCK_put_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_put_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.put_event_CallInstance = CMock_Guts_MemChain(Mock.put_event_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_put_event(cmock_call_instance, cmock_arg1, cmock_arg2);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void put_event_StubWithCallback(CMOCK_put_event_CALLBACK Callback)
{
  Mock.put_event_CallbackFunctionPointer = Callback;
}

event get_event(event_table* cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_event_CallInstance);
  Mock.get_event_CallInstance = CMock_Guts_MemNext(Mock.get_event_CallInstance);
  if (Mock.get_event_CallbackFunctionPointer != NULL)
  {
    return Mock.get_event_CallbackFunctionPointer(cmock_arg1, Mock.get_event_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'get_event' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.get_event_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.get_event_FinalReturn;
    memcpy(&Mock.get_event_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(event));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(event_table), cmock_line, "Function 'get_event' called with unexpected value for argument 'cmock_arg1'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_event(CMOCK_get_event_CALL_INSTANCE* cmock_call_instance, event_table* cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void get_event_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, event cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_event_CALL_INSTANCE));
  CMOCK_get_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.get_event_CallInstance = CMock_Guts_MemChain(Mock.get_event_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_event_IgnoreBool = (int)1;
}

void get_event_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, event_table* cmock_arg1, event cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_event_CALL_INSTANCE));
  CMOCK_get_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.get_event_CallInstance = CMock_Guts_MemChain(Mock.get_event_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_get_event(cmock_call_instance, cmock_arg1);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(event));
}

void get_event_StubWithCallback(CMOCK_get_event_CALLBACK Callback)
{
  Mock.get_event_CallbackFunctionPointer = Callback;
}

void flush_buffer(event_table* cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_flush_buffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_flush_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.flush_buffer_CallInstance);
  Mock.flush_buffer_CallInstance = CMock_Guts_MemNext(Mock.flush_buffer_CallInstance);
  if (Mock.flush_buffer_CallbackFunctionPointer != NULL)
  {
    Mock.flush_buffer_CallbackFunctionPointer(cmock_arg1, Mock.flush_buffer_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'flush_buffer' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.flush_buffer_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(event_table), cmock_line, "Function 'flush_buffer' called with unexpected value for argument 'cmock_arg1'.");
}

void CMockExpectParameters_flush_buffer(CMOCK_flush_buffer_CALL_INSTANCE* cmock_call_instance, event_table* cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void flush_buffer_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flush_buffer_CALL_INSTANCE));
  CMOCK_flush_buffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_flush_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flush_buffer_CallInstance = CMock_Guts_MemChain(Mock.flush_buffer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.flush_buffer_IgnoreBool = (int)1;
}

void flush_buffer_CMockExpect(UNITY_LINE_TYPE cmock_line, event_table* cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_flush_buffer_CALL_INSTANCE));
  CMOCK_flush_buffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_flush_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.flush_buffer_CallInstance = CMock_Guts_MemChain(Mock.flush_buffer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_flush_buffer(cmock_call_instance, cmock_arg1);
}

void flush_buffer_StubWithCallback(CMOCK_flush_buffer_CALLBACK Callback)
{
  Mock.flush_buffer_CallbackFunctionPointer = Callback;
}

