/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKLED_H
#define _MOCKLED_H

#include "Types.h"
#include "led.h"

void Mockled_Init(void);
void Mockled_Destroy(void);
void Mockled_Verify(void);




#define pcf8575_iic_write_Ignore() pcf8575_iic_write_CMockIgnore(__LINE__)
void pcf8575_iic_write_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define pcf8575_iic_write_Expect(cmock_arg1) pcf8575_iic_write_CMockExpect(__LINE__, cmock_arg1)
void pcf8575_iic_write_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1);
typedef void (* CMOCK_pcf8575_iic_write_CALLBACK)(uint8_t cmock_arg1, int cmock_num_calls);
void pcf8575_iic_write_StubWithCallback(CMOCK_pcf8575_iic_write_CALLBACK Callback);
#define PCF8575_I2C_StartTransmission_Ignore() PCF8575_I2C_StartTransmission_CMockIgnore(__LINE__)
void PCF8575_I2C_StartTransmission_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define PCF8575_I2C_StartTransmission_Expect(cmock_arg1) PCF8575_I2C_StartTransmission_CMockExpect(__LINE__, cmock_arg1)
void PCF8575_I2C_StartTransmission_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1);
typedef void (* CMOCK_PCF8575_I2C_StartTransmission_CALLBACK)(uint8_t cmock_arg1, int cmock_num_calls);
void PCF8575_I2C_StartTransmission_StubWithCallback(CMOCK_PCF8575_I2C_StartTransmission_CALLBACK Callback);
#define led_init_IgnoreAndReturn(cmock_retval) led_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void led_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define led_init_ExpectAndReturn(cmock_retval) led_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void led_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_led_init_CALLBACK)(int cmock_num_calls);
void led_init_StubWithCallback(CMOCK_led_init_CALLBACK Callback);
#define update_leds_IgnoreAndReturn(cmock_retval) update_leds_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void update_leds_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define update_leds_ExpectAndReturn(cmock_retval) update_leds_CMockExpectAndReturn(__LINE__, cmock_retval)
void update_leds_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_update_leds_CALLBACK)(int cmock_num_calls);
void update_leds_StubWithCallback(CMOCK_update_leds_CALLBACK Callback);
#define startup_leds_IgnoreAndReturn(cmock_retval) startup_leds_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void startup_leds_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define startup_leds_ExpectAndReturn(cmock_retval) startup_leds_CMockExpectAndReturn(__LINE__, cmock_retval)
void startup_leds_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_startup_leds_CALLBACK)(int cmock_num_calls);
void startup_leds_StubWithCallback(CMOCK_startup_leds_CALLBACK Callback);
#define shutdown_led_sequence_IgnoreAndReturn(cmock_retval) shutdown_led_sequence_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void shutdown_led_sequence_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define shutdown_led_sequence_ExpectAndReturn(cmock_retval) shutdown_led_sequence_CMockExpectAndReturn(__LINE__, cmock_retval)
void shutdown_led_sequence_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_shutdown_led_sequence_CALLBACK)(int cmock_num_calls);
void shutdown_led_sequence_StubWithCallback(CMOCK_shutdown_led_sequence_CALLBACK Callback);
#define startup_led_init_IgnoreAndReturn(cmock_retval) startup_led_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void startup_led_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define startup_led_init_ExpectAndReturn(cmock_retval) startup_led_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void startup_led_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_startup_led_init_CALLBACK)(int cmock_num_calls);
void startup_led_init_StubWithCallback(CMOCK_startup_led_init_CALLBACK Callback);
#define startup_led_sequence_Ignore() startup_led_sequence_CMockIgnore(__LINE__)
void startup_led_sequence_CMockIgnore(UNITY_LINE_TYPE cmock_line);
#define startup_led_sequence_Expect(cmock_arg1) startup_led_sequence_CMockExpect(__LINE__, cmock_arg1)
void startup_led_sequence_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t cmock_arg1);
typedef void (* CMOCK_startup_led_sequence_CALLBACK)(uint8_t cmock_arg1, int cmock_num_calls);
void startup_led_sequence_StubWithCallback(CMOCK_startup_led_sequence_CALLBACK Callback);

#endif
