/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockgui.h"

typedef struct _CMOCK_update_gui_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_update_gui_CALL_INSTANCE;

typedef struct _CMOCK_update_screen_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_update_screen_CALL_INSTANCE;

typedef struct _CMOCK_load_screen01_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_load_screen01_CALL_INSTANCE;

typedef struct _CMOCK_get_priming_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  prime_mode_t ReturnVal;

} CMOCK_get_priming_status_CALL_INSTANCE;

typedef struct _CMOCK_gui_stop_manual_prime_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_gui_stop_manual_prime_CALL_INSTANCE;

typedef struct _CMOCK_change_flow_manta_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  uint8_t Expected_coag_level;
  uint8_t Expected_new_flow;

} CMOCK_change_flow_manta_CALL_INSTANCE;

typedef struct _CMOCK_gui_stop_auto_prime_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_gui_stop_auto_prime_CALL_INSTANCE;

typedef struct _CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE;

static struct MockguiInstance
{
  int update_gui_IgnoreBool;
  uint8_t update_gui_FinalReturn;
  CMOCK_update_gui_CALLBACK update_gui_CallbackFunctionPointer;
  int update_gui_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE update_gui_CallInstance;
  int update_screen_IgnoreBool;
  uint8_t update_screen_FinalReturn;
  CMOCK_update_screen_CALLBACK update_screen_CallbackFunctionPointer;
  int update_screen_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE update_screen_CallInstance;
  int load_screen01_IgnoreBool;
  uint8_t load_screen01_FinalReturn;
  CMOCK_load_screen01_CALLBACK load_screen01_CallbackFunctionPointer;
  int load_screen01_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE load_screen01_CallInstance;
  int get_priming_status_IgnoreBool;
  prime_mode_t get_priming_status_FinalReturn;
  CMOCK_get_priming_status_CALLBACK get_priming_status_CallbackFunctionPointer;
  int get_priming_status_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_priming_status_CallInstance;
  int gui_stop_manual_prime_IgnoreBool;
  CMOCK_gui_stop_manual_prime_CALLBACK gui_stop_manual_prime_CallbackFunctionPointer;
  int gui_stop_manual_prime_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE gui_stop_manual_prime_CallInstance;
  int change_flow_manta_IgnoreBool;
  uint8_t change_flow_manta_FinalReturn;
  CMOCK_change_flow_manta_CALLBACK change_flow_manta_CallbackFunctionPointer;
  int change_flow_manta_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE change_flow_manta_CallInstance;
  int gui_stop_auto_prime_IgnoreBool;
  CMOCK_gui_stop_auto_prime_CALLBACK gui_stop_auto_prime_CallbackFunctionPointer;
  int gui_stop_auto_prime_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE gui_stop_auto_prime_CallInstance;
  int gui_clear_auto_prime_event_IgnoreBool;
  CMOCK_gui_clear_auto_prime_event_CALLBACK gui_clear_auto_prime_event_CallbackFunctionPointer;
  int gui_clear_auto_prime_event_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE gui_clear_auto_prime_event_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockgui_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.update_gui_IgnoreBool)
    Mock.update_gui_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.update_gui_CallInstance, cmock_line, "Function 'update_gui' called less times than expected.");
  if (Mock.update_gui_CallbackFunctionPointer != NULL)
    Mock.update_gui_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.update_screen_IgnoreBool)
    Mock.update_screen_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.update_screen_CallInstance, cmock_line, "Function 'update_screen' called less times than expected.");
  if (Mock.update_screen_CallbackFunctionPointer != NULL)
    Mock.update_screen_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.load_screen01_IgnoreBool)
    Mock.load_screen01_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.load_screen01_CallInstance, cmock_line, "Function 'load_screen01' called less times than expected.");
  if (Mock.load_screen01_CallbackFunctionPointer != NULL)
    Mock.load_screen01_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.get_priming_status_IgnoreBool)
    Mock.get_priming_status_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.get_priming_status_CallInstance, cmock_line, "Function 'get_priming_status' called less times than expected.");
  if (Mock.get_priming_status_CallbackFunctionPointer != NULL)
    Mock.get_priming_status_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.gui_stop_manual_prime_IgnoreBool)
    Mock.gui_stop_manual_prime_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.gui_stop_manual_prime_CallInstance, cmock_line, "Function 'gui_stop_manual_prime' called less times than expected.");
  if (Mock.gui_stop_manual_prime_CallbackFunctionPointer != NULL)
    Mock.gui_stop_manual_prime_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.change_flow_manta_IgnoreBool)
    Mock.change_flow_manta_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.change_flow_manta_CallInstance, cmock_line, "Function 'change_flow_manta' called less times than expected.");
  if (Mock.change_flow_manta_CallbackFunctionPointer != NULL)
    Mock.change_flow_manta_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.gui_stop_auto_prime_IgnoreBool)
    Mock.gui_stop_auto_prime_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.gui_stop_auto_prime_CallInstance, cmock_line, "Function 'gui_stop_auto_prime' called less times than expected.");
  if (Mock.gui_stop_auto_prime_CallbackFunctionPointer != NULL)
    Mock.gui_stop_auto_prime_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.gui_clear_auto_prime_event_IgnoreBool)
    Mock.gui_clear_auto_prime_event_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.gui_clear_auto_prime_event_CallInstance, cmock_line, "Function 'gui_clear_auto_prime_event' called less times than expected.");
  if (Mock.gui_clear_auto_prime_event_CallbackFunctionPointer != NULL)
    Mock.gui_clear_auto_prime_event_CallInstance = CMOCK_GUTS_NONE;
}

void Mockgui_Init(void)
{
  Mockgui_Destroy();
}

void Mockgui_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.update_gui_CallbackFunctionPointer = NULL;
  Mock.update_gui_CallbackCalls = 0;
  Mock.update_screen_CallbackFunctionPointer = NULL;
  Mock.update_screen_CallbackCalls = 0;
  Mock.load_screen01_CallbackFunctionPointer = NULL;
  Mock.load_screen01_CallbackCalls = 0;
  Mock.get_priming_status_CallbackFunctionPointer = NULL;
  Mock.get_priming_status_CallbackCalls = 0;
  Mock.gui_stop_manual_prime_CallbackFunctionPointer = NULL;
  Mock.gui_stop_manual_prime_CallbackCalls = 0;
  Mock.change_flow_manta_CallbackFunctionPointer = NULL;
  Mock.change_flow_manta_CallbackCalls = 0;
  Mock.gui_stop_auto_prime_CallbackFunctionPointer = NULL;
  Mock.gui_stop_auto_prime_CallbackCalls = 0;
  Mock.gui_clear_auto_prime_event_CallbackFunctionPointer = NULL;
  Mock.gui_clear_auto_prime_event_CallbackCalls = 0;
}

uint8_t update_gui(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_update_gui_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_gui_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.update_gui_CallInstance);
  Mock.update_gui_CallInstance = CMock_Guts_MemNext(Mock.update_gui_CallInstance);
  if (Mock.update_gui_CallbackFunctionPointer != NULL)
  {
    return Mock.update_gui_CallbackFunctionPointer(Mock.update_gui_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'update_gui' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.update_gui_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.update_gui_FinalReturn;
    Mock.update_gui_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void update_gui_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_update_gui_CALL_INSTANCE));
  CMOCK_update_gui_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_gui_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.update_gui_CallInstance = CMock_Guts_MemChain(Mock.update_gui_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.update_gui_IgnoreBool = (int)1;
}

void update_gui_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_update_gui_CALL_INSTANCE));
  CMOCK_update_gui_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_gui_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.update_gui_CallInstance = CMock_Guts_MemChain(Mock.update_gui_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void update_gui_StubWithCallback(CMOCK_update_gui_CALLBACK Callback)
{
  Mock.update_gui_CallbackFunctionPointer = Callback;
}

uint8_t update_screen(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_update_screen_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_screen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.update_screen_CallInstance);
  Mock.update_screen_CallInstance = CMock_Guts_MemNext(Mock.update_screen_CallInstance);
  if (Mock.update_screen_CallbackFunctionPointer != NULL)
  {
    return Mock.update_screen_CallbackFunctionPointer(Mock.update_screen_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'update_screen' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.update_screen_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.update_screen_FinalReturn;
    Mock.update_screen_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void update_screen_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_update_screen_CALL_INSTANCE));
  CMOCK_update_screen_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_screen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.update_screen_CallInstance = CMock_Guts_MemChain(Mock.update_screen_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.update_screen_IgnoreBool = (int)1;
}

void update_screen_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_update_screen_CALL_INSTANCE));
  CMOCK_update_screen_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_screen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.update_screen_CallInstance = CMock_Guts_MemChain(Mock.update_screen_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void update_screen_StubWithCallback(CMOCK_update_screen_CALLBACK Callback)
{
  Mock.update_screen_CallbackFunctionPointer = Callback;
}

uint8_t load_screen01(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_load_screen01_CALL_INSTANCE* cmock_call_instance = (CMOCK_load_screen01_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.load_screen01_CallInstance);
  Mock.load_screen01_CallInstance = CMock_Guts_MemNext(Mock.load_screen01_CallInstance);
  if (Mock.load_screen01_CallbackFunctionPointer != NULL)
  {
    return Mock.load_screen01_CallbackFunctionPointer(Mock.load_screen01_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'load_screen01' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.load_screen01_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.load_screen01_FinalReturn;
    Mock.load_screen01_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void load_screen01_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_load_screen01_CALL_INSTANCE));
  CMOCK_load_screen01_CALL_INSTANCE* cmock_call_instance = (CMOCK_load_screen01_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.load_screen01_CallInstance = CMock_Guts_MemChain(Mock.load_screen01_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.load_screen01_IgnoreBool = (int)1;
}

void load_screen01_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_load_screen01_CALL_INSTANCE));
  CMOCK_load_screen01_CALL_INSTANCE* cmock_call_instance = (CMOCK_load_screen01_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.load_screen01_CallInstance = CMock_Guts_MemChain(Mock.load_screen01_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void load_screen01_StubWithCallback(CMOCK_load_screen01_CALLBACK Callback)
{
  Mock.load_screen01_CallbackFunctionPointer = Callback;
}

prime_mode_t get_priming_status(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_priming_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_priming_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_priming_status_CallInstance);
  Mock.get_priming_status_CallInstance = CMock_Guts_MemNext(Mock.get_priming_status_CallInstance);
  if (Mock.get_priming_status_CallbackFunctionPointer != NULL)
  {
    return Mock.get_priming_status_CallbackFunctionPointer(Mock.get_priming_status_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'get_priming_status' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.get_priming_status_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.get_priming_status_FinalReturn;
    memcpy(&Mock.get_priming_status_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(prime_mode_t));
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void get_priming_status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, prime_mode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_priming_status_CALL_INSTANCE));
  CMOCK_get_priming_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_priming_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.get_priming_status_CallInstance = CMock_Guts_MemChain(Mock.get_priming_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_priming_status_IgnoreBool = (int)1;
}

void get_priming_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, prime_mode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_priming_status_CALL_INSTANCE));
  CMOCK_get_priming_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_priming_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.get_priming_status_CallInstance = CMock_Guts_MemChain(Mock.get_priming_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(prime_mode_t));
}

void get_priming_status_StubWithCallback(CMOCK_get_priming_status_CALLBACK Callback)
{
  Mock.get_priming_status_CallbackFunctionPointer = Callback;
}

void gui_stop_manual_prime(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gui_stop_manual_prime_CALL_INSTANCE* cmock_call_instance = (CMOCK_gui_stop_manual_prime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gui_stop_manual_prime_CallInstance);
  Mock.gui_stop_manual_prime_CallInstance = CMock_Guts_MemNext(Mock.gui_stop_manual_prime_CallInstance);
  if (Mock.gui_stop_manual_prime_CallbackFunctionPointer != NULL)
  {
    Mock.gui_stop_manual_prime_CallbackFunctionPointer(Mock.gui_stop_manual_prime_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'gui_stop_manual_prime' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.gui_stop_manual_prime_IgnoreBool)
  {
    return;
  }
}

void gui_stop_manual_prime_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gui_stop_manual_prime_CALL_INSTANCE));
  CMOCK_gui_stop_manual_prime_CALL_INSTANCE* cmock_call_instance = (CMOCK_gui_stop_manual_prime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.gui_stop_manual_prime_CallInstance = CMock_Guts_MemChain(Mock.gui_stop_manual_prime_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.gui_stop_manual_prime_IgnoreBool = (int)1;
}

void gui_stop_manual_prime_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gui_stop_manual_prime_CALL_INSTANCE));
  CMOCK_gui_stop_manual_prime_CALL_INSTANCE* cmock_call_instance = (CMOCK_gui_stop_manual_prime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.gui_stop_manual_prime_CallInstance = CMock_Guts_MemChain(Mock.gui_stop_manual_prime_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void gui_stop_manual_prime_StubWithCallback(CMOCK_gui_stop_manual_prime_CALLBACK Callback)
{
  Mock.gui_stop_manual_prime_CallbackFunctionPointer = Callback;
}

uint8_t change_flow_manta(uint8_t coag_level, uint8_t new_flow)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_change_flow_manta_CALL_INSTANCE* cmock_call_instance = (CMOCK_change_flow_manta_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.change_flow_manta_CallInstance);
  Mock.change_flow_manta_CallInstance = CMock_Guts_MemNext(Mock.change_flow_manta_CallInstance);
  if (Mock.change_flow_manta_CallbackFunctionPointer != NULL)
  {
    return Mock.change_flow_manta_CallbackFunctionPointer(coag_level, new_flow, Mock.change_flow_manta_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'change_flow_manta' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.change_flow_manta_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.change_flow_manta_FinalReturn;
    Mock.change_flow_manta_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_coag_level, coag_level, cmock_line, "Function 'change_flow_manta' called with unexpected value for argument 'coag_level'.");
  UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_new_flow, new_flow, cmock_line, "Function 'change_flow_manta' called with unexpected value for argument 'new_flow'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_change_flow_manta(CMOCK_change_flow_manta_CALL_INSTANCE* cmock_call_instance, uint8_t coag_level, uint8_t new_flow)
{
  cmock_call_instance->Expected_coag_level = coag_level;
  cmock_call_instance->Expected_new_flow = new_flow;
}

void change_flow_manta_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_change_flow_manta_CALL_INSTANCE));
  CMOCK_change_flow_manta_CALL_INSTANCE* cmock_call_instance = (CMOCK_change_flow_manta_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.change_flow_manta_CallInstance = CMock_Guts_MemChain(Mock.change_flow_manta_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.change_flow_manta_IgnoreBool = (int)1;
}

void change_flow_manta_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t coag_level, uint8_t new_flow, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_change_flow_manta_CALL_INSTANCE));
  CMOCK_change_flow_manta_CALL_INSTANCE* cmock_call_instance = (CMOCK_change_flow_manta_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.change_flow_manta_CallInstance = CMock_Guts_MemChain(Mock.change_flow_manta_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_change_flow_manta(cmock_call_instance, coag_level, new_flow);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void change_flow_manta_StubWithCallback(CMOCK_change_flow_manta_CALLBACK Callback)
{
  Mock.change_flow_manta_CallbackFunctionPointer = Callback;
}

void gui_stop_auto_prime(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gui_stop_auto_prime_CALL_INSTANCE* cmock_call_instance = (CMOCK_gui_stop_auto_prime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gui_stop_auto_prime_CallInstance);
  Mock.gui_stop_auto_prime_CallInstance = CMock_Guts_MemNext(Mock.gui_stop_auto_prime_CallInstance);
  if (Mock.gui_stop_auto_prime_CallbackFunctionPointer != NULL)
  {
    Mock.gui_stop_auto_prime_CallbackFunctionPointer(Mock.gui_stop_auto_prime_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'gui_stop_auto_prime' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.gui_stop_auto_prime_IgnoreBool)
  {
    return;
  }
}

void gui_stop_auto_prime_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gui_stop_auto_prime_CALL_INSTANCE));
  CMOCK_gui_stop_auto_prime_CALL_INSTANCE* cmock_call_instance = (CMOCK_gui_stop_auto_prime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.gui_stop_auto_prime_CallInstance = CMock_Guts_MemChain(Mock.gui_stop_auto_prime_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.gui_stop_auto_prime_IgnoreBool = (int)1;
}

void gui_stop_auto_prime_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gui_stop_auto_prime_CALL_INSTANCE));
  CMOCK_gui_stop_auto_prime_CALL_INSTANCE* cmock_call_instance = (CMOCK_gui_stop_auto_prime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.gui_stop_auto_prime_CallInstance = CMock_Guts_MemChain(Mock.gui_stop_auto_prime_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void gui_stop_auto_prime_StubWithCallback(CMOCK_gui_stop_auto_prime_CALLBACK Callback)
{
  Mock.gui_stop_auto_prime_CallbackFunctionPointer = Callback;
}

void gui_clear_auto_prime_event(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gui_clear_auto_prime_event_CallInstance);
  Mock.gui_clear_auto_prime_event_CallInstance = CMock_Guts_MemNext(Mock.gui_clear_auto_prime_event_CallInstance);
  if (Mock.gui_clear_auto_prime_event_CallbackFunctionPointer != NULL)
  {
    Mock.gui_clear_auto_prime_event_CallbackFunctionPointer(Mock.gui_clear_auto_prime_event_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'gui_clear_auto_prime_event' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.gui_clear_auto_prime_event_IgnoreBool)
  {
    return;
  }
}

void gui_clear_auto_prime_event_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE));
  CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.gui_clear_auto_prime_event_CallInstance = CMock_Guts_MemChain(Mock.gui_clear_auto_prime_event_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.gui_clear_auto_prime_event_IgnoreBool = (int)1;
}

void gui_clear_auto_prime_event_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE));
  CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_gui_clear_auto_prime_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.gui_clear_auto_prime_event_CallInstance = CMock_Guts_MemChain(Mock.gui_clear_auto_prime_event_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void gui_clear_auto_prime_event_StubWithCallback(CMOCK_gui_clear_auto_prime_event_CALLBACK Callback)
{
  Mock.gui_clear_auto_prime_event_CallbackFunctionPointer = Callback;
}

