/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockrtc.h"

typedef struct _CMOCK_rtc_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_rtc_init_CALL_INSTANCE;

typedef struct _CMOCK_rtc_check_errors_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_rtc_check_errors_CALL_INSTANCE;

static struct MockrtcInstance
{
  int rtc_init_IgnoreBool;
  uint32_t rtc_init_FinalReturn;
  CMOCK_rtc_init_CALLBACK rtc_init_CallbackFunctionPointer;
  int rtc_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rtc_init_CallInstance;
  int rtc_check_errors_IgnoreBool;
  CMOCK_rtc_check_errors_CALLBACK rtc_check_errors_CallbackFunctionPointer;
  int rtc_check_errors_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rtc_check_errors_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockrtc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.rtc_init_IgnoreBool)
    Mock.rtc_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rtc_init_CallInstance, cmock_line, "Function 'rtc_init' called less times than expected.");
  if (Mock.rtc_init_CallbackFunctionPointer != NULL)
    Mock.rtc_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rtc_check_errors_IgnoreBool)
    Mock.rtc_check_errors_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rtc_check_errors_CallInstance, cmock_line, "Function 'rtc_check_errors' called less times than expected.");
  if (Mock.rtc_check_errors_CallbackFunctionPointer != NULL)
    Mock.rtc_check_errors_CallInstance = CMOCK_GUTS_NONE;
}

void Mockrtc_Init(void)
{
  Mockrtc_Destroy();
}

void Mockrtc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.rtc_init_CallbackFunctionPointer = NULL;
  Mock.rtc_init_CallbackCalls = 0;
  Mock.rtc_check_errors_CallbackFunctionPointer = NULL;
  Mock.rtc_check_errors_CallbackCalls = 0;
}

uint32_t rtc_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rtc_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rtc_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rtc_init_CallInstance);
  Mock.rtc_init_CallInstance = CMock_Guts_MemNext(Mock.rtc_init_CallInstance);
  if (Mock.rtc_init_CallbackFunctionPointer != NULL)
  {
    return Mock.rtc_init_CallbackFunctionPointer(Mock.rtc_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rtc_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.rtc_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.rtc_init_FinalReturn;
    Mock.rtc_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void rtc_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rtc_init_CALL_INSTANCE));
  CMOCK_rtc_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rtc_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.rtc_init_CallInstance = CMock_Guts_MemChain(Mock.rtc_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rtc_init_IgnoreBool = (int)1;
}

void rtc_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rtc_init_CALL_INSTANCE));
  CMOCK_rtc_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rtc_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.rtc_init_CallInstance = CMock_Guts_MemChain(Mock.rtc_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void rtc_init_StubWithCallback(CMOCK_rtc_init_CALLBACK Callback)
{
  Mock.rtc_init_CallbackFunctionPointer = Callback;
}

void rtc_check_errors(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rtc_check_errors_CALL_INSTANCE* cmock_call_instance = (CMOCK_rtc_check_errors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rtc_check_errors_CallInstance);
  Mock.rtc_check_errors_CallInstance = CMock_Guts_MemNext(Mock.rtc_check_errors_CallInstance);
  if (Mock.rtc_check_errors_CallbackFunctionPointer != NULL)
  {
    Mock.rtc_check_errors_CallbackFunctionPointer(Mock.rtc_check_errors_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rtc_check_errors' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.rtc_check_errors_IgnoreBool)
  {
    return;
  }
}

void rtc_check_errors_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rtc_check_errors_CALL_INSTANCE));
  CMOCK_rtc_check_errors_CALL_INSTANCE* cmock_call_instance = (CMOCK_rtc_check_errors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.rtc_check_errors_CallInstance = CMock_Guts_MemChain(Mock.rtc_check_errors_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.rtc_check_errors_IgnoreBool = (int)1;
}

void rtc_check_errors_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rtc_check_errors_CALL_INSTANCE));
  CMOCK_rtc_check_errors_CALL_INSTANCE* cmock_call_instance = (CMOCK_rtc_check_errors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.rtc_check_errors_CallInstance = CMock_Guts_MemChain(Mock.rtc_check_errors_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void rtc_check_errors_StubWithCallback(CMOCK_rtc_check_errors_CALLBACK Callback)
{
  Mock.rtc_check_errors_CallbackFunctionPointer = Callback;
}

