/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockartc_arm_math.h"

typedef struct _CMOCK_arm_fir_q15_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  arm_fir_instance_q15* Expected_cmock_arg1;
  q15_t* Expected_cmock_arg2;
  q15_t* Expected_cmock_arg3;
  uint32_t Expected_cmock_arg4;

} CMOCK_arm_fir_q15_CALL_INSTANCE;

typedef struct _CMOCK_arm_fir_init_q15_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  arm_status ReturnVal;
  arm_fir_instance_q15* Expected_cmock_arg1;
  uint16_t Expected_cmock_arg2;
  q15_t* Expected_cmock_arg3;
  q15_t* Expected_cmock_arg4;
  uint32_t Expected_cmock_arg5;

} CMOCK_arm_fir_init_q15_CALL_INSTANCE;

typedef struct _CMOCK_arm_mean_q15_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  q15_t* Expected_cmock_arg1;
  uint32_t Expected_cmock_arg2;
  q15_t* Expected_cmock_arg3;

} CMOCK_arm_mean_q15_CALL_INSTANCE;

typedef struct _CMOCK_arm_sqrt_f32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  arm_status ReturnVal;
  float32_t Expected_in;
  float32_t* Expected_pOut;

} CMOCK_arm_sqrt_f32_CALL_INSTANCE;

static struct Mockartc_arm_mathInstance
{
  int arm_fir_q15_IgnoreBool;
  CMOCK_arm_fir_q15_CALLBACK arm_fir_q15_CallbackFunctionPointer;
  int arm_fir_q15_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE arm_fir_q15_CallInstance;
  int arm_fir_init_q15_IgnoreBool;
  arm_status arm_fir_init_q15_FinalReturn;
  CMOCK_arm_fir_init_q15_CALLBACK arm_fir_init_q15_CallbackFunctionPointer;
  int arm_fir_init_q15_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE arm_fir_init_q15_CallInstance;
  int arm_mean_q15_IgnoreBool;
  CMOCK_arm_mean_q15_CALLBACK arm_mean_q15_CallbackFunctionPointer;
  int arm_mean_q15_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE arm_mean_q15_CallInstance;
  int arm_sqrt_f32_IgnoreBool;
  arm_status arm_sqrt_f32_FinalReturn;
  CMOCK_arm_sqrt_f32_CALLBACK arm_sqrt_f32_CallbackFunctionPointer;
  int arm_sqrt_f32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE arm_sqrt_f32_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockartc_arm_math_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.arm_fir_q15_IgnoreBool)
    Mock.arm_fir_q15_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arm_fir_q15_CallInstance, cmock_line, "Function 'arm_fir_q15' called less times than expected.");
  if (Mock.arm_fir_q15_CallbackFunctionPointer != NULL)
    Mock.arm_fir_q15_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.arm_fir_init_q15_IgnoreBool)
    Mock.arm_fir_init_q15_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arm_fir_init_q15_CallInstance, cmock_line, "Function 'arm_fir_init_q15' called less times than expected.");
  if (Mock.arm_fir_init_q15_CallbackFunctionPointer != NULL)
    Mock.arm_fir_init_q15_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.arm_mean_q15_IgnoreBool)
    Mock.arm_mean_q15_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arm_mean_q15_CallInstance, cmock_line, "Function 'arm_mean_q15' called less times than expected.");
  if (Mock.arm_mean_q15_CallbackFunctionPointer != NULL)
    Mock.arm_mean_q15_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.arm_sqrt_f32_IgnoreBool)
    Mock.arm_sqrt_f32_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.arm_sqrt_f32_CallInstance, cmock_line, "Function 'arm_sqrt_f32' called less times than expected.");
  if (Mock.arm_sqrt_f32_CallbackFunctionPointer != NULL)
    Mock.arm_sqrt_f32_CallInstance = CMOCK_GUTS_NONE;
}

void Mockartc_arm_math_Init(void)
{
  Mockartc_arm_math_Destroy();
}

void Mockartc_arm_math_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.arm_fir_q15_CallbackFunctionPointer = NULL;
  Mock.arm_fir_q15_CallbackCalls = 0;
  Mock.arm_fir_init_q15_CallbackFunctionPointer = NULL;
  Mock.arm_fir_init_q15_CallbackCalls = 0;
  Mock.arm_mean_q15_CallbackFunctionPointer = NULL;
  Mock.arm_mean_q15_CallbackCalls = 0;
  Mock.arm_sqrt_f32_CallbackFunctionPointer = NULL;
  Mock.arm_sqrt_f32_CallbackCalls = 0;
}

void arm_fir_q15(const arm_fir_instance_q15* cmock_arg1, q15_t* cmock_arg2, q15_t* cmock_arg3, uint32_t cmock_arg4)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arm_fir_q15_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_fir_q15_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arm_fir_q15_CallInstance);
  Mock.arm_fir_q15_CallInstance = CMock_Guts_MemNext(Mock.arm_fir_q15_CallInstance);
  if (Mock.arm_fir_q15_CallbackFunctionPointer != NULL)
  {
    Mock.arm_fir_q15_CallbackFunctionPointer(cmock_arg1, cmock_arg2, cmock_arg3, cmock_arg4, Mock.arm_fir_q15_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'arm_fir_q15' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.arm_fir_q15_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(arm_fir_instance_q15), cmock_line, "Function 'arm_fir_q15' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg2), (void*)(cmock_arg2), sizeof(q15_t), cmock_line, "Function 'arm_fir_q15' called with unexpected value for argument 'cmock_arg2'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg3), (void*)(cmock_arg3), sizeof(q15_t), cmock_line, "Function 'arm_fir_q15' called with unexpected value for argument 'cmock_arg3'.");
  UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_cmock_arg4, cmock_arg4, cmock_line, "Function 'arm_fir_q15' called with unexpected value for argument 'cmock_arg4'.");
}

void CMockExpectParameters_arm_fir_q15(CMOCK_arm_fir_q15_CALL_INSTANCE* cmock_call_instance, const arm_fir_instance_q15* cmock_arg1, q15_t* cmock_arg2, q15_t* cmock_arg3, uint32_t cmock_arg4)
{
  cmock_call_instance->Expected_cmock_arg1 = (arm_fir_instance_q15*)cmock_arg1;
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
  cmock_call_instance->Expected_cmock_arg3 = cmock_arg3;
  cmock_call_instance->Expected_cmock_arg4 = cmock_arg4;
}

void arm_fir_q15_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arm_fir_q15_CALL_INSTANCE));
  CMOCK_arm_fir_q15_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_fir_q15_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.arm_fir_q15_CallInstance = CMock_Guts_MemChain(Mock.arm_fir_q15_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.arm_fir_q15_IgnoreBool = (int)1;
}

void arm_fir_q15_CMockExpect(UNITY_LINE_TYPE cmock_line, const arm_fir_instance_q15* cmock_arg1, q15_t* cmock_arg2, q15_t* cmock_arg3, uint32_t cmock_arg4)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arm_fir_q15_CALL_INSTANCE));
  CMOCK_arm_fir_q15_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_fir_q15_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.arm_fir_q15_CallInstance = CMock_Guts_MemChain(Mock.arm_fir_q15_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_arm_fir_q15(cmock_call_instance, cmock_arg1, cmock_arg2, cmock_arg3, cmock_arg4);
}

void arm_fir_q15_StubWithCallback(CMOCK_arm_fir_q15_CALLBACK Callback)
{
  Mock.arm_fir_q15_CallbackFunctionPointer = Callback;
}

arm_status arm_fir_init_q15(arm_fir_instance_q15* cmock_arg1, uint16_t cmock_arg2, q15_t* cmock_arg3, q15_t* cmock_arg4, uint32_t cmock_arg5)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arm_fir_init_q15_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_fir_init_q15_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arm_fir_init_q15_CallInstance);
  Mock.arm_fir_init_q15_CallInstance = CMock_Guts_MemNext(Mock.arm_fir_init_q15_CallInstance);
  if (Mock.arm_fir_init_q15_CallbackFunctionPointer != NULL)
  {
    return Mock.arm_fir_init_q15_CallbackFunctionPointer(cmock_arg1, cmock_arg2, cmock_arg3, cmock_arg4, cmock_arg5, Mock.arm_fir_init_q15_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'arm_fir_init_q15' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.arm_fir_init_q15_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.arm_fir_init_q15_FinalReturn;
    memcpy(&Mock.arm_fir_init_q15_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(arm_status));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(arm_fir_instance_q15), cmock_line, "Function 'arm_fir_init_q15' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, cmock_line, "Function 'arm_fir_init_q15' called with unexpected value for argument 'cmock_arg2'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg3), (void*)(cmock_arg3), sizeof(q15_t), cmock_line, "Function 'arm_fir_init_q15' called with unexpected value for argument 'cmock_arg3'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg4), (void*)(cmock_arg4), sizeof(q15_t), cmock_line, "Function 'arm_fir_init_q15' called with unexpected value for argument 'cmock_arg4'.");
  UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_cmock_arg5, cmock_arg5, cmock_line, "Function 'arm_fir_init_q15' called with unexpected value for argument 'cmock_arg5'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_arm_fir_init_q15(CMOCK_arm_fir_init_q15_CALL_INSTANCE* cmock_call_instance, arm_fir_instance_q15* cmock_arg1, uint16_t cmock_arg2, q15_t* cmock_arg3, q15_t* cmock_arg4, uint32_t cmock_arg5)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
  cmock_call_instance->Expected_cmock_arg3 = cmock_arg3;
  cmock_call_instance->Expected_cmock_arg4 = cmock_arg4;
  cmock_call_instance->Expected_cmock_arg5 = cmock_arg5;
}

void arm_fir_init_q15_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, arm_status cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arm_fir_init_q15_CALL_INSTANCE));
  CMOCK_arm_fir_init_q15_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_fir_init_q15_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.arm_fir_init_q15_CallInstance = CMock_Guts_MemChain(Mock.arm_fir_init_q15_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.arm_fir_init_q15_IgnoreBool = (int)1;
}

void arm_fir_init_q15_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, arm_fir_instance_q15* cmock_arg1, uint16_t cmock_arg2, q15_t* cmock_arg3, q15_t* cmock_arg4, uint32_t cmock_arg5, arm_status cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arm_fir_init_q15_CALL_INSTANCE));
  CMOCK_arm_fir_init_q15_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_fir_init_q15_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.arm_fir_init_q15_CallInstance = CMock_Guts_MemChain(Mock.arm_fir_init_q15_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_arm_fir_init_q15(cmock_call_instance, cmock_arg1, cmock_arg2, cmock_arg3, cmock_arg4, cmock_arg5);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(arm_status));
}

void arm_fir_init_q15_StubWithCallback(CMOCK_arm_fir_init_q15_CALLBACK Callback)
{
  Mock.arm_fir_init_q15_CallbackFunctionPointer = Callback;
}

void arm_mean_q15(q15_t* cmock_arg1, uint32_t cmock_arg2, q15_t* cmock_arg3)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arm_mean_q15_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_mean_q15_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arm_mean_q15_CallInstance);
  Mock.arm_mean_q15_CallInstance = CMock_Guts_MemNext(Mock.arm_mean_q15_CallInstance);
  if (Mock.arm_mean_q15_CallbackFunctionPointer != NULL)
  {
    Mock.arm_mean_q15_CallbackFunctionPointer(cmock_arg1, cmock_arg2, cmock_arg3, Mock.arm_mean_q15_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'arm_mean_q15' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.arm_mean_q15_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(q15_t), cmock_line, "Function 'arm_mean_q15' called with unexpected value for argument 'cmock_arg1'.");
  UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_cmock_arg2, cmock_arg2, cmock_line, "Function 'arm_mean_q15' called with unexpected value for argument 'cmock_arg2'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg3), (void*)(cmock_arg3), sizeof(q15_t), cmock_line, "Function 'arm_mean_q15' called with unexpected value for argument 'cmock_arg3'.");
}

void CMockExpectParameters_arm_mean_q15(CMOCK_arm_mean_q15_CALL_INSTANCE* cmock_call_instance, q15_t* cmock_arg1, uint32_t cmock_arg2, q15_t* cmock_arg3)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg2 = cmock_arg2;
  cmock_call_instance->Expected_cmock_arg3 = cmock_arg3;
}

void arm_mean_q15_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arm_mean_q15_CALL_INSTANCE));
  CMOCK_arm_mean_q15_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_mean_q15_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.arm_mean_q15_CallInstance = CMock_Guts_MemChain(Mock.arm_mean_q15_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  Mock.arm_mean_q15_IgnoreBool = (int)1;
}

void arm_mean_q15_CMockExpect(UNITY_LINE_TYPE cmock_line, q15_t* cmock_arg1, uint32_t cmock_arg2, q15_t* cmock_arg3)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arm_mean_q15_CALL_INSTANCE));
  CMOCK_arm_mean_q15_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_mean_q15_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.arm_mean_q15_CallInstance = CMock_Guts_MemChain(Mock.arm_mean_q15_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_arm_mean_q15(cmock_call_instance, cmock_arg1, cmock_arg2, cmock_arg3);
}

void arm_mean_q15_StubWithCallback(CMOCK_arm_mean_q15_CALLBACK Callback)
{
  Mock.arm_mean_q15_CallbackFunctionPointer = Callback;
}

arm_status arm_sqrt_f32(float32_t in, float32_t* pOut)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_arm_sqrt_f32_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_sqrt_f32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.arm_sqrt_f32_CallInstance);
  Mock.arm_sqrt_f32_CallInstance = CMock_Guts_MemNext(Mock.arm_sqrt_f32_CallInstance);
  if (Mock.arm_sqrt_f32_CallbackFunctionPointer != NULL)
  {
    return Mock.arm_sqrt_f32_CallbackFunctionPointer(in, pOut, Mock.arm_sqrt_f32_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'arm_sqrt_f32' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.arm_sqrt_f32_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.arm_sqrt_f32_FinalReturn;
    memcpy(&Mock.arm_sqrt_f32_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(arm_status));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_in), (void*)(&in), sizeof(float32_t), cmock_line, "Function 'arm_sqrt_f32' called with unexpected value for argument 'in'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOut), (void*)(pOut), sizeof(float32_t), cmock_line, "Function 'arm_sqrt_f32' called with unexpected value for argument 'pOut'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_arm_sqrt_f32(CMOCK_arm_sqrt_f32_CALL_INSTANCE* cmock_call_instance, float32_t in, float32_t* pOut)
{
  memcpy(&cmock_call_instance->Expected_in, &in, sizeof(float32_t));
  cmock_call_instance->Expected_pOut = pOut;
}

void arm_sqrt_f32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, arm_status cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arm_sqrt_f32_CALL_INSTANCE));
  CMOCK_arm_sqrt_f32_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_sqrt_f32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.arm_sqrt_f32_CallInstance = CMock_Guts_MemChain(Mock.arm_sqrt_f32_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.arm_sqrt_f32_IgnoreBool = (int)1;
}

void arm_sqrt_f32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float32_t in, float32_t* pOut, arm_status cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_arm_sqrt_f32_CALL_INSTANCE));
  CMOCK_arm_sqrt_f32_CALL_INSTANCE* cmock_call_instance = (CMOCK_arm_sqrt_f32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.arm_sqrt_f32_CallInstance = CMock_Guts_MemChain(Mock.arm_sqrt_f32_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_arm_sqrt_f32(cmock_call_instance, in, pOut);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(arm_status));
}

void arm_sqrt_f32_StubWithCallback(CMOCK_arm_sqrt_f32_CALLBACK Callback)
{
  Mock.arm_sqrt_f32_CallbackFunctionPointer = Callback;
}

