/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mocklpt.h"

typedef struct _CMOCK_lpt_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_lpt_init_CALL_INSTANCE;

typedef struct _CMOCK_reset_pulse_cnt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_reset_pulse_cnt_CALL_INSTANCE;

static struct MocklptInstance
{
  int lpt_init_IgnoreBool;
  uint8_t lpt_init_FinalReturn;
  CMOCK_lpt_init_CALLBACK lpt_init_CallbackFunctionPointer;
  int lpt_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE lpt_init_CallInstance;
  int reset_pulse_cnt_IgnoreBool;
  uint8_t reset_pulse_cnt_FinalReturn;
  CMOCK_reset_pulse_cnt_CALLBACK reset_pulse_cnt_CallbackFunctionPointer;
  int reset_pulse_cnt_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE reset_pulse_cnt_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocklpt_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.lpt_init_IgnoreBool)
    Mock.lpt_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.lpt_init_CallInstance, cmock_line, "Function 'lpt_init' called less times than expected.");
  if (Mock.lpt_init_CallbackFunctionPointer != NULL)
    Mock.lpt_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.reset_pulse_cnt_IgnoreBool)
    Mock.reset_pulse_cnt_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.reset_pulse_cnt_CallInstance, cmock_line, "Function 'reset_pulse_cnt' called less times than expected.");
  if (Mock.reset_pulse_cnt_CallbackFunctionPointer != NULL)
    Mock.reset_pulse_cnt_CallInstance = CMOCK_GUTS_NONE;
}

void Mocklpt_Init(void)
{
  Mocklpt_Destroy();
}

void Mocklpt_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.lpt_init_CallbackFunctionPointer = NULL;
  Mock.lpt_init_CallbackCalls = 0;
  Mock.reset_pulse_cnt_CallbackFunctionPointer = NULL;
  Mock.reset_pulse_cnt_CallbackCalls = 0;
}

uint8_t lpt_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_lpt_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_lpt_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lpt_init_CallInstance);
  Mock.lpt_init_CallInstance = CMock_Guts_MemNext(Mock.lpt_init_CallInstance);
  if (Mock.lpt_init_CallbackFunctionPointer != NULL)
  {
    return Mock.lpt_init_CallbackFunctionPointer(Mock.lpt_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'lpt_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.lpt_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.lpt_init_FinalReturn;
    Mock.lpt_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void lpt_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lpt_init_CALL_INSTANCE));
  CMOCK_lpt_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_lpt_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.lpt_init_CallInstance = CMock_Guts_MemChain(Mock.lpt_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.lpt_init_IgnoreBool = (int)1;
}

void lpt_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lpt_init_CALL_INSTANCE));
  CMOCK_lpt_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_lpt_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.lpt_init_CallInstance = CMock_Guts_MemChain(Mock.lpt_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void lpt_init_StubWithCallback(CMOCK_lpt_init_CALLBACK Callback)
{
  Mock.lpt_init_CallbackFunctionPointer = Callback;
}

uint8_t reset_pulse_cnt(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_reset_pulse_cnt_CALL_INSTANCE* cmock_call_instance = (CMOCK_reset_pulse_cnt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.reset_pulse_cnt_CallInstance);
  Mock.reset_pulse_cnt_CallInstance = CMock_Guts_MemNext(Mock.reset_pulse_cnt_CallInstance);
  if (Mock.reset_pulse_cnt_CallbackFunctionPointer != NULL)
  {
    return Mock.reset_pulse_cnt_CallbackFunctionPointer(Mock.reset_pulse_cnt_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'reset_pulse_cnt' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.reset_pulse_cnt_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.reset_pulse_cnt_FinalReturn;
    Mock.reset_pulse_cnt_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  return cmock_call_instance->ReturnVal;
}

void reset_pulse_cnt_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_reset_pulse_cnt_CALL_INSTANCE));
  CMOCK_reset_pulse_cnt_CALL_INSTANCE* cmock_call_instance = (CMOCK_reset_pulse_cnt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.reset_pulse_cnt_CallInstance = CMock_Guts_MemChain(Mock.reset_pulse_cnt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.reset_pulse_cnt_IgnoreBool = (int)1;
}

void reset_pulse_cnt_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_reset_pulse_cnt_CALL_INSTANCE));
  CMOCK_reset_pulse_cnt_CALL_INSTANCE* cmock_call_instance = (CMOCK_reset_pulse_cnt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.reset_pulse_cnt_CallInstance = CMock_Guts_MemChain(Mock.reset_pulse_cnt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void reset_pulse_cnt_StubWithCallback(CMOCK_reset_pulse_cnt_CALLBACK Callback)
{
  Mock.reset_pulse_cnt_CallbackFunctionPointer = Callback;
}

